---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade, ONTAP tools, VMware vSphere, HA, non-HA, low RPO backup, SRA adapter, vCenter Server 
summary: Mettez à niveau les ONTAP tools for VMware vSphere de la version 10.4 ou 10.5 à la version 10.6 pour les déploiements HA et non-HA en utilisant les pré-vérifications et les étapes de sauvegarde requises. 
---
= Mettez à niveau ONTAP tools for VMware vSphere 10.x vers 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau directement ONTAP tools for VMware vSphere 10.4 ou 10.5 vers 10.6. Pour mettre à niveau ONTAP tools for VMware vSphere 10.0, 10.1, 10.2 ou 10.3 vers 10.6, vous devez d'abord effectuer une mise à niveau vers 10.4 ou 10.5.

[NOTE]
====
* Pour les systèmes ASA r2, assurez-vous de mettre à niveau ONTAP tools for VMware vSphere vers la version 10.6 et ONTAP vers la version 9.16.1 avant de configurer davantage de zones de disponibilité de stockage (SAZ).
* Si la mise à niveau des ONTAP tools for VMware vSphere 10.4 ou 10.5 vers 10.6 échoue, vous ne pouvez pas revenir en arrière. Utilisez un faible RPO ou une restauration par snapshot pour rétablir la configuration. Pour ONTAP tools for VMware vSphere 10.3 et versions antérieures, utilisez un RPO nul pour rétablir la configuration. Après la restauration dans les environnements protégés, revalidez la protection des datastores et vérifiez l'état et les relations des groupes de protection.


====
.Avant de commencer
* Assurez-vous que tous les nœuds sont actifs avant de commencer la mise à niveau.
* Assurez-vous que le certificat système ONTAP et les certificats vCenter intégrés sont valides pendant au moins 5 jours. Si les certificats expirent plus tôt, la mise à niveau échoue.
* Assurez-vous d’avoir un cinquième disque d’une capacité de 100 Go sur tous les nœuds.
* Vérifiez que la configuration du nœud correspond aux spécifications du tableau ci-dessous.


|===
| Type de déploiement | Cœurs de processeur par nœud | Mémoire (Go) par nœud | Espace disque (Go) par nœud | Nombre total de cœurs du processeur | Mémoire totale (Go) | Espace disque total (Go) 


| Non HA petit | 9 | 18 | 350 | 9 | 18 | 350 


| Non HA Moyen | 13 | 26 | 350 | 13 | 26 | 350 


| HA petit | 9 | 18 | 350 | 27 | 54 | 1050 


| HA Moyen | 13 | 26 | 350 | 39 | 78 | 1050 


| HAUTE disponibilité | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Activez la sauvegarde à faible RPO et assurez-vous qu'une sauvegarde soit visible dans l'interface vSphere Client. Téléchargez le dossier de sauvegarde avant la mise à niveau.
* Une sauvegarde avec un RPO faible est recommandée.  Toutefois, dans un déploiement non HA, vous pouvez prendre un instantané mis au repos de la machine virtuelle des outils ONTAP avant la mise à niveau.
+
Se référer à link:../manage/backup-settings.html["Modifier les paramètres de sauvegarde"] et link:../manage/recover-backup.html["Récupérer la configuration des outils ONTAP"] pour plus d'informations sur la sauvegarde et la restauration.



.Étapes
. Télécharger les outils ONTAP pour VMware vSphere, mettez à niveau ISO vers la bibliothèque de contenu.
. Sur la page principale de la VM, sélectionnez *Actions* > *Modifier les paramètres*. Pour identifier le nom de la machine virtuelle principale :
+
.. Activer le shell de diagnostic sur n'importe quel nœud
.. Exécutez la commande suivante :
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. Sélectionnez le *fichier ISO de la bibliothèque de contenu* dans la fenêtre des paramètres d'édition sous le champ *lecteur CD/DVD*.
. Sélectionnez le fichier ISO, cochez la case *Connecté* pour le champ *lecteur CD/DVD* et cliquez sur *OK*.
. Connectez-vous au serveur vCenter.
. Localisez la machine virtuelle principale des ONTAP tools et lancez la console Web.
. Connectez-vous en utilisant les `maint` identifiants.
. Entrez *2* pour sélectionner le menu *Configuration système*.
. Saisissez *6* pour sélectionner l'option *Mise à niveau*.
. Fournissez les informations d'identification vCenter lorsque vous y êtes invité. Il s'agit de l'instance vCenter sur laquelle les outils ONTAP sont hébergés.
+
Si vous utilisez les outils ONTAP dans une topologie à deux serveurs vCenter—où l'appliance est hébergée dans une instance vCenter et en gère une autre, vous pouvez attribuer un rôle restreint à l'instance vCenter hébergeant les outils ONTAP. Vous pouvez créer un utilisateur et un rôle vCenter dédiés, disposant uniquement des autorisations nécessaires au déploiement du modèle OVF. Pour plus de détails, consultez les rôles listés dans link:../concepts/rbac-vcenter-use.html#vsphere-object-hierarchy["Rôles inclus avec les outils ONTAP pour VMware vSphere 10"].

+
Pour l'instance vCenter qui sera gérée par les outils ONTAP , assurez-vous que le compte utilisateur vCenter dispose des privilèges d'administrateur.

+
Pendant la mise à niveau, si des certificats backend de stockage intégrés manquent d'entrées de nom alternatif du sujet (SAN), vous recevrez une invite indiquant le SAN manquant.  Si vous choisissez de continuer sans valider le SAN, la mise à niveau se poursuivra, mais cela n'est pas recommandé en raison de risques de sécurité potentiels.

. Lorsque vous effectuez une mise à niveau, les actions suivantes sont automatiquement exécutées :
+
.. Le certificat de passerelle est renouvelé pour une période de validité d'un an. Lorsque vous supprimez l'ancien adaptateur SRA et chargez le nouvel adaptateur 10.6, la validité du certificat SRA passe de 10 ans à 1 an.
.. Le plug-in distant est mis à niveau
.. Les certificats ONTAP et vCenter Server sont validés et ajoutés aux outils ONTAP
.. La sauvegarde est activée
.. Si des paramètres de protection du cluster hôte existent à partir des versions 10.5 ou antérieures, ONTAP tools crée un élément de navigation distinct *Cluster protection configuration* lors de la mise à niveau.




.Et la suite
Après la mise à niveau vers ONTAP tools for VMware vSphere 10.6 :

* Surveillez les alertes système et prévoyez de renouveler le certificat de passerelle avant son expiration dans un an.
* Supprimez l'adaptateur SRA des ONTAP tools 10.4 ou 10.5 et téléchargez le fichier tar de l'adaptateur SRA 10.6.
* Exécutez la commande d'installation après avoir téléchargé l'archive tar de l'adaptateur SRA. Ensuite, analysez à nouveau les adaptateurs SRA pour mettre à jour la page des adaptateurs de réplication de stockage VMware Site Recovery.
* Ouvrez la *configuration de protection du cluster* et vérifiez que les paramètres de protection du cluster hôte existants sont présents et correctement mappés.


Après la mise à niveau, vous pouvez :

* Désactiver les services depuis le gestionnaire d'outils ONTAP
* Passez d'une configuration non HA à une configuration haute disponibilité
* Faites évoluer une petite configuration non HA vers une configuration moyenne non HA, ou vers une configuration moyenne ou grande HA.


.Informations associées
link:../migrate/migrate-to-latest-ontaptools.html["Migrez des ONTAP tools for VMware vSphere 9.x vers 10.6"]
