---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: La mise à niveau est prise en charge pour les déploiements haute disponibilité et non haute disponibilité. 
---
= Mise à niveau des ONTAP tools for VMware vSphere 10.x vers 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une mise à niveau des ONTAP tools for VMware vSphere 10.3 ou 10.4 vers 10.5.  Cependant, pour effectuer une mise à niveau des outils ONTAP 10.0, 10.1 ou 10.2 vers 10.5, vous devez d'abord effectuer une mise à niveau vers 10.3 ou 10.4 avant de passer à 10.5.

REMARQUE :

* Pour les systèmes ASA r2, assurez-vous de mettre à niveau les ONTAP tools for VMware vSphere vers 10.5 et ONTAP vers 9.16.1, avant de configurer davantage de zones de disponibilité de stockage (SAZ).
* Si la mise à niveau des ONTAP tools for VMware vSphere 10.3 ou 10.4 vers 10.5 échoue, vous ne pouvez pas revenir en arrière.  Utilisez un RPO faible ou une récupération de snapshot pour restaurer la configuration.  Pour les ONTAP tools for VMware vSphere 10.2 et versions antérieures, utilisez le RPO zéro pour restaurer la configuration.


.Avant de commencer
* Assurez-vous que le certificat système ONTAP et les certificats vCenter intégrés sont valides pendant au moins 5 jours.  Si elle expire plus tôt, la mise à niveau échoue.
* Pour garantir une mise à niveau sécurisée, vérifiez que vos certificats incluent des entrées de nom alternatif du sujet (SAN).  Si vos certificats manquent d'entrées SAN et que vous devez procéder à la mise à niveau, vous pouvez définir l'indicateur de validation du certificat sur faux pour contourner les vérifications SAN dans l'invite pendant la mise à niveau.
* Assurez-vous d’avoir un cinquième disque d’une capacité de 100 Go sur tous les nœuds.
* Vérifiez que la configuration du nœud correspond aux spécifications du tableau ci-dessous.


|===
| Type de déploiement | CPU (Core) par nœud | Mémoire (Go) par nœud | Espace disque (Go) par nœud | Total CPU (cœur) | Mémoire (Go) | Espace disque total (Go) 


| Non HA petit | 9 | 18 | 350 | 9 | 18 | 350 


| Non HA Moyen | 13 | 26 | 350 | 13 | 26 | 350 


| HA petit | 9 | 18 | 350 | 27 | 54 | 1050 


| HA Moyen | 13 | 26 | 350 | 39 | 78 | 1050 


| HAUTE disponibilité | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Assurez-vous que le branchement à chaud pour le processeur et la RAM est activé.
* Pour le déploiement des ONTAP tools for VMware vSphere 10.3 ou 10.4, prenez un snapshot suspendu sur la machine virtuelle des outils ONTAP avant la mise à niveau.
* Activez la sauvegarde à faible RPO et assurez-vous qu'une sauvegarde est visible dans l'interface client vCenter.


.Étapes
. Télécharger les outils ONTAP pour VMware vSphere, mettez à niveau ISO vers la bibliothèque de contenu.
. Sur la page VM principale, sélectionnez *actions* > *Modifier les paramètres*
. Sélectionnez le *fichier ISO de la bibliothèque de contenu* dans la fenêtre des paramètres d'édition sous le champ *lecteur CD/DVD*.
. Sélectionnez le fichier ISO, cochez la case *Connecté* pour le champ *lecteur CD/DVD* et cliquez sur *OK*.
. À partir du serveur vCenter, ouvrez une console pour accéder aux outils ONTAP.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez *3* pour sélectionner le menu *Configuration système*.
. Entrez *7* pour sélectionner l’option *Mise à niveau*.
+
Pendant la mise à niveau, si des certificats backend de stockage intégrés manquent d'entrées de nom alternatif du sujet (SAN), vous recevrez une invite indiquant le SAN manquant.  Si vous choisissez de continuer sans valider le SAN, la mise à niveau se poursuivra, mais cela n'est pas recommandé en raison de risques de sécurité potentiels.

. Lorsque vous effectuez une mise à niveau, les actions suivantes sont automatiquement exécutées :
+
.. Le certificat de passerelle est renouvelé avec une durée de validité d'un an.  Lorsque vous supprimez l'adaptateur SRA précédent et téléchargez le nouvel adaptateur 10.5, la validité du certificat SRA passe de 10 ans à 1 an.
.. Le plug-in distant est mis à niveau
.. Les certificats ONTAP et vCenter Server sont validés et ajoutés aux outils ONTAP
.. La sauvegarde est activée




.Et la suite
Après la mise à niveau vers les ONTAP tools for VMware vSphere 10.5 :

* Surveillez les alertes système et prévoyez de renouveler le certificat de passerelle avant son expiration dans un an.
* Supprimez l'adaptateur SRA 10.4 ou 10.3 des outils ONTAP et téléchargez le fichier tar de l'adaptateur SRA 10.5.  Ensuite, analysez à nouveau les adaptateurs SRA pour mettre à jour la page Adaptateurs de réplication de stockage VMware Site Recovery.


Après la mise à niveau, vous pouvez :

* Désactivez les services à partir de l'interface utilisateur Manager
* Passez d'une configuration non HA à une configuration haute disponibilité
* Faites évoluer une petite configuration non HA vers une configuration moyenne non HA, ou vers une configuration moyenne ou grande HA.


.Informations associées
link:../migrate/migrate-to-latest-ontaptools.html["Migrer des ONTAP tools for VMware vSphere 9.xx vers 10.5"]
