---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: ONTAP tools migration, vVols migration, VMware vSphere, NFS datastores, VMFS datastores 
summary: Migrez les ONTAP tools for VMware vSphere 9.xx vers 10.6 en choisissant une méthode selon que vous utilisez ou non des datastores vVols. 
---
= Migrez des ONTAP tools for VMware vSphere 9.xx vers 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La migration des ONTAP tools for VMware vSphere 9.xx vers 10.6 nécessite des étapes différentes en fonction de vos types de datastore.

Vous pouvez migrer des ONTAP tools for VMware vSphere 9.12D1, 9.13D2 et 9.13P2 vers ONTAP tools for VMware vSphere 10.6.

Si votre configuration comporte des datastores NFS et VMFS et aucun vVols datastore, désinstallez ONTAP tools 9.xx et déployez ONTAP tools 10.6. Si votre configuration contient des datastores vVols, migrez le VASA Provider et le SRA.

Le tableau suivant décrit le processus de migration dans ces deux scénarios différents.

|===
| *Si la configuration dispose de magasins de données vVols* | *Si la configuration contient uniquement des banques de données NFS et VMFS* 


| Étapes : 1. link:../migrate/sra-vasa-migration.html["Migrer le fournisseur VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Créer des politiques de stockage de machines virtuelles"] | Étapes : 1. Supprimez les outils ONTAP 9.xx de votre environnement. Voir  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Comment supprimer OTV 9.xx de votre environnement"] dans la base de connaissances NetApp. 2. link:../deploy/quick-start.html["Déployez et configurez les ONTAP tools for VMware vSphere 10.6"] 3. link:../migrate/sra-vasa-migration.html["Mettre à jour le SRA"] 4. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Créer des politiques de stockage de machines virtuelles"] 
|===

NOTE: Après la migration des ONTAP tools for VMware vSphere 9.xx vers 10.6, les datastores vVols utilisant le protocole NVMe/FC deviennent non opérationnels car ONTAP tools 10.6 prend en charge le protocole NVMe-oF uniquement avec les datastores VMFS.



[[after-migration]]
== Après la migration

Vérifiez les points suivants :

* Les datastores sont accessibles depuis le serveur vCenter.
* Les stratégies de stockage des machines virtuelles sont mappées comme prévu.
* L'état de protection et de réplication est sain pour les banques de données configurées.

