---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: VASA Provider migration, SRA update, VMware Live Site Recovery, ONTAP tools migration, vVols migration, migration jobs, Swagger, REST API 
summary: Migrez le fournisseur VASA et mettez à jour SRA des ONTAP tools 9.x vers 10.6 pour VMware Live Site Recovery. 
---
= Migrez le fournisseur VASA et mettez à jour le SRA dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez cette tâche pour migrer le fournisseur VASA des ONTAP tools for VMware vSphere 9.xx vers 10.6 et mettre à jour l'adaptateur de réplication de stockage (SRA) sur l'appliance VMware Live Site Recovery.



[[migrate-the-vasa-provider]]
== Migrer le fournisseur VASA

.Avant de commencer
Assurez-vous que ONTAP tools for VMware vSphere 10.6 est déployé et que le serveur vCenter cible et les systèmes de stockage sont prêts pour la migration.

. Pour activer le port Derby 1527 sur l'appliance ONTAP tools for VMware vSphere existante, activez l'utilisateur root, connectez-vous à l'interface de ligne de commande via SSH et exécutez la commande suivante :
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Déployez l'OVA pour ONTAP tools for VMware vSphere 10.6.
. Ajoutez l’instance de serveur vCenter que vous souhaitez migrer vers les outils ONTAP pour VMware vSphere 10.6. Consultez link:../configure/add-vcenter.html["Ajoutez une instance de vCenter Server"] pour plus d’informations.
. Intégrez localement le système de stockage via les API du serveur vCenter pour le plug-in ONTAP tools. Consultez link:../configure/add-storage-backend.html["Ajoutez un système de stockage à l'aide de l'interface vSphere Client"] pour plus d'informations.
. Obtenez un jeton d'accès pour authentifier les requêtes API REST.  Utilisez l'exemple suivant en remplaçant les variables par des valeurs spécifiques à votre environnement.
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD", "vcenter hostname": "$MYVCENTER"}'
----
+
Copiez et enregistrez le jeton d'accès renvoyé dans la réponse.

. Exécutez l'appel API de migration suivant depuis Swagger ou Postman.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Vous pouvez accéder à Swagger via cette URL : `\https://$FQDN_IP_PORT/` , Par exemple: `\https://10.67.25.33:8443/` .

+
[]
====
*Méthode HTTP et noeud final*

Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

|===


| *Méthode HTTP* | *Chemin* 


| POST | /api/v1 
|===
*Type de traitement*

Asynchrone

*Exemple Curl*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
Corps de la demande pour une autre migration de version :

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*Exemple de sortie JSON*

Le système renvoie un objet de travail.  Enregistrez l’identifiant du travail pour l’utiliser à l’étape suivante.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====




[[check-migration-status]]
=== Vérifier l'état de la migration

. Utilisez l'URI suivant dans swagger pour vérifier l'état :
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
Utilisez la valeur 'id' renvoyée par le travail de migration de l’étape précédente. Après la fin du travail, consultez le rapport de migration dans la réponse du travail.





[[register-and-verify-the-migrated-vasa-provider]]
=== Enregistrez et vérifiez le fournisseur VASA migré

. Enregistrez le fournisseur VASA auprès des ONTAP tools for VMware vSphere. Pour les instructions, voirlink:../configure/registration-process.html["Enregistrez le fournisseur VASA"] .
. Vérifiez l'inscription du fournisseur VASA :
+
.. Dans le vSphere Client, accédez au vCenter Server.
.. Sélectionnez *Configurer* > *Storage Providers*.
.. Confirmez que le VASA Provider enregistré à l'étape précédente apparaît en ligne.


. Arrêtez les ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 (service VASA Provider) en suivant ces étapes :
+
.. Dans ONTAP tools 9.x, ouvrez la console web.
.. Connectez-vous en utilisant les `maint` identifiants.
.. Entrer `1` pour sélectionner le menu *Configuration de l'application*.
.. Entrer `5` pour mettre fin aux services VASA Provider et SRA.
.. Dans le vSphere Client, accédez au vCenter Server et sélectionnez *Configurer* > *Fournisseurs de stockage*.
.. Sélectionnez le fournisseur VASA hors ligne pour les outils ONTAP 9.x et sélectionnez *Supprimer*.
+
Après l'arrêt de l'ancien fournisseur VASA, le serveur vCenter bascule vers ONTAP tools for VMware vSphere. Toutes les banques de données et les machines virtuelles deviennent accessibles et sont servies à partir d'ONTAP tools for VMware vSphere.



. Les banques de données NFS et VMFS migrées apparaissent dans ONTAP tools for VMware vSphere 10.6 après la tâche de découverte des banques de données, qui peut prendre jusqu'à 30 minutes. Vérifiez leur visibilité sur la page de présentation.




[[run-the-patch-migration]]
=== Exécutez la migration des correctifs

. Effectuez l'appel API de migration de correctif à l'aide de Swagger ou Postman :
+
[]
====
*Méthode HTTP et noeud final*

Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

|===


| *Méthode HTTP* | *Chemin* 


| CORRECTIF | /api/v1 
|===
*Type de traitement*

Asynchrone

Utilisez l'URI suivant dans Swagger :

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Méthode HTTP et noeud final*

Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

|===


| *Méthode HTTP* | *Chemin* 


| CORRECTIF | /api/v1 
|===
*Type de traitement*

Asynchrone

Utilisez l'URI suivant dans Swagger :

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Exemple Curl*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*Exemple de sortie JSON*

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: Utilisez la valeur 'migration_id' renvoyée à l'étape 7 comme <migration_id> dans l'appel API PATCH. Le corps de la requête est vide pour une opération PATCH.

+

NOTE: UUID est l'UUID de migration renvoyé en réponse à l'API post-migration.



Après avoir exécuté l'API de migration des correctifs, toutes les machines virtuelles respectent la stratégie de stockage.



[[after-migration]]
== Après la migration

Après avoir terminé la migration et enregistré les ONTAP tools 10.6 auprès du serveur vCenter, suivez ces étapes :

* Attendez que *Discovery* soit terminé et le système actualise automatiquement les certificats sur tous les hôtes.
* Attendez avant de démarrer les opérations de la banque de données et de la machine virtuelle.  Le temps d’attente dépend du nombre d’hôtes, de banques de données et de machines virtuelles.  Si vous n’attendez pas, vous risquez de voir des échecs occasionnels.


Après la mise à niveau, si l'état de conformité de la machine virtuelle est obsolète, réappliquez la stratégie de stockage en procédant comme suit :

. Accédez au magasin de données et sélectionnez *Résumé* > *Stratégies de stockage VM*.
. Le système affiche l'état de conformité sous *Conformité à la politique de stockage VM* comme *Obsolète*.
. Sélectionnez la politique de machine virtuelle de stockage et la machine virtuelle correspondante.
. Sélectionnez *Appliquer*.
. L'état de conformité sous *Conformité à la politique de stockage VM* indique qu'il est conforme.


.Informations associées
* link:../concepts/rbac-learn-about.html["Découvrez les outils ONTAP pour VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Mettez à niveau ONTAP tools for VMware vSphere 10.x vers 10.6"]




[[update-the-storage-replication-adapter-sra]]
== Mettre à jour l'adaptateur de réplication de stockage (SRA)

.Avant de commencer
Avant de migrer le SRA, vérifiez les points suivants :

* Dans le plan de récupération, le site protégé est l'emplacement où les machines virtuelles sont actuellement en cours d'exécution, et le site de récupération est l'emplacement où les machines virtuelles seront restaurées.
* Dans l'interface de l'appliance VMware Live Site Recovery, un site apparaît à l'état protégé et l'autre site apparaît à l'état de récupération.
* Dans le plan de récupération, les boutons *NETTOYAGE* et *REPROTECTION* sont désactivés, et les boutons *TEST* et *RUN* restent activés.



NOTE: Ne lancez pas la migration si le basculement est terminé mais que la reprotection est en attente. Assurez-vous que le processus de reprotection est terminé avant de poursuivre la migration. Si un basculement de test est en cours, nettoyez le basculement de test et lancez la migration.

. Procédez comme suit pour supprimer l'adaptateur ONTAP Tools SRA pour VMware vSphere 9.xx dans VMware site Recovery :
. Accédez à la page de gestion de la configuration de VMware Live Site Recovery.
+
.. Accédez à la section *Storage Replication adapter*.
.. Dans le menu points de suspension, sélectionnez *Réinitialiser la configuration*.
.. Dans le menu points de suspension, sélectionnez *Supprimer*.


. Effectuez ces étapes sur les sites de protection et de reprise d'activité.
+
.. link:../manage/enable-services.html["Activez les outils ONTAP pour les services VMware vSphere"]
.. Configurez les outils ONTAP pour VMware vSphere 10.6 SRA à l'aide des étapes indiquées dans link:../protect/configure-on-srm-appliance.html["Configurez SRA sur l'appliance VMware Live site Recovery"].
.. Sur l'interface VMware Live Site Recovery, exécutez *Discover Arrays* et *Discover Devices*.  Confirmez que les appareils s'affichent comme avant la migration.



