---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Lors de la migration des données de stockage, les systèmes back-end sont intégrés manuellement via des API REST. Lors de la migration des données VASA Provider, les données sont exportées à partir de la base de données Derby existante et importées dans la base de données MongoDB. 
---
= Migrez le fournisseur VASA et mettez à jour le SRA dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez les étapes de cette section pour migrer le fournisseur VASA des ONTAP tools for VMware vSphere 9.xx vers les ONTAP tools for VMware vSphere 10.5 et mettre à jour l'adaptateur de réplication de stockage (SRA) sur l'appliance VMware Live Site Recovery.



== Étapes pour migrer le fournisseur VASA

. Pour activer LE PORT Derby 1527 sur les outils ONTAP existants pour VMware vSphere, activez l'utilisateur root et connectez-vous à l'interface de ligne de commande via SSH. Exécutez ensuite la commande suivante :
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Déployez les ONTAP tools for VMware vSphere 10.5.
. Ajoutez l’instance vCenter Server que vous souhaitez migrer vers les ONTAP tools for VMware vSphere 10.5. Consultez link:../configure/add-vcenter.html["Ajoutez une instance de vCenter Server"] pour plus d'informations.
. Intégrez localement le système de stockage à partir des API du serveur vCenter pour le plug-in ONTAP Tools. Voirlink:../configure/add-storage-backend.html["Ajoutez un système de stockage dorsal à l'aide de l'interface client vSphere."] pour plus d'informations.
. Obtenez un jeton d'accès pour authentifier les requêtes API REST.  Utilisez l'exemple suivant en remplaçant les variables par des valeurs spécifiques à votre environnement.
+
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
+
Copiez et enregistrez le jeton d'accès renvoyé dans la réponse.

. Exécutez l'API suivante depuis swagger ou dans Postman pour effectuer la migration.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Vous pouvez accéder à Swagger via cette URL : `\https://$FQDN_IP_PORT/` , Par exemple: `\https://10.67.25.33:8443/` .

+
[]
====
*Méthode HTTP et noeud final*

Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

|===


| *Méthode HTTP* | *Chemin* 


| POST | /api/v1 
|===
*Type de traitement*

Asynchrone

*Exemple Curl*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
Corps de la demande pour une autre migration de version :

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*Exemple de sortie JSON*

Le système renvoie un objet de travail.  Enregistrez l’identifiant du travail pour l’utiliser à l’étape suivante.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Utilisez l'URI suivant dans swagger pour vérifier l'état :
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
Une fois la tâche terminée, examinez le rapport de migration dans la réponse à la tâche.

. Ajoutez les ONTAP tools for VMware vSphere au serveur vCenter.
. Enregistrez le fournisseur VASA auprès des ONTAP tools for VMware vSphere. Pour les instructions, voirlink:../configure/registration-process.html["Enregistrez le fournisseur VASA"] .
. Après l'enregistrement, vérifiez le nom du fournisseur VASA et son statut dans le client vSphere sous *Fournisseurs de stockage*.  Le fournisseur VASA devrait apparaître en ligne, confirmant ainsi la réussite de l'inscription.
. link:../manage/enable-services.html["Activez VASA Provider"]service sur les ONTAP tools for VMware vSphere 10.5.
. Arrêtez les ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 (service VASA Provider) en suivant ces étapes :
+
.. Dans ONTAP tools 9.x, ouvrez la console web.
.. Accéder à la console de maintenance.
.. Entrer `1` pour sélectionner le menu *Configuration de l'application*.
.. Entrer `5` pour mettre fin aux services VASA Provider et SRA.
.. Dans le client vSphere, accédez à *Inventaire* > *Fournisseurs de stockage*.
.. Sélectionnez le fournisseur VASA ONTAP tools 9.x dans le backend de stockage et cliquez sur *Supprimer*.
+
Après l'arrêt de l'ancien fournisseur VASA, vCenter Server bascule vers les ONTAP tools for VMware vSphere. Tous les datastores et machines virtuelles deviennent accessibles et sont gérés par les ONTAP tools for VMware vSphere.



. Les banques de données NFS et VMFS migrées apparaissent dans les ONTAP tools for VMware vSphere 10.5 après la tâche de découverte de banque de données, ce qui peut prendre jusqu'à 30 minutes.  Vérifiez leur visibilité sur la page d'aperçu.
. Effectuez la migration des correctifs à l'aide de l'API suivante dans swagger ou dans Postman :
+
[]
====
*Méthode HTTP et noeud final*

Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

|===


| *Méthode HTTP* | *Chemin* 


| CORRECTIF | /api/v1 
|===
*Type de traitement*

Asynchrone

Utilisez l'URI suivant dans Swagger :

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Exemple Curl*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*Exemple de sortie JSON*

Un objet de travail est renvoyé. Vous devez enregistrer l'identifiant du travail pour l'utiliser à l'étape suivante.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
Le corps de la demande est vide pour l'opération de patch.




NOTE: UUID est l'UUID de migration renvoyé en réponse à l'API post-migration.

Après avoir exécuté l'API de migration des correctifs, toutes les machines virtuelles respectent la stratégie de stockage.

.Et la suite
Après avoir terminé la migration et enregistré les outils ONTAP 10.5 sur vCenter Server, suivez ces étapes :

* Attendez que *Discovery* soit terminé et le système actualise automatiquement les certificats sur tous les hôtes.
* Attendez avant de démarrer les opérations de la banque de données et de la machine virtuelle.  Le temps d’attente dépend du nombre d’hôtes, de banques de données et de machines virtuelles.  Si vous n’attendez pas, vous risquez de voir des échecs occasionnels.


Après la mise à niveau, si l'état de conformité de la machine virtuelle est obsolète, réappliquez la stratégie de stockage en procédant comme suit :

. Accédez au magasin de données et sélectionnez *Résumé* > *Stratégies de stockage VM*.
+
Le système affiche l'état de conformité sous *Conformité à la politique de stockage VM* comme *Obsolète*.

. Sélectionnez la politique de machine virtuelle de stockage et la machine virtuelle correspondante.
. Sélectionnez *Appliquer*.
+
L'état de conformité sous *Conformité à la politique de stockage VM* indique qu'il est conforme.



.Informations associées
* link:../concepts/rbac-learn-about.html["Découvrez les outils ONTAP pour VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Mise à niveau des ONTAP tools for VMware vSphere 10.x vers 10.5"]




== Étapes pour mettre à jour l'adaptateur de réplication de stockage (SRA)

.Avant de commencer
Dans le plan de récupération, le site protégé désigne l'emplacement où les machines virtuelles sont actuellement exécutées, tandis que le site de récupération désigne l'emplacement où elles seront restaurées. L'interface du dispositif VMware Live Site Recovery affiche l'état du plan de récupération avec des détails sur les sites protégés et de récupération.  Dans le plan de récupération, les boutons NETTOYER et REPROTÉGER sont désactivés, tandis que les boutons TESTER et EXÉCUTER restent activés. Cela indique que le site est prêt pour la récupération des données. Avant de migrer le SRA, vérifiez qu'un site est en état protégé et l'autre en état de récupération.


NOTE: Ne commencez pas la migration si le basculement a été effectué mais que la reprotection est en attente.  Assurez-vous que le processus de reprotection est terminé avant de procéder à la migration.  Si un basculement de test est en cours, nettoyez le basculement de test et démarrez la migration.

. Procédez comme suit pour supprimer l'adaptateur ONTAP Tools SRA pour VMware vSphere 9.xx dans VMware site Recovery :
+
.. Accédez à la page de gestion de la configuration de VMware Live site Recovery
.. Accédez à la section *Storage Replication adapter*.
.. Dans le menu points de suspension, sélectionnez *Réinitialiser la configuration*.
.. Dans le menu points de suspension, sélectionnez *Supprimer*.


. Effectuez ces étapes sur les sites de protection et de reprise d'activité.
+
.. link:../manage/enable-services.html["Activez les outils ONTAP pour les services VMware vSphere"]
.. Configurez les ONTAP tools for VMware vSphere 10.5 SRA en suivant les étapes décrites danslink:../protect/configure-on-srm-appliance.html["Configurez SRA sur l'appliance VMware Live site Recovery"] .
.. Sur l'interface VMware Live Site Recovery, exécutez *Discover Arrays* et *Discover Devices*.  Confirmez que les appareils s'affichent comme avant la migration.



