---
permalink: deploy/deployment-error-codes.html 
sidebar: sidebar 
keywords: upgrade 
summary: 'Cette page présente les codes d"erreur relatifs aux opérations de déploiement, de redémarrage et de restauration des outils ONTAP pour le système VMware vSphere.' 
---
= Résoudre les erreurs de déploiement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous rencontrez des problèmes de déploiement, consultez les journaux et les codes d’erreur pour diagnostiquer et résoudre les problèmes.  À partir des ONTAP tools for VMware vSphere 10.5, les groupes de journaux collectés à partir des pods incluent les journaux de MongoDB, RabbitMQ et Vault, ainsi que l'état et les descriptions de tous les pods.  Ils sont fournis en plus des journaux de service des outils ONTAP existants, améliorant ainsi la prise en charge et le dépannage.



== Collectez les fichiers journaux

Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir des options disponibles dans l'interface utilisateur de ONTAP Tools Manager. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.


NOTE: La génération de journaux à partir du Gestionnaire d'outils ONTAP inclut tous les journaux de toutes les instances de vCenter Server. La génération des journaux à partir de l'interface utilisateur du client vCenter est étendue pour le serveur vCenter sélectionné.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *Log Bundles* dans la barre latérale.
+
Cette opération peut prendre plusieurs minutes.

. Sélectionnez *générer* pour générer les fichiers journaux.
. Saisissez le libellé du lot de journaux et sélectionnez *Generate*.
+
Téléchargez le fichier tar.gz et envoyez-le au support technique.



Pour générer un bundle de journaux à l'aide de l'interface utilisateur du client vCenter, procédez comme suit :

.Étapes
. Connectez-vous au client vSphere.
. Depuis la page d'accueil de vSphere client, accédez à *support* > *Log bundle* > *Generate*.
. Indiquez l'étiquette du fichier journal et générez-le. L'option de téléchargement s'affiche une fois les fichiers générés. Le téléchargement peut prendre un certain temps.



NOTE: L'ensemble de journaux généré remplace l'ensemble de journaux généré au cours des 3 derniers jours ou des 72 dernières heures.



== Codes d'erreur de déploiement

Des codes d'erreur peuvent s'afficher lors du déploiement, du redémarrage et des opérations de restauration des outils ONTAP pour VMware vSphere.
Les codes d'erreur sont composés de cinq chiffres, les deux premiers chiffres représentant le script qui a rencontré le problème, et les trois derniers chiffres représentent le flux de travail spécifique de ce script.

Tous les journaux d'erreurs sont enregistrés dans le fichier ansible-perl-errors.log sous le répertoire /var/log pour faciliter le suivi et la résolution des problèmes.  Ce fichier journal contient le code d'erreur et la tâche Ansible ayant échoué.


NOTE: Les codes d'erreur fournis sur cette page sont fournis à titre de référence uniquement. Contactez l'équipe d'assistance si l'erreur persiste ou si aucune résolution n'est mentionnée.

Le tableau suivant répertorie les codes d'erreur et les noms de fichier correspondants.

|===


| *Code d'erreur* | *Nom du script* 


| 00 | firstboot-network-config.pl, mode deploy 


| 01 | firstboot-network-config.pl, mise à niveau du mode 


| 02 | firstboot-inputs-validation.pl 


| 03 | firstboot-deploy-otv-ng.pl, déploiement, haute disponibilité 


| 04 | firstboot-deploy-otv-ng.pl, déploiement, non HA 


| 05 | firstboot-deploy-otv-ng.pl, redémarrer 


| 06 | firstboot-deploy-otv-ng.pl, mise à niveau, haute disponibilité 


| 07 | firstboot-deploy-otv-ng.pl, mise à niveau, non HA 


| 08 | firstboot-otv-recovery.pl 


| 09 | post-deploy-upgrade.pl 
|===
Les trois derniers chiffres du code d'erreur indiquent l'erreur de flux de travail spécifique dans le script :

|===


| *Code d'erreur de déploiement* | *Workflow* | *Résolution* 


| 049 | Pour le réseau et la validation, le script perl les attribuera également sous peu | - 


| 050 | Échec de la génération de la clé SSH | Redémarrez la machine virtuelle (VM) principale. 


| 053 | Echec de l'installation de RKE2 | Exécutez les opérations suivantes et redémarrez la machine virtuelle principale ou redéployez :
Sudo rke2-killall.sh (toutes les VM)
Sudo rke2-uninstall.sh (toutes les VM). 


| 054 | Échec du paramétrage kubeconfig | Redéploiement 


| 055 | Échec du déploiement du registre | Si le pod de registre est présent, attendez que le pod soit prêt, puis redémarrez la machine virtuelle principale ou redéployez-la. 


| 059 | Échec du déploiement KubeVip | Vérifiez que l'adresse IP virtuelle du plan de contrôle Kubernetes et l'adresse IP des outils ONTAP fournies lors du déploiement appartiennent au même VLAN et sont des adresses IP libres. Redémarrez si tous les points précédents sont corrects. Sinon, redéployer. 


| 060 | Le déploiement de l'opérateur a échoué | Redémarrer 


| 061 | Le déploiement des services a échoué | Effectuez des opérations de débogage Kubernetes de base comme GET pods, GET RS, GET svc, etc. Dans l'espace de noms du système ntv pour plus de détails et des journaux d'erreurs dans /var/log/ansible-perl-errors.log et /var/log/ansible-run.log et redéployez. 


| 062 | Le déploiement des services d'outils ONTAP a échoué | Reportez-vous aux journaux d'erreurs à l'adresse /var/log/ansible-perl-errors.log pour plus de détails et redéployez. 


| 065 | L'URL de la page swagger est inaccessible | Redéploiement 


| 066 | Les étapes de post-déploiement du certificat de passerelle ont échoué | Procédez comme suit pour récupérer/terminer la mise à niveau : * Activer le shell de diagnostic. * Exécutez la commande 'sudo perl /home/maint/scripts/post-deploy-upgrade.pl --postDeploy'. * Consultez les journaux dans /var/log/post-deploy-upgrade.log. 


| 088 | La configuration de la rotation du journal pour journald a échoué | Vérifiez les paramètres réseau de la machine virtuelle compatibles avec l'hôte sur lequel la machine virtuelle est hébergée. Vous pouvez essayer de migrer vers un autre hôte et redémarrer la machine virtuelle. 


| 089 | La modification de la propriété du fichier de configuration de rotation du journal de synthèse a échoué | Redémarrez la machine virtuelle principale. 


| 096 | Installer le provisionneur de stockage dynamique | - 


| 108 | Echec du script d'amorçage | - 
|===
|===


| *Redémarrez le code d'erreur* | *Workflow* | *Résolution* 


| 067 | Délai d'attente du serveur rke2 dépassé. | - 


| 101 | Echec de la réinitialisation du mot de passe utilisateur maint/Console. | - 


| 102 | Échec de la suppression du fichier de mot de passe lors de la réinitialisation du mot de passe utilisateur maint/Console. | - 


| 103 | Échec de la mise à jour du nouveau mot de passe utilisateur maint/Console dans le coffre-fort. | - 


| 088 | La configuration de la rotation du journal pour journald a échoué. | Vérifiez les paramètres réseau de la machine virtuelle compatibles avec l'hôte sur lequel la machine virtuelle est hébergée. Vous pouvez essayer de migrer vers un autre hôte et redémarrer la machine virtuelle. 


| 089 | La modification de la propriété du fichier de configuration de rotation du journal de synthèse a échoué. | Redémarrez l'unité VM. 
|===