---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez configurer la haute disponibilité dans des configurations de petite, moyenne ou grande taille. 
---
= Déployez une configuration haute disponibilité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer la haute disponibilité de trois nœuds dans des configurations de petite, moyenne ou grande taille. Le déploiement HAUTE DISPONIBILITÉ utilise Trident pour stocker les données de services.

* Petit HA trois nœuds contiennent 8 processeurs et 16 Go de RAM par nœud.
* Moyenne disponibilité trois nœuds contiennent 12 processeurs et 24 Go de RAM par nœud.
* Grand système haute disponibilité, trois nœuds contiennent 16 processeurs et 32 Go de RAM par nœud.


*Avant de commencer*

Cette tâche fournit des instructions sur l'installation de trois nœuds HA dans des configurations de petite, moyenne ou haute disponibilité.


NOTE: La création de la bibliothèque de contenu est une étape obligatoire pour le déploiement de la configuration à trois nœuds haute disponibilité. Reportez-vous à link:../deploy/download-ontap-tools.html["Créer une bibliothèque de contenu"]la section pour connaître la procédure. Pour plus d'informations, consultez https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Création et utilisation de la bibliothèque de contenu"] le blog.

Assurez-vous d'avoir importé votre OVA dans votre bibliothèque de contenu. Gardez à portée de main le nom de la bibliothèque de contenu et le nom de l'élément de bibliothèque que vous avez donné à votre élément OVA.


NOTE: Avant de procéder au déploiement, définissez le gestionnaire de ressources distribuées (DRS) du cluster sur l'inventaire sur « conservateur » lors de l'installation des outils ONTAP. Cela permet de s'assurer que les machines virtuelles ne migrent pas pendant l'installation.

*Étapes*

. Connectez-vous au serveur vSphere.
. Accédez au pool de ressources que vous avez créé ou au cluster ou à l'hôte sur lequel vous souhaitez déployer l'OVA.
. Cliquez avec le bouton droit de la souris sur l'emplacement requis et sélectionnez *déployer le modèle OVF...*.
+

NOTE: Ne déployez pas les outils ONTAP pour la machine virtuelle VMware vSphere sur un datastore vVols qu'il gère.

. Sélectionnez le fichier OVA via l'URL du fichier _.ova_ ou naviguez jusqu'au dossier dans lequel le fichier _.ova_ est enregistré, puis cliquez sur *Suivant*.
. Pour déployer les outils ONTAP pour VMware vSphere à partir de la bibliothèque de contenu :
+
.. Accédez à votre bibliothèque de contenu et cliquez sur l'élément de bibliothèque que vous souhaitez déployer.
.. Cliquez sur *actions* > *Nouveau VM à partir de ce modèle*


. Sélectionnez une ressource ordinateur et cliquez sur *Suivant*.
. Passez en revue les détails du modèle et cliquez sur *Suivant*.
. Lisez et acceptez le contrat de licence et cliquez sur *Suivant*.
. Sélectionnez la configuration de déploiement et cliquez sur *Suivant*.
. Sélectionnez le stockage pour la configuration et les fichiers disque, puis cliquez sur *Suivant*.
. Sélectionnez le réseau de destination pour chaque réseau source et cliquez sur *Suivant*.
. Dans la fenêtre *Personnaliser le modèle*, remplissez les champs requis et cliquez sur *Suivant*.
+
** Lorsque l'étendue de SVM est activée, vous devez avoir déjà activé la prise en charge des SVM avec l'adresse IP de gestion.
** Les informations fournies ici sont validées pour les modèles corrects lors du processus d'installation. En cas de divergence, un message d'erreur s'affiche sur la console Web et vous êtes invité à corriger toute information incorrecte fournie.
** Les noms d'hôte doivent être composés de lettres majuscules (A-Z), de lettres minuscules (a-z), de chiffres (0-9) ou de caractères spéciaux de tiret (-). Si vous souhaitez configurer la double pile, spécifiez le nom d'hôte mappé sur l'adresse IPv6.


. Consultez les détails dans la fenêtre *prêt à terminer*, sélectionnez *Terminer*.
+
Au fur et à mesure de la création de la tâche de déploiement, la progression s'affiche dans la barre des tâches vSphere.

. Mettez le serveur virtuel sous tension une fois la tâche terminée.
+
L'installation commence. Vous pouvez suivre la progression de l'installation dans la console Web de la machine virtuelle. Dans le cadre de l'installation, les configurations de nœuds sont validées. Les entrées fournies sous différentes sections sous le modèle Personnaliser du formulaire OVF sont validées. En cas de divergence, une boîte de dialogue vous invite à prendre des mesures correctives.

. Apportez les modifications nécessaires dans l'invite de la boîte de dialogue. Utilisez le bouton Tab pour naviguer dans le panneau et sélectionnez *OK*.
+
Les valeurs fournies sont à nouveau validées. Les outils ONTAP pour VMware vSphere vous permettent de corriger toute valeur non valide en trois tentatives. Si vous ne parvenez pas à corriger les problèmes après trois tentatives, l'installation du produit s'arrête et il vous est conseillé d'essayer l'installation sur une nouvelle machine virtuelle.



Une fois l'installation terminée, la console Web affiche l'état des outils ONTAP pour VMware vSphere.
