---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez configurer un seul nœud non HA dans des configurations de petite ou moyenne taille. 
---
= Déployez une configuration à un seul nœud non HA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déployer une configuration à un seul nœud non HA dans une configuration de petite ou moyenne taille.

* La petite configuration non HA contient 8 processeurs et 16 Go de RAM.
* La configuration moyenne non HA contient 12 processeurs et 24 Go de RAM.


*Avant de commencer*

Assurez-vous que la route réseau est présente. Le réseau de données de stockage doit être accessible depuis le réseau de gestion des machines virtuelles. Par exemple, connectez-vous à ONTAP > exécutez la commande _network route create -vserver <SVM> -destination 0.0.0.0/0 -Gateway <gateway_ip>_

*Étapes*

. Connectez-vous au serveur vSphere.
. Accédez au pool de ressources que vous avez créé ou au cluster ou à l'hôte sur lequel vous souhaitez déployer l'OVA.
. Cliquez avec le bouton droit de la souris sur l'emplacement requis et sélectionnez *déployer le modèle OVF...*.
+

NOTE: Ne déployez pas les outils ONTAP pour la machine virtuelle VMware vSphere sur un datastore vVols qu'il gère.

. Sélectionnez le fichier OVA via l'URL du fichier _.ova_ ou naviguez jusqu'au dossier dans lequel le fichier _.ova_ est enregistré, puis cliquez sur *Suivant*.
. Sélectionnez une ressource ordinateur et cliquez sur *Suivant*.
. Passez en revue les détails du modèle et cliquez sur *Suivant*.
. Lisez et acceptez le contrat de licence.
. Sélectionnez la configuration de déploiement et cliquez sur *Suivant*.
+
Les options de déploiement avancé utilisent Trident en tant que provisionneur de stockage dynamique pour ONTAP pour créer des volumes. Le déploiement simplifié utilise le stockage local pour créer des volumes.

. Sélectionnez le stockage pour la configuration et les fichiers disque, puis cliquez sur *Suivant*.
. Sélectionnez le réseau de destination pour chaque réseau source et cliquez sur *Suivant*.
. Dans le *Personnaliser le modèle*, entrez les détails requis et cliquez sur *Suivant*
+
** Lorsque l'étendue de SVM est activée, vous devez avoir déjà activé la prise en charge des SVM avec l'adresse IP de gestion.
** Les informations fournies ici sont validées pour les modèles corrects lors du processus d'installation. En cas de divergence, un message d'erreur s'affiche sur la console Web et vous êtes invité à corriger toute information incorrecte fournie.
** Les noms d'hôte doivent être composés de lettres majuscules (A-Z), de lettres minuscules (a-z), de chiffres (0-9) ou de caractères spéciaux de tiret (-). Si vous souhaitez configurer la double pile, spécifiez le nom d'hôte mappé sur l'adresse IPv6.


. Consultez les détails dans la fenêtre *prêt à terminer*, sélectionnez *Terminer*.
+
Au fur et à mesure de la création de la tâche de déploiement, la progression s'affiche dans la barre des tâches vSphere.

. Mettez le serveur virtuel sous tension une fois la tâche terminée.
+
L'installation commence. Vous pouvez suivre la progression de l'installation dans la console Web de la machine virtuelle. Dans le cadre de l'installation, les configurations de nœuds sont validées. Les entrées fournies sous différentes sections sous le modèle Personnaliser du formulaire OVF sont validées. En cas de divergence, une boîte de dialogue vous invite à prendre des mesures correctives.

. Apportez les modifications nécessaires dans l'invite de la boîte de dialogue. Utilisez le bouton Tab pour naviguer dans le panneau et sélectionnez *OK*.
+
Les valeurs fournies sont à nouveau validées. Les outils ONTAP pour VMware vSphere vous permettent de corriger toute valeur non valide en trois tentatives. Si vous ne parvenez pas à corriger les problèmes après trois tentatives, l'installation du produit s'arrête et il vous est conseillé d'essayer l'installation sur une nouvelle machine virtuelle.



Une fois l'installation terminée, la console Web affiche l'état des outils ONTAP pour VMware vSphere.
