---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP pour l"appliance VMware vSphere sont toujours déployés en tant que nœud unique de petite taille avec des services de base pour prendre en charge les datastores NFS/VMFS.' 
---
= Déployez les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour l'appliance VMware vSphere sont toujours déployés en tant que nœud unique de petite taille avec des services de base pour prendre en charge les datastores NFS/VMFS.

*Avant de commencer*

Une bibliothèque de contenu dans VMware est un objet conteneur qui stocke les modèles de machine virtuelle, les modèles vApp et d'autres types de fichiers. Le déploiement avec la bibliothèque de contenu vous offre une expérience transparente car il ne dépend pas de la connectivité réseau.


NOTE: Vous devez stocker la bibliothèque de contenu sur un datastore partagé, de sorte que tous les hôtes d'un cluster puissent y accéder. Vous devez créer une bibliothèque de contenu pour stocker l'OVA avant de modifier les paramètres de l'appliance en configuration haute disponibilité. Une fois le téléchargement terminé, le modèle de bibliothèque de contenu ne doit pas être supprimé après le déploiement.


NOTE: Pour activer le déploiement de la haute disponibilité ultérieurement, la machine virtuelle qui héberge les outils ONTAP ne doit pas être déployée directement sur un hôte ESXi. Il doit plutôt être déployé sur un cluster ou un pool de ressources.

Si vous ne disposez pas encore d'une bibliothèque de contenu appropriée, créez-en une en procédant comme suit :

*Créer une bibliothèque de contenu* si vous avez seulement l'intention d'utiliser un déploiement à un seul nœud, vous n'avez pas besoin de créer une bibliothèque de contenu.

. Téléchargez le `.zip` fichier contenant les binaires (_.ova_) et les certificats signés pour les outils ONTAP pour VMware vSphere à partir du https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de support NetApp"^].
. Connectez-vous au client vSphere à l'aide de `\https://<vcenterip>/<ui>`
. Sélectionnez les ellipses horizontales en regard de client vSphere et sélectionnez *Bibliothèque de contenu*.
. Sélectionnez *Créer* à droite de la page.
. Indiquez un nom pour la bibliothèque et créez la bibliothèque de contenu.
. Accédez à la bibliothèque de contenu que vous avez créée.
. Sélectionnez *actions* à droite de la page et sélectionnez *Importer élément* et importez le fichier OVA.



NOTE: Pour plus d'informations, consultez https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Création et utilisation de la bibliothèque de contenu"] le blog.

Assurez-vous d'avoir importé l'OVA dans votre bibliothèque de contenu.


NOTE: Avant de procéder au déploiement, définissez le gestionnaire de ressources distribuées (DRS) du cluster sur l'inventaire sur « conservateur » lors de l'installation des outils ONTAP. Cela permet de s'assurer que les machines virtuelles ne migrent pas pendant l'installation.

.Étapes
. Téléchargez le `.zip` fichier contenant les binaires (_.ova_) et les certificats signés pour les outils ONTAP pour VMware vSphere à partir du https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de support NetApp"^]. Si vous avez importé l'OVA dans la bibliothèque de contenu, vous pouvez ignorer cette étape et passer à l'étape suivante car vous pouvez déployer directement depuis la bibliothèque de contenu.
. Connectez-vous au serveur vSphere.
. Accédez au pool de ressources que vous avez créé ou au cluster ou à l'hôte sur lequel vous souhaitez déployer l'OVA.
. Cliquez avec le bouton droit de la souris sur l'emplacement requis et sélectionnez *déployer le modèle OVF...*.
+

NOTE: Ne stockez jamais d'outils ONTAP pour les machines virtuelles VMware vSphere sur des datastores vVols qu'ils gèrent.

. Sélectionnez le fichier OVA via l'URL du fichier _.ova_ ou naviguez jusqu'au dossier dans lequel le fichier _.ova_ est enregistré, puis sélectionnez *Suivant*.
. Pour déployer les outils ONTAP pour VMware vSphere à partir de la bibliothèque de contenu :
+
.. Accédez à votre bibliothèque de contenu et sélectionnez l'élément de bibliothèque que vous souhaitez déployer.
.. Sélectionnez *actions* > *Nouveau VM à partir de ce modèle*


. Dans la fenêtre *sélectionnez un nom et un dossier* pour la machine virtuelle, entrez le nom de la machine virtuelle et sélectionnez l'emplacement de la machine virtuelle. Si vous cochez la case *Personnaliser le matériel de cette machine virtuelle*, une étape appelée *Personnaliser le matériel* est activée avant d'atteindre la fenêtre *prêt à terminer*.
. Sélectionnez une ressource d'ordinateur et sélectionnez *Suivant*. Vous pouvez cocher la case *mettre automatiquement sous tension la machine virtuelle déployée*.
. Passez en revue les détails du modèle et sélectionnez *Suivant*.
. Lisez et acceptez le contrat de licence et sélectionnez *Suivant*.
. Sélectionnez le stockage pour la configuration et les fichiers disque, puis sélectionnez *Suivant*.
. Sélectionnez le réseau de destination pour chaque réseau source et sélectionnez *Suivant*.
. Dans la fenêtre *Personnaliser le modèle*, remplissez les champs requis et sélectionnez *Suivant*.
+
** Les informations fournies ici sont validées pour les modèles corrects lors du processus d'installation. En cas de divergence, un message d'erreur s'affiche sur la console Web et vous êtes invité à corriger toute information incorrecte fournie.
** Les noms d'hôte doivent être composés de lettres majuscules (A-Z), de lettres minuscules (a-z), de chiffres (0-9) ou de caractères spéciaux de tiret (-). Si vous souhaitez configurer la double pile, spécifiez le nom d'hôte mappé sur l'adresse IPv6.
+

NOTE: Le PROTOCOLE IPv6 pur n'est pas pris en charge. Le mode mixte est pris en charge avec les VLAN ayant des adresses IPv6 et IPv4.



. Dans la fenêtre *Personnaliser le matériel*, vous devez activer l'ajout à chaud de CPU et la connexion à chaud de mémoire.
. Consultez les détails dans la fenêtre *prêt à terminer*, sélectionnez *Terminer*.
+
Au fur et à mesure de la création de la tâche de déploiement, la progression s'affiche dans la barre des tâches vSphere.

. Mettez le serveur virtuel sous tension une fois la tâche terminée.
+

NOTE: Avant de mettre l'ordinateur sous tension, assurez-vous que les plug-ins actifs sont activés pour le processeur et la mémoire.



Vous pouvez suivre la progression de l'installation au sein de la console Web de la machine virtuelle.

En cas de divergence dans les valeurs saisies dans le formulaire OVF, une boîte de dialogue vous invite à prendre des mesures correctives. Effectuez les modifications nécessaires dans la boîte de dialogue, en utilisant le bouton Tab pour naviguer et sélectionner "OK". Vous avez trois tentatives pour corriger tout problème. Si les problèmes persistent après trois tentatives, le processus d'installation s'arrête et il est recommandé de réessayer l'installation sur une nouvelle machine virtuelle.
