---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître les besoins en espace requis pour le package de déploiement et la configuration système hôte de base requise. 
---
= Exigences et limites de configuration des outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître les besoins en espace requis pour le package de déploiement et la configuration système hôte de base requise.

Vous pouvez utiliser les outils ONTAP pour VMware vSphere avec VMware vCenter Server Virtual Appliance (vCSA). Vous devez déployer les outils ONTAP pour VMware vSphere sur un client vSphere pris en charge qui inclut le système ESXi.



== Configuration minimale requise

* *Espace requis pour le package d'installation par nœud*
+
** 15 Go pour les installations à provisionnement fin
** 348 Go pour les installations à provisionnement lourd


* *Dimensionnement requis du système hôte* Le tableau ci-dessous indique la mémoire recommandée pour chaque taille de déploiement. Pour les déploiements haute disponibilité (HA), vous avez besoin de trois fois la taille de l'appliance indiquée.


|===


| *Type de déploiement* | *CPU par nœud* | *Mémoire (Go) par nœud* | *Espace disque (Go) thick provisionné par nœud* 


| Petit | 9 | 18 | 350 


| Moyen | 13 | 26 | 350 


| REMARQUE importante : le déploiement de grande envergure concerne uniquement la configuration haute disponibilité. | 17 | 34 | 350 
|===

NOTE: Lorsque la sauvegarde est activée, chaque cluster d'outils ONTAP a besoin d'un espace supplémentaire de 50 Go sur le datastore où les machines virtuelles sont déployées. Par conséquent, une configuration non HA requiert 400 Go et la haute disponibilité requiert au total 1100 Go d'espace.



== Exigences minimales en matière de stockage et d'applications

|===
| Stockage, hôte et applications | Exigences de version 


| ONTAP | 9.15.1, 9.16.0, 9.16.1, 9.17.0 et 9.17.1 


| Les outils ONTAP prennent en charge les hôtes ESXi | à partir de 7.0.3 


| Les outils ONTAP prennent en charge vCenter Server | 7.0U3 à partir de 


| Vasa Provider | 3.0 


| Application OVA | 10,5 


| Hôte VMware ESXi pour déployer la machine virtuelle des outils ONTAP | 7.0U3 et 8.0U3 


| VCenter Server pour déployer la machine virtuelle des outils ONTAP | 7.0 et 8.0 
|===

NOTE: À partir des outils ONTAP pour VMware vSphere 10.4, le matériel de la machine virtuelle passe de la version 10 à la version 17.

La matrice d'interopérabilité (IMT) contient les dernières informations sur les versions prises en charge de ONTAP, de vCenter Server, d'hôtes ESXi et d'applications de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité"^]



== Configuration requise pour les ports

Le tableau suivant présente les ports réseau utilisés par NetApp et leurs fonctions. Il existe trois types de ports différents :

* Ports externes : ces ports sont accessibles depuis l’extérieur du cluster ou du nœud Kubernetes. Ils permettent aux services de communiquer avec des réseaux ou des utilisateurs externes, permettant ainsi l'intégration avec des systèmes situés en dehors de l'environnement du cluster.
* Ports inter-nœuds : ces ports permettent la communication entre les nœuds au sein du cluster Kubernetes. Ils sont nécessaires pour les tâches en cluster telles que le partage de données et le travail collaboratif. Pour les déploiements à nœud unique, les ports inter-nœuds sont utilisés uniquement au sein du nœud et n'ont pas besoin d'accès externe. Les ports inter-nœuds peuvent accepter le trafic provenant de l'extérieur du cluster. Bloquez l'accès Internet aux ports inter-nœuds à l'aide de règles de pare-feu.
* Ports internes : ces ports communiquent au sein du cluster Kubernetes à l’aide d’adresses ClusterIP. Elles ne sont pas exposées de l'extérieur et n'ont pas besoin d'être ajoutées aux règles du pare-feu.



NOTE: Assurez-vous que tous les nœuds des outils ONTAP résident sur le même sous-réseau pour maintenir une communication ininterrompue entre eux.

Cliquez pour développer ou réduire le tableau des exigences relatives aux ports.

[%collapsible]
====
|===
| *Nom du service/composant* | *Port* | *Protocole* | *Type de port* | *Description* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Externe | Port de transit pour les communications entrantes du service fournisseur VASA. Le certificat auto-signé du fournisseur VASA et le certificat CA personnalisé sont hébergés sur ce port. 


| SSH | 22 | TCP | Externe | Secure Shell pour la connexion à un serveur distant et l'exécution de commandes. 


| serveur rke2 | 9345 | TCP | Inter-nœud | API de supervision RKE2 (Restriction aux réseaux de confiance). 


| kube-apiserver | 6443 | TCP | Inter-nœud | Port du serveur API Kubernetes (à limiter aux réseaux de confiance). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nœud | Utilisé pour la communication RPC entre les services. 


| coredns (DNS) | 53 | TCP/UDP | Inter-nœud | Service DNS (Domain Name System) pour la résolution de noms au sein du cluster. 


| NTP | 123 | UDP | Inter-nœud | Protocole NTP (Network Time Protocol) pour la synchronisation de l'heure. 


| etcd | 2379, 2380, 2381 | TCP | Inter-nœud | Système de stockage clé-valeur pour les données de cluster. 


| kube-vip | 2112 | TCP | Inter-nœud | Port du serveur API Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nœud | Composant Kubernetes 


| contrôleur kube | 10257 | TCP | Inter-nœud | Composant Kubernetes 


| contrôleur cloud | 10258 | TCP | Inter-nœud | Composant Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nœud | Composant Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nœud | Composant Kubernetes 


| nœud calico | 9091, 9099 | TCP | Inter-nœud | Composant réseau Calico. 


| conteneur | 10010 | TCP | Inter-nœud | Service démon du conteneur. 


| VXLAN (Flannel) | 8472 | UDP | Inter-nœud | Réseau superposé pour la communication entre les pods. 
|===

NOTE: Pour les déploiements HA, assurez-vous que le port UDP 8472 est ouvert entre tous les nœuds. Ce port permet la communication entre les pods au sein des nœuds ; son blocage interrompra la mise en réseau entre les nœuds.

====


== Limites de configuration pour déployer ONTAP tools for VMware vSphere pour les datastores vVols

Vous pouvez utiliser le tableau suivant comme guide pour configurer les ONTAP tools for VMware vSphere.

|===


| *Déploiement* | *Type* | *Nombre de vVols* | *Nombre d'hôtes* 


| Non HA | Petit (S) | jusqu'à 12K | 32 


| Non HA | Moyen (M) | jusqu'à 24K | 64 


| Haute-disponibilité | Petit (S) | jusqu'à 24K | 64 


| Haute-disponibilité | Moyen (M) | jusqu'à 50k | 128 


| Haute-disponibilité | Grand (L) | jusqu'à 100k | 256 
|===

NOTE: Le nombre d'hôtes indiqué dans le tableau représente le total combiné pour tous les vCenters connectés.



== Limites de configuration pour le déploiement des ONTAP tools for VMware vSphere pour les datastores VMFS et NFS

Les limites de configuration indiquées dans cette section sont validées et prises en charge par NetApp. Les limites réelles peuvent varier en fonction de votre environnement et de votre charge de travail. Le dépassement de ces limites peut impacter les performances ou la prise en charge et est déconseillé. Tenez compte des éléments suivants lors de l’examen du tableau :

* La reprise après sinistre (DR) des machines virtuelles est configurée à l'aide de stratégies synchrones, asynchrones ou de synchronisation stricte. DR n'est pas pris en charge pour le protocole NVMe.
* La protection des clusters hôtes ESXi utilise SnapMirror Active Sync, qui ne prend pas en charge les déploiements multi-vCenter.
* ONTAP tools limite uniquement le nombre d'hôtes ESXi et de banques de données en fonction de la taille du déploiement. Il n'y a aucune restriction sur le nombre de vCenter Servers pouvant être connectés à ONTAP tools.
* ONTAP tools effectue une découverte parallèle de tous les objets de stockage. Les limites de configuration des objets de stockage ONTAP s'appliquent quel que soit le nombre d'objets utilisés.
* ONTAP tools n'impose aucune limite quant au nombre de serveurs vCenter pouvant être intégrés. Les limites de configuration sont déterminées par le nombre d'hôtes et de banques de données pris en charge, comme indiqué dans le tableau suivant.


|===
| Déploiement | Nombre de banques de données VMFS et NFS | Nombre de banques de données VMFS activées pour la reprise après sinistre | Nombre d'hôtes 


| Non HA petit | 200 | 80 | 32 


| Non HA Moyen | 250 | 100 | 32 


| HA petit | 350 | 200 | 64 


| HA Moyen | 600 | 200 | 128 


| HAUTE disponibilité | 1024 | 250 | 256 
|===


== Outils ONTAP pour VMware vSphere - Storage Replication adapter (SRA)

Le tableau suivant indique les chiffres pris en charge par instance VMware Live site Recovery à l'aide des outils ONTAP pour VMware vSphere.

|===
| *Taille du déploiement vCenter* | *Petit* | *Moyen* 


| Nombre total de machines virtuelles configurées pour la protection à l'aide de la réplication basée sur les baies | 2000 | 5000 


| Nombre total de groupes de protection de réplication basés sur les baies | 250 | 250 


| Nombre total de groupes de protection par plan de reprise d'activité | 50 | 50 


| Nombre de datastores répliqués | 255 | 255 


| Nombre de VM | 4000 | 7000 
|===
Le tableau suivant indique le nombre de VMware Live site Recovery et les outils ONTAP correspondants pour la taille du déploiement de VMware vSphere.

|===


| *Nombre d'instances de VMware Live site Recovery* | *Déploiement des outils ONTAP taille* 


| Jusqu'à 4 | Petit 


| 4 à 8 | Moyen 


| Plus de 8 | Grand 
|===
Pour plus d'informations, reportez-vous https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limites opérationnelles de la restauration VMware Live site"]à .
