---
permalink: deploy/sizing-requirements.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: 'Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître l"espace requis pour le package de déploiement ainsi que certaines exigences de base en matière de système hôte.' 
---
= Conditions préalables au déploiement des outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître l'espace requis pour le package de déploiement ainsi que certaines exigences de base en matière de système hôte.

Vous pouvez utiliser les outils ONTAP pour VMware vSphere avec VMware vCenter Server Virtual Appliance (vCSA). Vous devez déployer les outils ONTAP pour VMware vSphere sur un client vSphere pris en charge qui inclut le système ESXi.

* *Espace requis pour le package d'installation par nœud*
+
** 10 Go pour les installations à provisionnement fin
** 248 Go pour les installations à provisionnement lourd


* *Exigences de dimensionnement du système hôte par nœud*
La mémoire recommandée par taille de déploiement et par nœud est indiquée dans le tableau ci-dessous :


|===


| *Type de déploiement* | *CPU* | *Mémoire (Go)* 


| Petit (S) | 8 | 16 


| Moyen (M) | 12 | 24 


| Grand (L) | 16 | 32 
|===
Voir link:../deploy/config-limits.html["Limites de configuration pour le déploiement des outils ONTAP pour VMware vSphere"]pour plus de détails.



== Exigences minimales en matière de stockage et d'applications

|===
| Stockage, hôte et applications | Configuration minimale requise pour la version 


| ONTAP | Dernière version de correctif de ONTAP 9.12.1, 9.13.1, 9.14.1 et 9.15.1. 


| Hôtes ESXi | ESXi 7.0.3 


| Serveur vCenter | VCenter 7.0U3 


| Fournisseur VASA | 3.0 


| Application OVA | 10,2 
|===
La matrice d'interopérabilité (IMT) contient les dernières informations sur les versions prises en charge de ONTAP, de vCenter Server, d'hôtes ESXi et d'applications de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité"^]
