---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Vous devez créer des groupes de protection pour protéger un groupe de machines virtuelles sur le site protégé. 
---
= Configuration des sites protégés et de reprise après incident
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer des groupes de protection pour protéger un groupe de machines virtuelles sur le site protégé.

Lorsque vous ajoutez une nouvelle banque de données, vous pouvez l'inclure dans le groupe de banques de données existant ou en ajouter une nouvelle et créer un volume ou un groupe de cohérence à protéger. Après avoir ajouté une nouvelle banque de données à un groupe de cohérence ou à un volume protégé, mettez à jour SnapMirror et effectuez la découverte du stockage sur les sites protégé et de récupération. Vous pouvez exécuter la découverte manuellement ou selon un calendrier pour garantir la détection et la protection de la nouvelle banque de données.



== Protection par paires et sites de reprise après incident

Vous devez coupler les sites protégés et de reprise créés à l'aide de votre client vSphere pour permettre à Storage Replication adapter (SRA) de détecter les systèmes de stockage.


NOTE: L'adaptateur de réplication de stockage (SRA) prend en charge la distribution avec une relation de synchronisation de type Duplex de basculement automatisé et une relation asynchrone SnapMirror sur le groupe de cohérence. Toutefois, la réplication « Fan-Out » avec deux SnapMirror asynchrones sur le groupe de cohérence ou sur le volume n'est pas prise en charge.

.Avant de commencer
* VMware Live site Recovery doit être installé sur les sites protégés et de reprise.
* SRA doit être installée sur les sites protégés et de reprise.


.Étapes
. Sur la page d’accueil de vSphere Client, double-cliquez sur l’icône *Site Recovery*, puis sélectionnez *Sites*.
. Sélectionnez *objets* > *actions* > *associer sites*.
. Dans la boîte de dialogue *pair site Recovery Manager Servers*, entrez l'adresse du Platform Services Controller du site protégé, puis sélectionnez *Next*.
. Dans la section Select vCenter Server, procédez comme suit :
+
.. Vérifiez que le serveur vCenter du site protégé apparaît comme candidat correspondant au couplage.
.. Entrez les informations d'identification d'administration SSO, puis sélectionnez *Terminer*.


. Si vous y êtes invité, sélectionnez *Oui* pour accepter les certificats de sécurité.


.Résultat
La boîte de dialogue *Objets* affiche les sites protégés et de récupération.



== Configuration des groupes de protection

.Avant de commencer
Vous devez vous assurer que les sites source et cible sont configurés pour les sites suivants :

* La même version de VMware Live site Recovery est installée
* Ordinateurs virtuels
* Sites protégés et de reprise par paires
* Les datastores source et de destination doivent être montés sur les sites respectifs


.Étapes
. Connectez-vous à vCenter Server et sélectionnez *Site Recovery* > *Groupes de protection*.
. Dans le volet *groupes de protection*, sélectionnez *Nouveau*.
. Spécifiez un nom et une description pour le groupe de protection, Direction et sélectionnez *Suivant*.
. Dans le champ *Type*, sélectionnez l'option *Type* comme groupes de banques de données (réplication basée sur une baie) pour les banques de données NFS et VMFS. Le domaine d'erreur ne comprend que les SVM avec réplication activée. Les SVM pour lesquelles seul le peering est implémenté et qui ne présentent aucun problème sont affichées.
. Dans l'onglet Replication Groups, sélectionnez la paire de matrices activée ou les groupes de réplication sur lesquels la machine virtuelle est configurée, puis sélectionnez *Next*.
+
Toutes les machines virtuelles du groupe de réplication sont ajoutées au groupe de protection.

. Vous pouvez sélectionner le plan de récupération existant ou en créer un nouveau en sélectionnant *Ajouter au nouveau plan de récupération*.
. Dans l'onglet prêt à terminer, vérifiez les détails du groupe de protection que vous avez créé, puis sélectionnez *Terminer*.

