---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Configurez une banque de données d’espace réservé pour réserver de l’espace dans l’inventaire vCenter sur le site de récupération pour les machines virtuelles (VM) protégées.  Les magasins de données d"espace réservé nécessitent une capacité minimale, car les machines virtuelles d"espace réservé sont petites et n"utilisent généralement que quelques centaines de kilo-octets.' 
---
= Configurer les magasins de données de substitution dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurez une banque de données d’espace réservé pour réserver de l’espace dans l’inventaire vCenter sur le site de récupération pour les machines virtuelles (VM) protégées.  Les magasins de données d'espace réservé nécessitent une capacité minimale, car les machines virtuelles d'espace réservé sont petites et n'utilisent généralement que quelques centaines de kilo-octets.

.Avant de commencer
* Assurez-vous que les sites protégés et de récupération sont connectés.
* Vérifiez que les mappages de ressources ont été configurés.


.Étapes
. Connectez-vous à vCenter Server et sélectionnez *site Recovery* > *sites*.
. Sélectionnez votre site protégé et sélectionnez *gérer*.
. Sélectionnez *Placeholder datastores* > *New* dans l'onglet gérer pour créer un nouveau datastore de marque de réservation.
. Sélectionnez le datastore approprié et sélectionnez *OK*.
+

NOTE: Les magasins de données d'espace réservé peuvent résider sur un stockage local ou distant, mais ils ne nécessitent pas de réplication.

. Répétez les étapes 3 à 5 pour configurer un datastore de marque de réservation pour le site de reprise.

