---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez configurer les systèmes de stockage avant d"exécuter Storage Replication adapter \(SRA\) pour site Recovery Manager \(SRM\).' 
---
= Configurez SRA pour les environnements SAN et NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer les systèmes de stockage avant d'exécuter Storage Replication adapter (SRA) pour site Recovery Manager (SRM).



== Configurez SRA pour l'environnement SAN

*Ce dont vous aurez besoin*

Les programmes suivants doivent être installés sur le site protégé et le site de reprise :

* SRM
+
La documentation relative à l'installation de SRM est disponible sur le site VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentation VMware site Recovery Manager"]

* SRA
+
L'adaptateur est installé sur SRM.



*Étapes*

. Vérifiez que les hôtes ESXi principaux sont connectés aux LUN du système de stockage principal du site protégé.
. Vérifiez que LES LUN sont dans des igroups qui ont `ostype` Option définie sur _VMware_ sur le système de stockage principal.
. Vérifier que les hôtes ESXi sur le site de reprise disposent d'une connectivité iSCSI appropriée à la machine virtuelle de stockage (SVM). Les hôtes ESXi du site secondaire doivent avoir accès au système de stockage du site secondaire, de même que les hôtes ESXi du site principal doivent avoir accès au stockage du site principal.
+
Vous pouvez le faire en vérifiant que les hôtes ESXi disposent de LUN locales connectées au SVM ou au `iscsi show initiators` Commande sur les SVM.
Vérifiez l'accès aux LUN mappées sur l'hôte ESXi pour vérifier la connectivité iSCSI.





== Configurez SRA pour l'environnement NAS

*Ce dont vous aurez besoin*

Les programmes suivants doivent être installés sur le site protégé et le site de reprise :

* SRM
+
La documentation relative à l'installation de SRM est disponible sur le site de VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentation VMware site Recovery Manager"]

* SRA
+
L'adaptateur est installé sur SRM et le serveur SRA.



*Étapes*

. Vérifiez que les datastores du site protégé contiennent des machines virtuelles enregistrées auprès de vCenter Server.
. Vérifier que les hôtes ESXi du site protégé ont monté les volumes NFS exportés depuis la machine virtuelle de stockage (SVM).
. Vérifiez que les adresses valides telles que l'adresse IP, le nom d'hôte ou le FQDN sur lequel les exportations NFS sont présentes sont spécifiées dans le champ *NFS Addresses* lors de l'utilisation de l'assistant Array Manager pour ajouter des matrices à SRM.
. Utilisez le `ping` Commande sur chaque hôte ESXi du site de reprise pour vérifier que l'hôte dispose d'un port VMkernel qui peut accéder aux adresses IP utilisées pour servir les exportations NFS à partir du SVM.

