---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez configurer les systèmes de stockage avant d"exécuter Storage Replication adapter \(SRA\) pour VMware Live site Recovery.' 
---
= Configurer SRA dans ONTAP tools for VMware vSphere pour les environnements SAN et NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer les systèmes de stockage avant d'exécuter Storage Replication adapter (SRA) pour VMware Live site Recovery.



== Configurez SRA pour les environnements SAN

.Avant de commencer
Les programmes suivants doivent être installés sur le site protégé et le site de reprise :

* VMware Live Site Recovery : le site VMware fournit une documentation d’installation pour VMware Live Site Recovery.
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["À propos de VMware Live site Recovery"]

* SRA : installez l’adaptateur sur VMware Live Site Recovery.


.Étapes
. Vérifiez que les hôtes ESXi principaux sont connectés aux LUN du système de stockage principal du site protégé.
. Vérifiez que LES LUN sont dans des igroups qui ont `ostype` Option définie sur _VMware_ sur le système de stockage principal.
. Vérifiez que les hôtes ESXi sur le site de récupération disposent d’une connectivité iSCSI et Fibre Channel appropriée à la machine virtuelle de stockage (SVM).  Les hôtes ESXi du site secondaire doivent avoir accès au stockage du site secondaire et les hôtes ESXi du site principal doivent avoir accès au stockage du site principal.
+
Vous pouvez le faire en vérifiant que les hôtes ESXi disposent de LUN locales connectées au SVM ou au `iscsi show initiators` Commande sur les SVM.
Vérifiez l'accès aux LUN mappées sur l'hôte ESXi pour vérifier la connectivité iSCSI.





== Configurez SRA pour les environnements NAS

.Avant de commencer
Les programmes suivants doivent être installés sur le site protégé et le site de reprise :

* VMware Live Site Recovery : vous pouvez trouver la documentation d'installation de VMware Live Site Recovery sur le site VMware - https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["À propos de VMware Live site Recovery"]
* SRA : installez l’adaptateur sur VMware Live Site Recovery et le serveur SRA.


.Étapes
. Vérifiez que les datastores du site protégé contiennent des machines virtuelles enregistrées auprès de vCenter Server.
. Vérifier que les hôtes ESXi du site protégé ont monté les volumes NFS exportés depuis la machine virtuelle de stockage (SVM).
. Vérifiez que des adresses valides, telles que l'adresse IP ou le nom de domaine complet (FQDN) sur lesquels les exportations NFS sont présentes, sont spécifiées dans le champ « Adresses NFS » lorsque vous utilisez l'assistant Gestionnaire de baies pour ajouter des baies à VMware Live Site Recovery. N'utilisez pas le nom d'hôte NFS dans le champ « Adresses NFS ».
. Utilisez le `ping` Commande sur chaque hôte ESXi du site de reprise pour vérifier que l'hôte dispose d'un port VMkernel qui peut accéder aux adresses IP utilisées pour servir les exportations NFS à partir du SVM.

