---
permalink: protect/pair-protected-and-recovery-sites.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez coupler les sites protégés et de reprise créés à l"aide de votre client vSphere pour permettre à Storage Replication adapter \(SRA\) de détecter les systèmes de stockage.' 
---
= Protection par paires et sites de reprise après incident
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez coupler les sites protégés et de reprise créés à l'aide de votre client vSphere pour permettre à Storage Replication adapter (SRA) de détecter les systèmes de stockage.

.Avant de commencer
* VMware Live site Recovery doit être installé sur les sites protégés et de reprise.
* SRA doit être installée sur les sites protégés et de reprise.


.Étapes
. Double-cliquez sur *site Recovery* sur la page d'accueil du client vSphere et sélectionnez *sites*.
. Sélectionnez *objets* > *actions* > *associer sites*.
. Dans la boîte de dialogue *pair site Recovery Manager Servers*, entrez l'adresse du Platform Services Controller du site protégé, puis sélectionnez *Next*.
. Dans la section Select vCenter Server, procédez comme suit :
+
.. Vérifiez que le serveur vCenter du site protégé apparaît comme candidat correspondant au couplage.
.. Entrez les informations d'identification d'administration SSO, puis sélectionnez *Terminer*.


. Si vous y êtes invité, sélectionnez *Oui* pour accepter les certificats de sécurité.


.Résultat
Les sites protégés et de restauration s'affichent dans la boîte de dialogue objets.
