---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 'Pour que VMware Live site Recovery puisse communiquer avec SRA, vous devez mettre à jour les informations d"identification SRA sur le serveur VMware Live site Recovery si vous avez modifié les informations d"identification.' 
---
= Mettre à jour les informations d'identification SRA dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que VMware Live site Recovery puisse communiquer avec SRA, vous devez mettre à jour les informations d'identification SRA sur le serveur VMware Live site Recovery si vous avez modifié les informations d'identification.

.Avant de commencer
Vous devez avoir exécuté les étapes mentionnées dans la rubrique link:../protect/configure-on-srm-appliance.html["Configuration de SRA sur l'appliance VMware Live site Recovery"].

.Étapes
. Exécutez les commandes suivantes pour supprimer les informations d'identification des outils ONTAP mises en cache sur la machine VMware Live Site Recovery :
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Exécutez la commande Perl pour configurer SRA avec les nouvelles informations d'identification :
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Vous devez avoir un devis unique autour de la valeur du mot de passe.
+
Un message de confirmation s'affiche indiquant que les informations d'identification de stockage ont bien été enregistrées. SRA peut communiquer avec le serveur SRA en utilisant l'adresse IP, le port et les informations d'identification fournis.







== Reconfigurez vCenter dans l'appliance VMware Live Site Recovery après un changement de certificat

Si le certificat vCenter change, par exemple après une mise à niveau vCenter, vous pouvez rencontrer une erreur d'empreinte numérique non concordante dans l'extension Site Recovery. Suivez les étapes ci-dessous pour résoudre ce problème.

.Étapes
. Reconfigurer vCenter dans l'appliance VMware Live Site Recovery
+
.. Ouvrez l'interface de gestion de l'appliance VMware Live Site Recovery dans un navigateur : `\https://<SRM_IP>:5480`
.. Sélectionnez l'onglet *Résumé*.
.. Sélectionnez *Reconfigurer* pour la connexion au serveur vCenter.
+
Cette fonction récupère et accepte l'empreinte numérique du certificat la plus récente provenant de vCenter.



. Reconnecter le site d'appairage (si l'erreur persiste)
+
Si l'erreur de non-concordance d'empreinte digitale persiste après reconfiguration :

+
.. Connectez-vous à l’interface utilisateur vCenter.
.. Accédez à l'extension *Site Recovery*.
.. Repérez la section *Appariement de sites*.
.. Sélectionnez *Reconnect* pour rétablir l'association du site avec le certificat mis à jour.



