---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords: key concepts, ONTAP tools terms, consistency group, dual stack 
summary: Examinez les concepts et termes clés utilisés dans la documentation des ONTAP tools for VMware vSphere. 
---
= Termes clés et définitions pour ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Familiarisez-vous avec les concepts et la terminologie clés utilisés dans ONTAP tools for VMware vSphere. Les définitions couvrent les backends de stockage, les volumes virtuels (vVols), la synchronisation active SnapMirror, VASA, SRA et d'autres composants essentiels.



[[certificate-authority-ca]]
=== Autorité de certification (CA)

Une autorité de certification (CA) est une entité de confiance qui délivre des certificats SSL (Secure Sockets Layer).



[[consistency-group]]
=== Groupe de cohérence

Un groupe de cohérence est un ensemble de volumes gérés comme une seule unité. Les groupes de cohérence sont synchronisés pour la cohérence des données entre les unités de stockage et les volumes. Dans ONTAP, ils offrent une gestion simplifiée et des garanties de protection pour une charge de travail applicative répartie sur plusieurs volumes. En savoir plus https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["groupes de cohérence"].



[[dual-stack]]
=== Double pile

Un réseau à double pile est un environnement réseau qui prend en charge l'utilisation simultanée des adresses IPv4 et IPv6.



[[high-availability-ha]]
=== Haute disponibilité (HA)

Les nœuds de cluster sont configurés en paires haute disponibilité pour assurer la continuité de l'activité.



[[logical-unit-number-lun]]
=== Numéro d'unité logique (LUN)

Une LUN est un numéro permettant d'identifier une unité logique au sein d'un réseau de stockage (SAN). Ces périphériques adressables sont généralement des disques logiques accessibles via le protocole SCSI (Small Computer System interface) ou l'un de ses dérivés encapsulés.



[[nvme-namespace-and-subsystem]]
=== Espace de noms et sous-système NVMe

Un espace de noms NVMe correspond à une quantité de mémoire non volatile pouvant être formatée en blocs logiques. Les espaces de noms sont l'équivalent des LUN pour les protocoles FC et iSCSI, et un sous-système NVMe est analogue à un igroup. Un sous-système NVMe peut être associé à des initiateurs, leur permettant d'accéder aux espaces de noms au sein du sous-système.



[[ontap-tools-manager]]
=== Gestionnaire d'outils ONTAP

ONTAP tools Manager offre ONTAP tools for VMware vSphere aux administrateurs un contrôle accru sur les instances de serveur vCenter gérées et les backends de stockage intégrés. Il aide à gérer les instances de serveur vCenter, les backends de stockage, les certificats, les mots de passe et les bundles de journaux.



[[open-virtual-appliance-ova]]
=== Appliance virtuelle ouverte (OVA)

OVA est une norme ouverte pour le packaging et la distribution d'appliances ou de logiciels virtuels devant être exécutés sur des machines virtuelles.



[[recovery-point-objective-rpo]]
=== Objectif de point de récupération

Le RPO (objectif de point de restauration) mesure la fréquence à laquelle vous sauvegardez ou répliquez vos données. Il spécifie le moment précis où vous devez restaurer les données après une interruption de service pour reprendre les opérations commerciales. Par exemple, si une organisation a un RPO de quatre heures, elle peut tolérer la perte de quatre heures de données en cas de sinistre.



[[snapmirror-active-sync]]
=== Synchronisation active SnapMirror

SnapMirror active sync permet aux services métier de continuer à fonctionner même en cas de panne complète d'un site, en prenant en charge le basculement transparent des applications grâce à une copie secondaire. SnapMirror active sync ne nécessite aucune intervention manuelle ni script personnalisé pour déclencher un basculement. En savoir plus https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Synchronisation active SnapMirror"].



[[storage-backends]]
=== Systèmes back-end

Les systèmes back-end de stockage constituent l'infrastructure de stockage sous-jacente utilisée par l'hôte ESXi pour stocker les fichiers, données et autres ressources des machines virtuelles. Ils permettent à l'hôte ESXi d'accéder aux données persistantes et de les gérer, offrant ainsi les capacités de stockage et les performances requises pour un environnement virtualisé.

.Cluster global (back-end de stockage)
Les systèmes back-end de stockage global, disponibles uniquement avec des identifiants de cluster ONTAP, sont intégrés via l'interface ONTAP Tools Manager. Ils peuvent être ajoutés avec un Privileges minimal pour permettre la découverte des ressources de cluster essentielles nécessaires à la gestion des vVols. Les clusters globaux sont parfaits pour les scénarios de colocation dans lesquels un utilisateur SVM est ajouté localement pour la gestion des vVols.

.Back-end du stockage local
Les systèmes back-end de stockage local dotés d'identifiants de cluster ou SVM sont ajoutés via l'interface utilisateur des outils ONTAP et limités à une instance vCenter. Lors de l'utilisation locale des identifiants de cluster, les SVM associés sont automatiquement mappés avec vCenter pour gérer les vVols ou VMFS. Pour la gestion VMFS, notamment SRA, les outils ONTAP prennent en charge les identifiants SVM sans avoir besoin d'un cluster global.



[[storage-replication-adapter-sra]]
=== Storage Replication adapter (SRA)

SRA est le logiciel spécifique au fournisseur de stockage installé dans l'appliance VMware Live site Recovery. L'adaptateur permet la communication entre site Recovery Manager et un contrôleur de stockage au niveau du SVM (Storage Virtual machine) et la configuration au niveau du cluster.



[[storage-virtual-machine-svm]]
=== SVM (Storage Virtual machine)

SVM est l'unité de multitenancy dans ONTAP. À l'instar d'une machine virtuelle exécutée sur un hyperviseur, SVM est une entité logique qui abstrait les ressources physiques. SVM contient des volumes de données et une ou plusieurs LIF par lesquelles elle distribue les données aux clients.



[[uniform-and-non-uniform-configuration]]
=== Configuration uniforme et non uniforme

* *Accès hôte uniforme* signifie que les hôtes de deux sites sont connectés à tous les chemins vers les clusters de stockage sur les deux sites. Les chemins d'accès intersites sont étendus sur plusieurs distances.
* *Accès hôte non uniforme* signifie que les hôtes de chaque site sont connectés uniquement au cluster du même site. Les chemins intersites et les chemins étendus ne sont pas connectés.
+

NOTE: SnapMirror active sync prend en charge l'accès uniforme à l'hôte pour tout déploiement ; seuls les déploiements symétriques actif/actif prennent en charge l'accès non uniforme à l'hôte. En savoir plus https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Présentation de la synchronisation active SnapMirror dans ONTAP"].





[[virtual-machine-file-system-vmfs]]
=== VMFS (Virtual machine File System)

VMFS est un système de fichiers en cluster conçu pour stocker des fichiers de machines virtuelles dans des environnements VMware vSphere.



[[virtual-volumes-vvols]]
=== Volumes virtuels (vvols)

vVols fournissent une abstraction au niveau du volume pour le stockage utilisé par une machine virtuelle. vVols offrent plusieurs avantages et constituent une alternative à l'utilisation d'un LUN traditionnel. Un datastore vVol est généralement associé à un seul LUN qui sert de conteneur pour les vVols.



[[vm-storage-policy]]
=== Stratégie de stockage de VM

Les stratégies de stockage VM sont créées dans vCenter Server sous stratégies et profils. Pour les vVols, créez un jeu de règles à l'aide de règles provenant du fournisseur de type de stockage NetApp vVols.



[[vmware-live-site-recovery]]
=== Restauration de site en direct VMware

VMware Live Site Recovery, anciennement connu sous le nom de Site Recovery Manager (SRM), offre des fonctionnalités de continuité d'activité, de reprise après sinistre, de migration de site et de test non perturbateur pour les environnements virtuels VMware.



[[vmware-vsphere-apis-for-storage-awareness-vasa]]
=== API VMware vSphere pour la sensibilisation du stockage (VASA)

Vasa est un ensemble d'API qui intègre les baies de stockage à vCenter Server pour la gestion et l'administration. L'architecture repose sur plusieurs composants, notamment le VASA Provider, qui gère les communications entre VMware vSphere et les systèmes de stockage.



[[vmware-vsphere-storage-apis-array-integration-vaai]]
=== API de stockage VMware vSphere - intégration de baies (VAAI)

VAAI est un ensemble d'API qui permet la communication entre les hôtes VMware vSphere ESXi et les périphériques de stockage. Les API incluent un ensemble d'opérations primitives utilisées par les hôtes pour décharger les opérations de stockage vers la baie. VAAI permet d'améliorer considérablement les performances des tâches consommatrices de stockage.



[[vsphere-metro-storage-cluster]]
=== Cluster de stockage vSphere Metro

vSphere Metro Storage Cluster (vMSC) est une architecture qui permet et prend en charge vSphere dans un déploiement de cluster étendu. Les solutions vMSC sont prises en charge sur NetApp MetroCluster et SnapMirror active sync (anciennement SMBC). Ces solutions offrent une continuité d'activité renforcée en cas de panne de domaine. Le modèle de résilience dépend de vos choix de configuration spécifiques. En savoir plus https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["Cluster de stockage VMware vSphere Metro"].



[[vvols-datastore]]
=== Datastore vVols

Le vVols datastore est une représentation logique d'un vVols container créé et maintenu par un VASA Provider.



[[zero-rpo]]
=== RPO nul

RPO désigne l'objectif de point de récupération, la quantité de perte de données jugée acceptable au cours d'une période donnée. La valeur RPO de zéro signifie qu'aucune perte de données n'est acceptable.
