---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords: ONTAP tools overview, virtual machine lifecycle, VASA Provider, disaster recovery 
summary: Découvrez comment les ONTAP tools for VMware vSphere prennent en charge la gestion du cycle de vie du stockage des machines virtuelles, le provisionnement des datastores et la reprise après sinistre. 
---
= Découvrez les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools pour VMware vSphere est une suite d'outils de gestion du cycle de vie des machines virtuelles. Elle s'intègre à l'écosystème VMware pour simplifier le provisionnement des datastores et fournir une protection de base ainsi qu'une reprise après sinistre pour les machines virtuelles. Déployée sous forme d'Open Virtual Appliance (OVA), elle utilise des microservices événementiels à scalabilité horizontale pour garantir des performances fiables à grande échelle.

Les ONTAP tools for VMware vSphere prennent en charge :

* Fonctionnalités principales des machines virtuelles (VM) telles que la protection et la reprise après sinistre
* Fournisseur VASA pour la gestion basée sur les politiques de stockage
* Gestion du stockage basée sur des règles
* Storage Replication adapter (SRA)


.Haute disponibilité pour ONTAP tools for VMware vSphere
Les ONTAP tools for VMware vSphere offrent une prise en charge de haute disponibilité (HA) pour aider à maintenir un fonctionnement ininterrompu en cas de panne.

La solution HA vous aide à récupérer rapidement des types de pannes suivants :

* Panne de l'hôte : seule une panne d'un seul nœud est prise en charge.
* Défaillance du réseau
* Panne de la machine virtuelle (système d'exploitation invité)
* Échec de l'application (outils ONTAP )


Vous n’avez pas besoin d’effectuer de configuration supplémentaire pour activer les ONTAP tools for VMware vSphere.

[NOTE]
====
Les ONTAP tools for VMware vSphere ne prennent pas en charge vCenter HA.

====
Pour utiliser la fonction HA, assurez-vous que l'ajout à chaud du processeur et le branchement à chaud de la mémoire sont activés lors du déploiement ou dans les paramètres de la machine virtuelle.
