---
permalink: concepts/rbac-vcenter-use.html 
sidebar: sidebar 
keywords: vcenter, vcenter server, vcenter server rbac, use rbac 
summary: 'Il existe plusieurs aspects des outils ONTAP pour l"implémentation de VMware vSphere 10 RBAC avec vCenter Server que vous devez prendre en compte avant de l"utiliser dans un environnement de production.' 
---
= Utilisez vCenter Server RBAC avec les outils ONTAP pour VMware vSphere 10
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs aspects des outils ONTAP pour l'implémentation de VMware vSphere 10 RBAC avec vCenter Server que vous devez prendre en compte avant de l'utiliser dans un environnement de production.



== Rôles vCenter et compte administrateur

Vous n'avez besoin de définir et d'utiliser les rôles de serveur vCenter personnalisés que si vous souhaitez limiter l'accès aux objets vSphere et aux tâches administratives associées. Si la limitation de l'accès n'est pas nécessaire, vous pouvez utiliser un compte d'administrateur. Chaque compte administrateur est défini avec le rôle Administrateur au niveau supérieur de la hiérarchie des objets. Vous bénéficiez ainsi d'un accès complet aux objets vSphere, y compris ceux ajoutés par les outils ONTAP pour VMware vSphere 10.



== Hiérarchie des objets vSphere

L'inventaire des objets vSphere est organisé dans une hiérarchie. Par exemple, vous pouvez déplacer la hiérarchie vers le bas comme suit :

`vCenter Server` --> `Datacenter` --> `Cluster` --> - `Virtual Machine`-> `ESXi host`

Toutes les autorisations sont validées dans la hiérarchie des objets vSphere, à l'exception des opérations du plug-in VAAI, qui sont validées par rapport à l'hôte ESXi cible.



== Rôles inclus avec les outils ONTAP pour VMware vSphere 10

Pour simplifier l'utilisation du RBAC de vCenter Server, les outils ONTAP pour VMware vSphere fournissent des rôles prédéfinis adaptés à diverses tâches d'administration.


NOTE: Vous pouvez créer de nouveaux rôles personnalisés si nécessaire. Dans ce cas, vous devez cloner l'un des rôles d'outils ONTAP existants et le modifier si nécessaire. Après avoir modifié la configuration, les utilisateurs du client vSphere concernés doivent se déconnecter et se reconnecter pour activer les modifications.

Pour afficher les ONTAP tools for VMware vSphere , sélectionnez *Menu* en haut du client vSphere, puis cliquez sur *Administration* et enfin sur *Rôles* à gauche. Les privilèges suivants doivent être inclus dans le rôle attribué à l'utilisateur vCenter responsable du déploiement ou de l'intégration de vCenter. Assurez-vous que ces privilèges sont configurés comme condition préalable au déploiement ou au processus d'intégration.

* Alarmes
+
** Accuser réception de l'alarme


* Bibliothèque de contenu
+
** Ajouter un élément de bibliothèque
** Vérifier dans un modèle
** Consultez un modèle
** Télécharger les fichiers
** Stockage d'importation
** Stockage de lecture
** Élément de bibliothèque synchroniser
** Bibliothèque synchronisée par abonnement
** Afficher les paramètres de configuration


* Datastore
+
** Allouer de l'espace
** Parcourir le magasin de données
** Opérations de fichiers de bas niveau
** Supprimer le fichier
** Mettre à jour les fichiers de la machine virtuelle
** Mettre à jour les métadonnées de la machine virtuelle


* Gestionnaire d'agents ESX
+
** View


* Dossier
+
** Créer un dossier


* Hôte
+
** Configuration
+
*** Paramètres avancés
*** Modifier les paramètres
*** Configuration du réseau
*** Ressources système
*** configuration du démarrage automatique de la machine virtuelle


** Opérations locales
+
*** Créer une machine virtuelle
*** Supprimer la machine virtuelle
*** Reconfigurer la machine virtuelle




* Réseau
+
** Attribuer un réseau
** Configure


* Gestionnaire Ovf
+
** Accès consommateur Ovf


* Profil de l'hôte
+
** View


* Ressource
+
** Affecter une machine virtuelle au pool de ressources


* Tâche planifiée
+
** Créer des tâches
** Modifier la tâche
** Exécuter la tâche


* Tâches
+
** Créer une tâche
** Tâche de mise à jour


* vApp
+
** Ajouter une machine virtuelle
** Affecter un pool de ressources
** Attribuer une vApp
** Créer
** Importer
** Se déplacer
** Mise hors tension
** Mise sous tension
** Récupérer depuis l'URL
** Afficher l'environnement OVF


* Ordinateur virtuel
+
** Modifier la configuration
+
*** Ajouter un disque existant
*** Ajouter un nouveau disque
*** Ajouter ou supprimer un appareil
*** Configuration avancée
*** Modifier le nombre de cœurs du processeur
*** Changer la mémoire
*** Modifier les paramètres
*** Modifier la ressource
*** Étendre le disque virtuel
*** Modifier les paramètres de l'appareil
*** Retirer le disque
*** Réinitialiser les informations des invités
*** Mise à niveau de la compatibilité des machines virtuelles


** Modifier l'inventaire
+
*** Créer à partir d'un existant
*** Créer un nouveau
*** Se déplacer
*** Registre
*** Retirer
*** Désinscription


** Interaction
+
*** Opération de sauvegarde sur machine virtuelle
*** Configurer le support CD
*** Configurer le lecteur de disquettes
*** Appareils de connexion
*** Interaction avec la console
*** Gestion du système d'exploitation invité par l'API VIX
*** Mise hors tension
*** Mise sous tension
*** Réinitialiser
*** Suspendre


** Provisionnement
+
*** Autoriser l'accès au disque
*** Modèle clone
*** Personnaliser l'expérience invité
*** Modèle de déploiement
*** Modifier les spécifications de personnalisation
*** Lire les spécifications de personnalisation


** Gestion des instantanés
+
*** Créer un instantané
*** Supprimer l'instantané
*** Renommer l'instantané
*** Rétablir l'instantané






Il existe trois rôles prédéfinis comme décrit ci-dessous.

.Outils NetApp ONTAP pour VMware vSphere Administrator
Fournit tous les outils vCenter Server Privileges natifs et ONTAP spécifiques Privileges requis pour effectuer les tâches d'administration des principaux outils ONTAP pour VMware vSphere.

.Outils NetApp ONTAP pour VMware vSphere en lecture seule
Accès en lecture seule aux outils ONTAP. Ces utilisateurs ne peuvent pas exécuter d'actions ONTAP Tools for VMware vSphere contrôlées par accès.

.Outils NetApp ONTAP pour le provisionnement VMware vSphere
Fournit certains privilèges vCenter Server natifs et certains privilèges spécifiques aux outils ONTAP requis pour provisionner le stockage. Vous pouvez effectuer les tâches suivantes :

* Créer de nouveaux datastores
* Gérer les datastores




== Objets vSphere et systèmes back-end de stockage ONTAP

Les deux environnements RBAC fonctionnent ensemble. Lors de l'exécution d'une tâche dans l'interface client vSphere, les rôles des outils ONTAP définis pour vCenter Server sont vérifiés en premier. Si l'opération est autorisée par vSphere, le Privileges de rôle ONTAP est examiné. Cette deuxième étape est effectuée en fonction du rôle ONTAP attribué à l'utilisateur au moment de la création et de la configuration du back-end de stockage.



== Utilisation de vCenter Server RBAC

Vous devez tenir compte de quelques éléments lorsque vous travaillez avec vCenter Server Privileges et les autorisations.



=== Privilèges requis

Pour accéder à l'interface utilisateur des outils ONTAP pour VMware vSphere 10, vous devez disposer du privilège _View_ spécifique aux outils ONTAP. Si vous vous connectez à vSphere sans ce privilège et que vous cliquez sur l'icône NetApp, ONTAP Tools for VMware vSphere affiche un message d'erreur et vous empêche d'accéder à l'interface utilisateur.

Le niveau d'affectation dans la hiérarchie des objets vSphere détermine les parties de l'interface utilisateur auxquelles vous pouvez accéder. L'attribution du privilège d'affichage à l'objet racine vous permet d'accéder aux outils ONTAP pour VMware vSphere en cliquant sur l'icône NetApp.

Vous pouvez à la place attribuer le privilège d'affichage à un autre niveau d'objet vSphere inférieur. Toutefois, cela limite les menus des outils ONTAP pour VMware vSphere auxquels vous pouvez accéder et utiliser.



=== Attribution d'autorisations

Vous devez utiliser les autorisations vCenter Server si vous souhaitez limiter l'accès aux objets et aux tâches vSphere. Lorsque vous attribuez des autorisations dans la hiérarchie d'objets vSphere, les outils ONTAP pour les tâches VMware vSphere 10 peuvent être utilisés par les utilisateurs.


TIP: À moins que vous n'ayez besoin de définir un accès plus restrictif, il est généralement recommandé d'attribuer des autorisations au niveau de l'objet racine ou du dossier racine.

Les autorisations disponibles avec les outils ONTAP pour VMware vSphere 10 s'appliquent aux objets non vSphere personnalisés, tels que les systèmes de stockage. Si possible, vous devez attribuer ces autorisations aux outils ONTAP pour l'objet racine VMware vSphere car il n'y a pas d'objet vSphere auquel vous pouvez l'affecter. Par exemple, toute autorisation qui inclut un privilège « Ajout/modification/Suppression de systèmes de stockage » des outils ONTAP pour VMware vSphere doit être attribuée au niveau de l'objet racine.

Lors de la définition d'une autorisation à un niveau supérieur dans la hiérarchie d'objets, vous pouvez configurer l'autorisation de sorte qu'elle soit transmise et héritée par les objets enfants. Si nécessaire, vous pouvez attribuer des autorisations supplémentaires aux objets enfants qui remplacent les autorisations héritées du parent.

Vous pouvez modifier une autorisation à tout moment. Si vous modifiez l'une des Privileges dans le cadre d'une autorisation, les utilisateurs associés à cette autorisation doivent se déconnecter de vSphere et se reconnecter pour activer la modification.
