---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: RBAC framework, role-based access control, authorization, security 
summary: 'Découvrez comment le RBAC définit des rôles avec des niveaux d"autorisation spécifiques pour contrôler l"accès et simplifier la gestion des utilisateurs dans ONTAP tools.' 
---
= Découvrez le contrôle d'accès basé sur les rôles (RBAC) dans les outils ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le contrôle d'accès basé sur les rôles (RBAC) est un cadre de sécurité permettant de contrôler l'accès aux ressources au sein d'une organisation. ONTAP tools for VMware vSphere utilise le RBAC dans deux environnements distincts — VMware vCenter Server et les clusters ONTAP — afin de gérer qui peut effectuer des opérations de stockage et accéder aux objets vSphere. Le RBAC simplifie l'administration en définissant des rôles avec des niveaux d'autorité spécifiques, au lieu d'attribuer des autorisations à des utilisateurs individuels, ce qui réduit le risque d'erreur et simplifie la gestion du contrôle d'accès.

Le modèle standard RBAC se compose de plusieurs technologies d'implémentation ou phases de plus en plus complexes. Il en résulte que les déploiements RBAC réels, basés sur les besoins des fournisseurs de logiciels et de leurs clients, peuvent différer et aller de relativement simple à très complexe.



[[rbac-components]]
== Composants RBAC

Chaque implémentation RBAC comprend plusieurs composants liés de différentes manières pour définir les processus d'autorisation.

.Privilèges
Un privilège est une action ou une capacité qui peut être autorisée ou refusée. Il peut s'agir d'une action simple, comme la possibilité de lire un fichier, ou d'une opération plus abstraite, spécifique à un système logiciel donné. Privileges peuvent également être définis pour restreindre l'accès aux points de terminaison REST API et aux commandes CLI. Chaque implémentation RBAC inclut des privilèges prédéfinis et peut également permettre aux administrateurs de créer des privilèges personnalisés.

.Rôles
Un rôle est un conteneur qui inclut un ou plusieurs privilèges. Les rôles sont généralement définis en fonction de tâches ou de fonctions professionnelles particulières. Lorsqu’un rôle est attribué à un utilisateur, celui-ci reçoit tous les privilèges contenus dans ce rôle. Comme pour les privilèges, les implémentations incluent des rôles prédéfinis et permettent généralement de créer des rôles personnalisés.

.Objets
Un _objet_ représente une ressource réelle ou abstraite identifiée dans l'environnement RBAC. Les actions définies via la Privileges sont effectuées sur ou avec les objets associés. Selon l'implémentation, Privileges peut être accordé à un type d'objet ou à une instance d'objet spécifique.

.Utilisateurs et groupes
_Users_ sont affectés ou associés à un rôle appliqué après l'authentification. Certaines implémentations RBAC ne permettent d'attribuer qu'un seul rôle à un utilisateur, tandis que d'autres autorisent plusieurs rôles par utilisateur, peut-être avec un seul rôle actif à la fois. L'attribution de rôles à des _groupes_ peut simplifier davantage l'administration de la sécurité.

.Autorisations
Une _permission_ est une définition qui lie un utilisateur ou un groupe avec un rôle à un objet. Les autorisations peuvent être utiles avec un modèle d'objet hiérarchique dans lequel elles peuvent éventuellement être héritées par les enfants de la hiérarchie.



[[two-rbac-environments]]
== Deux environnements RBAC

Il existe deux environnements RBAC distincts à prendre en compte lors de l'utilisation des ONTAP tools for VMware vSphere 10. Les ONTAP tools for VMware vSphere 10 nécessitent des privilèges spécifiques dans vCenter et ONTAP pour fonctionner. Bien que les outils ONTAP automatisent les tâches de gestion du stockage, ils ne créent pas de comptes d'utilisateurs ni dans vCenter ni dans ONTAP. Les comptes de service doivent être créés par un administrateur vSphere selon les besoins. Cette documentation fournit aux administrateurs des instructions pour attribuer les rôles et les autorisations nécessaires à une gestion efficace des outils ONTAP .

.Serveur VMware vCenter
L'implémentation du contrôle d'accès basé sur les rôles (RBAC) dans VMware vCenter Server restreint l'accès aux objets exposés via l'interface utilisateur du client vSphere. Dans le cadre de l'installation des ONTAP tools for VMware vSphere 10, l'environnement RBAC est étendu afin d'inclure des objets supplémentaires représentant les fonctionnalités des ONTAP tools. L'accès à ces objets est fourni via le plug-in distant. Voir link:../concepts/rbac-vcenter-environment.html["Environnement RBAC du serveur vCenter"] pour plus d'informations.

.Groupe ONTAP
ONTAP tools for VMware vSphere 10 se connecte à un cluster ONTAP via l'API REST ONTAP pour effectuer des opérations liées au stockage. L'accès aux ressources de stockage est contrôlé par un rôle ONTAP associé à l'utilisateur ONTAP fourni lors de l'authentification. Voir link:../concepts/rbac-ontap-environment.html["Environnement ONTAP RBAC"] pour plus d'informations.
