---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: role based access control, rbac, rbac components, learn about rbac 
summary: 'Le contrôle d"accès basé sur des rôles (RBAC) est un framework de sécurité qui permet de contrôler l"accès aux ressources au sein d"une entreprise. Le contrôle d"accès basé sur des rôles simplifie l"administration en définissant des rôles disposant de niveaux d"autorisation spécifiques pour effectuer des actions, au lieu d"attribuer des autorisations à des utilisateurs individuels. Les rôles définis sont attribués aux utilisateurs, ce qui permet de réduire le risque d"erreur et simplifie la gestion du contrôle d"accès dans l"ensemble de votre organisation.' 
---
= En savoir plus sur le RBAC des outils ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le contrôle d'accès basé sur des rôles (RBAC) est un framework de sécurité qui permet de contrôler l'accès aux ressources au sein d'une entreprise. Le contrôle d'accès basé sur des rôles simplifie l'administration en définissant des rôles disposant de niveaux d'autorisation spécifiques pour effectuer des actions, au lieu d'attribuer des autorisations à des utilisateurs individuels. Les rôles définis sont attribués aux utilisateurs, ce qui permet de réduire le risque d'erreur et simplifie la gestion du contrôle d'accès dans l'ensemble de votre organisation.

Le modèle standard RBAC se compose de plusieurs technologies d'implémentation ou phases de plus en plus complexes. Il en résulte que les déploiements RBAC réels, basés sur les besoins des fournisseurs de logiciels et de leurs clients, peuvent différer et aller de relativement simple à très complexe.



== Composants RBAC

À un niveau élevé, plusieurs composants sont généralement inclus dans chaque implémentation de RBAC. Ces composants sont liés de différentes manières dans le cadre de la définition des processus d'autorisation.

.Privilèges
Un privilège est une action ou une capacité qui peut être autorisée ou refusée. Il peut s'agir d'une action simple, comme la possibilité de lire un fichier, ou d'une opération plus abstraite, spécifique à un système logiciel donné. Des Privileges peuvent également être définis pour restreindre l'accès aux points de terminaison de l'API REST et aux commandes CLI. Chaque implémentation RBAC inclut des privilèges prédéfinis et peut également permettre aux administrateurs de créer des privilèges personnalisés.

.Rôles
Un _role_ est un conteneur qui inclut un ou plusieurs Privileges. Les rôles sont généralement définis en fonction de tâches ou de fonctions particulières. Lorsqu'un rôle est attribué à un utilisateur, tous les Privileges contenus dans le rôle lui sont attribués. Comme avec Privileges, les implémentations incluent des rôles prédéfinis et permettent généralement de créer des rôles personnalisés.

.Objets
Un _objet_ représente une ressource réelle ou abstraite identifiée dans l'environnement RBAC. Les actions définies via la Privileges sont effectuées sur ou avec les objets associés. Selon l'implémentation, Privileges peut être accordé à un type d'objet ou à une instance d'objet spécifique.

.Utilisateurs et groupes
_Users_ sont affectés ou associés à un rôle appliqué après l'authentification. Certaines implémentations RBAC ne permettent d'attribuer qu'un seul rôle à un utilisateur, tandis que d'autres autorisent plusieurs rôles par utilisateur, peut-être avec un seul rôle actif à la fois. L'attribution de rôles à des _groupes_ peut simplifier davantage l'administration de la sécurité.

.Autorisations
Une _permission_ est une définition qui lie un utilisateur ou un groupe avec un rôle à un objet. Les autorisations peuvent être utiles avec un modèle d'objet hiérarchique dans lequel elles peuvent éventuellement être héritées par les enfants de la hiérarchie.



== Deux environnements RBAC

Il existe deux environnements RBAC distincts à prendre en compte lors de l'utilisation des ONTAP tools for VMware vSphere 10. Les ONTAP tools for VMware vSphere 10 nécessitent des privilèges spécifiques dans vCenter et ONTAP pour fonctionner. Bien que les outils ONTAP automatisent les tâches de gestion du stockage, ils ne créent pas de comptes d'utilisateurs ni dans vCenter ni dans ONTAP. Les comptes de service doivent être créés par un administrateur vSphere selon les besoins. Cette documentation fournit aux administrateurs des instructions pour attribuer les rôles et les autorisations nécessaires à une gestion efficace des outils ONTAP .

.Serveur VMware vCenter
L'implémentation RBAC dans VMware vCenter Server permet de restreindre l'accès aux objets exposés via l'interface utilisateur du client vSphere. Dans le cadre de l'installation des outils ONTAP pour VMware vSphere 10, l'environnement RBAC est étendu pour inclure des objets supplémentaires représentant les fonctionnalités des outils ONTAP. L'accès à ces objets est fourni via le plug-in distant. Pour plus d'informations, reportez-vous à la section.link:../concepts/rbac-vcenter-environment.html["Environnement RBAC du serveur vCenter"]

.Groupe ONTAP
Les outils ONTAP pour VMware vSphere 10 se connectent à un cluster ONTAP via l'API REST ONTAP pour effectuer des opérations de stockage. L'accès aux ressources de stockage est contrôlé via un rôle ONTAP associé à l'utilisateur ONTAP lors de l'authentification. Voir link:../concepts/rbac-ontap-environment.html["Environnement ONTAP RBAC"] pour plus d'informations.
