---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Les systèmes back-end de stockage sont des systèmes que les hôtes ESXi utilisent pour le stockage des données. 
---
= Ajouter un backend de stockage aux outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez les ONTAP tools for VMware vSphere afin d'ajouter et de gérer les systèmes de stockage pour vos hôtes ESXi.  Vous pouvez intégrer des clusters ou des SVM, activer la prise en charge de MetroCluster et valider les certificats pour une connectivité sécurisée.  Vous pouvez configurer les systèmes de stockage à l'aide ONTAP Tools Manager ou du client vSphere, surveiller l'état des certificats et redécouvrir manuellement les ressources après des modifications du cluster.

Pour ajouter un système de stockage local, utilisez les informations d'identification du cluster ou de la SVM dans l'interface des outils ONTAP .  Les systèmes de stockage local sont disponibles uniquement pour le serveur vCenter sélectionné. Les outils ONTAP mappent les SVM au serveur vCenter pour la gestion des banques de données vVols ou VMFS.  Pour les banques de données VMFS et les flux de travail SRA, vous pouvez utiliser les informations d'identification SVM sans mapper un cluster globalement.

Pour ajouter un système de stockage global, utilisez les informations d'identification du cluster ONTAP dans ONTAP Tools Manager.  Les systèmes de stockage globaux permettent aux flux de travail de découverte d'identifier les ressources du cluster nécessaires à la gestion des vVol.  Dans les environnements mutualisés, vous pouvez ajouter localement un utilisateur SVM pour gérer les banques de données vVols .

Si la prise en charge de MetroCluster est activée dans ONTAP, intégrez les clusters source et de destination en tant que backends de stockage locaux ou globaux.

.Avant de commencer
Vérifiez que le certificat inclut un champ Nom alternatif du sujet (SAN) valide.  Les systèmes ONTAP utilisent le champ SAN pour identifier les LIF de gestion des clusters et des SVM.

[role="tabbed-block"]
====
.Utilisation du Gestionnaire d'outils ONTAP
--

NOTE: Dans une configuration mutualisée, vous pouvez ajouter un cluster back-end de stockage globalement et un SVM localement pour utiliser les identifiants utilisateur de SVM.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *systèmes back-end de stockage* dans la barre latérale.
. Ajoutez le back-end de stockage et fournissez l'adresse IP ou le nom de domaine complet du serveur, le nom d'utilisateur et le mot de passe.
+

NOTE: Les LIF de gestion d'adresses IPv4 et IPv6 sont prises en charge.

. Récupérez automatiquement les certificats du cluster ONTAP et autorisez le certificat, ou téléchargez-le manuellement en accédant à son emplacement.
+

NOTE: Si nécessaire, vous pouvez désactiver la validation du nom alternatif du sujet (SAN) à partir de la console de maintenance. Pour les instructions, voirlink:../manage/change-valid-flag.html["Modifier l'indicateur de validation du certificat"] .

. Si le backend de stockage que vous ajoutez fait partie d'une configuration MetroCluster , ONTAP Tools Manager affiche un message contextuel pour ajouter le cluster appairé.  Sélectionnez *Ajouter* et fournissez les détails du backend de stockage homologue MetroCluster .
+

NOTE: Une fois que le système ONTAP a effectué un basculement et un retour en arrière, exécutez la découverte des outils ONTAP manuellement.



--
.À l'aide de l'interface utilisateur du client vSphere
--

NOTE: Les banques de données vVols ne prennent pas en charge l’ajout direct d’un utilisateur SVM via l’interface utilisateur du client vSphere.

. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Sélectionnez *systèmes back-end de stockage* dans la barre latérale.
. Ajoutez le back-end de stockage et fournissez l'adresse IP du serveur, le nom d'utilisateur, le mot de passe et les détails du port.
+

NOTE: Vous pouvez ajouter un backend de stockage à l'aide d'informations d'identification basées sur un cluster avec des LIF de gestion IPv4 ou IPv6.  Pour ajouter directement un utilisateur SVM, fournissez les informations d'identification basées sur SVM ainsi qu'un LIF de gestion SVM.  Si un cluster est déjà intégré, vous ne pouvez pas intégrer à nouveau un utilisateur SVM à partir de ce cluster.

. Récupérez automatiquement les certificats du cluster ONTAP et autorisez le certificat, ou téléchargez-le manuellement en accédant à son emplacement.
. Si le backend de stockage ajouté fait partie de la configuration MetroCluster , les outils ONTAP affichent l'écran *Ajouter un homologue MetroCluster *.  Sélectionnez *Ajouter un pair* pour ajouter le backend de stockage pair.
+

NOTE: Une fois que le système ONTAP a effectué un basculement et un retour en arrière, exécutez la découverte des outils ONTAP manuellement.



.Et la suite ?
Les outils ONTAP mettent à jour la liste pour afficher le nouveau backend de stockage.

--
====
Les outils ONTAP répertorient le backend de stockage nouvellement ajouté sur la page *Backends de stockage*.  Si un certificat expire dans 30 jours ou moins, les outils ONTAP affichent un avertissement dans la colonne de date d’expiration du certificat.  Après expiration, les outils ONTAP marquent le backend de stockage comme inconnu car il ne peut pas se connecter au système de stockage.

.Informations associées
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["Configuration des clusters dans une configuration MetroCluster"]
