---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords: add vCenter Server, ONTAP tools vCenter registration, multiple vCenter support, vCenter CA certificate 
summary: Ajoutez des instances de serveur vCenter aux ONTAP tools pour configurer, gérer et protéger les banques de données. 
---
= Ajouter des instances vCenter Server aux outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ajoutez des instances de serveur vCenter aux ONTAP tools for VMware vSphere afin de configurer, gérer et protéger les datastores dans votre environnement serveur vCenter. Lorsque vous ajoutez plusieurs instances de serveur vCenter, configurez des certificats CA personnalisés pour une communication sécurisée entre ONTAP tools et chaque serveur vCenter.

.Description de la tâche
Les outils ONTAP s'intègrent à vCenter Server pour effectuer des tâches de stockage telles que le provisionnement, les instantanés et la protection des données directement à partir du client vSphere.

L'ajout d'une instance de serveur vCenter aux outils ONTAP déclenche automatiquement les actions suivantes :

* Les outils ONTAP enregistrent le plug-in client vCenter en tant que plug-in distant.
* ONTAP tools applique des privilèges personnalisés pour les plug-ins et les API à l’instance du serveur vCenter.
* ONTAP tools crée des rôles personnalisés pour gérer les utilisateurs.
* Le plug-in apparaît sous la forme d'un raccourci dans l'interface utilisateur vSphere.


.Avant de commencer
* Assurez-vous que le certificat du serveur vCenter inclut une extension SAN (Subject Alternative Name) valide avec des entrées DNS et d'adresse IP. Par exemple :
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
Si le certificat ne comporte pas d'extension SAN, ou si l'extension SAN ne contient pas les valeurs DNS ou d'adresse IP correctes, les opérations des ONTAP tools peuvent échouer en raison d'erreurs de validation du certificat.

* L'identifiant réseau principal (PNID) du vCenter Server doit figurer dans les détails du SAN. Le PNID et le nom DNS doivent être identiques et résolvables dans le DNS.
* Déployez le serveur vCenter en utilisant son nom de domaine complet (FQDN) et assurez-vous que le SAN dans le certificat inclut DNS Name=machine_FQDN pour une compatibilité et un support optimaux.
* Pour plus d'informations, consultez la documentation VMware :
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html["vSphere Exigences de certification pour les différents chemins de solution"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["Remplacez le certificat SSL de la machine vCenter par un certificat signé par une autorité de certification personnalisée"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["Erreur : Le champ Subject Alternate Name (SAN) ne contient pas le PNID. Veuillez fournir un certificat valide"]




[NOTE]
====
Si le nom de domaine complet (FQDN) n'est pas disponible, vous pouvez définir le PNID sur l'adresse IP et inclure l'adresse IP dans le SAN. Cependant, VMware déconseille cette configuration.

====
.Étapes
. Ouvrez un navigateur Web et accédez à l'URL : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *vCenters* > *Add* pour intégrer les instances de vCenter Server. Indiquez l'adresse IP ou le nom d'hôte, le nom d'utilisateur, le mot de passe et les informations de port de vCenter.
. Dans les options avancées, récupérez automatiquement le certificat vCenter Server (autorisez-le) ou téléchargez-le manuellement.
+

NOTE: Vous n'avez pas besoin d'un compte administrateur pour ajouter des instances vCenter aux ONTAP tools. Vous pouvez créer un rôle personnalisé sans compte administrateur, avec des autorisations limitées. Reportez-vous à link:../concepts/rbac-vcenter-use.html["Utilisez vCenter Server RBAC avec les outils ONTAP pour VMware vSphere 10"] pour plus de détails.


