---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords: associate storage backend, ONTAP tools backend mapping, global storage backend association, vCenter storage backend 
summary: Associez un système de stockage global à une instance de serveur vCenter dans ONTAP tools. 
---
= Associer un back-end de stockage à une instance vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Associez un système de stockage global, ajouté dans ONTAP tools Manager mais pas encore lié à une instance de serveur vCenter spécifique, à une instance de serveur vCenter. Pour les configurations NetApp MetroCluster, associez également le cluster homologue au serveur vCenter.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *vCenter* dans la barre latérale.
. Sélectionnez les points de suspension verticaux à côté de l’instance de serveur vCenter que vous souhaitez connecter aux backends de stockage.
. Dans le menu déroulant, choisissez le backend de stockage que vous souhaitez associer à l’instance vCenter Server sélectionnée.



NOTE: Pour les configurations NetApp MetroCluster, lorsque vous associez un cluster de stockage, associez également son cluster homologue au serveur vCenter.

.Et la suite ?
Les outils ONTAP associent le stockage principal sélectionné à l’instance du serveur vCenter, le rendant disponible pour les opérations de datastore dans cet environnement serveur vCenter.
