---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: 'Si vous n"avez pas configuré l"accès au réseau, toutes les adresses IP découvertes de l"hôte ESXi sont ajoutées à la règle d"export par défaut.' 
---
= Configurer l'accès au réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, toutes les adresses IP détectées depuis l'hôte ESXi sont automatiquement ajoutées à la stratégie d'exportation, sauf si vous configurez l'accès réseau.  Vous pouvez modifier la politique d'exportation pour autoriser l'accès uniquement à partir d'adresses IP spécifiques.  Si un hôte ESXi exclu tente une opération de montage, l'opération échoue.

.Étapes
. Connectez-vous au client vSphere.
. Sélectionnez *NetApp ONTAP Tools* dans la page des raccourcis sous la section des modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Paramètres* > *Gérer l'accès au réseau* > *Modifier*.
+
Pour ajouter plusieurs adresses IP, séparez la liste par des virgules, une plage, un routage CIDR (Classless Inter-Domain Routing) ou une combinaison des trois.

. Sélectionnez *Enregistrer*.

