---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: 'Si vous n"avez pas configuré l"accès au réseau, toutes les adresses IP découvertes de l"hôte ESXi sont ajoutées à la règle d"export par défaut.' 
---
= Configurer l'accès au réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À moins que l’accès au réseau n’ait été configuré, toutes les adresses IP découvertes à partir de l’hôte ESXi sont automatiquement incluses dans la politique d’exportation.  Vous pouvez configurer la stratégie pour autoriser uniquement certaines adresses IP et en exclure d’autres ; toutefois, si vous essayez de monter à partir d’un hôte ESXi exclu, l’opération échouera.

.Étapes
. Connectez-vous au client vSphere.
. Sélectionnez *NetApp ONTAP Tools* dans la page des raccourcis sous la section des modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Paramètres* > *Gérer l'accès au réseau* > *Modifier*.
+
Pour ajouter plusieurs adresses IP, séparez la liste par des virgules, une plage, un routage CIDR (Classless Inter-Domain Routing) ou une combinaison des trois.

. Sélectionnez *Enregistrer*.

