---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords: ESXi multipath settings, HBA timeout settings, ONTAP tools host settings, NetApp storage failover 
summary: 'Configurez les paramètres de multipathing de l"hôte ESXi et de délai d"expiration HBA pour des performances de stockage NetApp optimales.' 
---
= Configurer les paramètres de l'hôte ESXi dans ONTAP tools
:allow-uri-read: 
:firstname: = Configure ESXi host settings in ONTAP tools
:author: = Configure ESXi host settings in ONTAP tools
:authorinitials: =
:authors: = Configure ESXi host settings in ONTAP tools
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration des paramètres de chemin multiple et de délai d'expiration de l'hôte ESXi contribue à garantir la disponibilité des données et l'intégrité des données. Elle permet un basculement automatique vers un chemin de stockage de sauvegarde si le chemin principal devient indisponible.



[[apply-recommended-esxi-host-settings]]
== Appliquer les paramètres d'hôte ESXi recommandés

Les outils ONTAP pour VMware vSphere vérifient et définissent les paramètres des chemins d'accès multiples de l'hôte ESXi ainsi que les paramètres de délai d'expiration de l'adaptateur HBA qui fonctionnent mieux avec les systèmes de stockage NetApp.

.Description de la tâche
Ce processus peut prendre du temps, en fonction de votre configuration et de la charge du système.  Vous pouvez afficher la progression dans le panneau Tâches récentes.

.Étapes
. Sur la page d'accueil du client Web VMware vSphere, sélectionnez *hosts and clusters*.
. Sur la page des raccourcis du client Web VMware vSphere, sélectionnez *NetApp ONTAP Tools* dans la section des plug-ins.
. Accédez à la carte *ESXi Host Compliance* dans la présentation (tableau de bord) du plug-in ONTAP Tools for VMware vSphere.
. Sélectionnez le lien *Appliquer les paramètres recommandés*.
. Dans la fenêtre *Appliquer les paramètres d'hôte recommandés*, sélectionnez les hôtes que vous souhaitez mettre à jour pour utiliser les paramètres recommandés par NetApp et sélectionnez *Suivant*.
+

NOTE: Vous pouvez développer l'hôte ESXi pour voir les valeurs actuelles.

. Dans la page des paramètres, sélectionnez les valeurs recommandées.
. Dans le volet récapitulatif, vérifiez les valeurs et sélectionnez *Terminer*. Vous pouvez suivre la progression dans le panneau des tâches récentes.




[[set-esxi-host-values]]
== Définissez les valeurs de l'hôte ESXi

Utilisez les ONTAP tools for VMware vSphere pour définir des délais d’expiration et d’autres valeurs sur les hôtes ESXi pour des performances et un basculement optimaux.  Il définit ces valeurs en fonction des tests NetApp .

Vous pouvez définir les valeurs suivantes sur un hôte ESXi :



[[hbacna-adapter-settings]]
=== Paramètres de l'adaptateur HBA/CNA

Les outils ONTAP attribuent aux paramètres suivants des valeurs par défaut :

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Délais d'expiration de la carte HBA FC Emulex
* Délais de connexion HBA FC QLogic




[[mpio-settings]]
=== Paramètres MPIO

Les paramètres MPIO sélectionnent et utilisent le meilleur chemin disponible pour les systèmes de stockage NetApp.

Pour les environnements hautes performances ou lors de tests avec une seule banque de données LUN, ajustez le paramètre d'équilibrage de charge de la stratégie de sélection de chemin (PSP) à tour de rôle (VMW_PSP_RR) pour améliorer les performances.  Définissez la valeur IOPS par défaut de 1 000 à 1.


NOTE: Les paramètres MPIO ne s'appliquent pas aux protocoles NVMe, NVMe/FC et NVMe/TCP.



[[nfs-settings]]
=== Paramètres NFS

|===
| Paramètre | Définir cette valeur sur... 


| Net.TcpipeHeapSize | 32 


| Net.TcpipeHeapMax | 1024 MO 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou plus 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===