---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP pour VMware vSphere vérifient et définissent les paramètres de chemins d"accès multiples de l"hôte VMware ESXi et les paramètres de délai de l"adaptateur HBA qui fonctionnent le mieux avec les systèmes de stockage NetApp.' 
---
= Configurer les paramètres de l'hôte ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration des paramètres de délai d’expiration et de multi-chemin du serveur ESXi permet de maintenir la disponibilité et l’intégrité des données.  Il permet le basculement automatique vers un chemin de stockage de sauvegarde si le chemin principal devient indisponible.



== Configurer les paramètres de chemins d'accès multiples et de délai d'attente du serveur ESXi

Les outils ONTAP pour VMware vSphere vérifient et définissent les paramètres des chemins d'accès multiples de l'hôte ESXi ainsi que les paramètres de délai d'expiration de l'adaptateur HBA qui fonctionnent mieux avec les systèmes de stockage NetApp.

.Description de la tâche
Ce processus peut prendre du temps, en fonction de votre configuration et de la charge du système.  Vous pouvez afficher la progression dans le panneau Tâches récentes.

.Étapes
. Sur la page d'accueil du client Web VMware vSphere, sélectionnez *hosts and clusters*.
. Sur la page des raccourcis du client Web VMware vSphere, sélectionnez *NetApp ONTAP Tools* dans la section des plug-ins.
. Accédez à la carte *ESXi Host Compliance* dans la présentation (tableau de bord) du plug-in ONTAP Tools for VMware vSphere.
. Sélectionnez le lien *appliquer les paramètres recommandés*.
. Dans la fenêtre *Appliquer les paramètres d'hôte recommandés*, sélectionnez les hôtes que vous souhaitez mettre à jour pour utiliser les paramètres recommandés par NetApp et sélectionnez *Suivant*.
+

NOTE: Vous pouvez développer l'hôte ESXi pour voir les valeurs actuelles.

. Dans la page des paramètres, sélectionnez les valeurs recommandées.
. Dans le volet récapitulatif, vérifiez les valeurs et sélectionnez *Terminer*. Vous pouvez suivre la progression dans le panneau des tâches récentes.




== Définissez les valeurs de l'hôte ESXi

Utilisez les ONTAP tools for VMware vSphere pour définir des délais d’expiration et d’autres valeurs sur les hôtes ESXi pour des performances et un basculement optimaux.  Il définit ces valeurs en fonction des tests NetApp .

Vous pouvez définir les valeurs suivantes sur un hôte ESXi :



=== Paramètres de l'adaptateur HBA/CNA

Définit les paramètres suivants sur les valeurs par défaut :

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Délais d'expiration de la carte HBA FC Emulex
* Délais de connexion HBA FC QLogic




=== Paramètres MPIO

Les paramètres MPIO sélectionnent les meilleurs chemins pour les systèmes de stockage NetApp .  Les paramètres MPIO sélectionnent le meilleur chemin et l'utilisent.

Pour les environnements hautes performances ou lors de tests avec une seule banque de données LUN, ajustez le paramètre d'équilibrage de charge de la stratégie de sélection de chemin (PSP) à tour de rôle (VMW_PSP_RR) pour améliorer les performances.  Définissez la valeur IOPS par défaut de 1 000 à 1.


NOTE: Les paramètres MPIO ne s'appliquent pas aux protocoles NVMe, NVMe/FC et NVMe/TCP.



=== Paramètres NFS

|===


| Paramètre | Définir cette valeur sur... 


| Net.TcpipeHeapSize | 32 


| Net.TcpipeHeapMax | 1024 MO 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou plus 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===