---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP pour VMware vSphere vérifient et définissent les paramètres de chemins d"accès multiples de l"hôte VMware ESXi et les paramètres de délai de l"adaptateur HBA qui fonctionnent le mieux avec les systèmes de stockage NetApp.' 
---
= Configurer les paramètres de chemins d'accès multiples et de délai d'attente du serveur ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration des paramètres de chemins d'accès multiples et de temporisation du serveur ESXi garantit la haute disponibilité et l'intégrité des données en permettant un basculement transparent vers un chemin de stockage de sauvegarde en cas de défaillance d'un chemin principal.

Les outils ONTAP pour VMware vSphere vérifient et définissent les paramètres des chemins d'accès multiples de l'hôte ESXi ainsi que les paramètres de délai d'expiration de l'adaptateur HBA qui fonctionnent mieux avec les systèmes de stockage NetApp.

*À propos de cette tâche*

Selon votre configuration et la charge du système, ce processus peut prendre un certain temps. La progression de la tâche s'affiche dans le panneau tâches récentes.

.Étapes
. Sur la page d'accueil du client Web VMware vSphere, sélectionnez *hosts and clusters*.
. Cliquez avec le bouton droit de la souris sur un hôte et sélectionnez *NetApp ONTAP Tools* > *Update host data*.
. Sur la page des raccourcis du client Web VMware vSphere, sélectionnez *NetApp ONTAP Tools* dans la section des plug-ins.
. Accédez à la carte *ESXi Host Compliance* dans la présentation (tableau de bord) du plug-in ONTAP Tools for VMware vSphere.
. Sélectionnez le lien *appliquer les paramètres recommandés*.
. Dans la fenêtre *appliquer les paramètres d'hôte recommandés*, sélectionnez les hôtes que vous souhaitez mettre à jour pour qu'ils soient conformes aux paramètres recommandés par NetApp et sélectionnez *Suivant*.
+

NOTE: Vous pouvez développer l'hôte ESXi pour voir les valeurs actuelles.

. Dans la page des paramètres, sélectionnez les valeurs recommandées.
. Dans le volet récapitulatif, vérifiez les valeurs et sélectionnez *Terminer*. Vous pouvez suivre la progression dans le panneau des tâches récentes.

