---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: configure network access, ONTAP export policy, ESXi host IP allowlist, ONTAP tools mount access 
summary: 'Configurez l"accès réseau pour contrôler quelles adresses IP d"hôtes ESXi sont ajoutées aux règles d"export dans ONTAP tools.' 
---
= Configurer l'accès réseau dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, ONTAP tools ajoute automatiquement toutes les adresses IP détectées depuis l’hôte ESXi à la règle d'export, sauf si vous configurez l’accès réseau. Vous pouvez modifier la règle d'export pour autoriser l’accès uniquement à partir d’adresses IP spécifiques ; les opérations de montage échouent pour les hôtes ESXi exclus.

.Étapes
. Connectez-vous au client vSphere.
. Sélectionnez *NetApp ONTAP tools* sur la page des raccourcis, dans la section des plug-ins.
. Dans le volet gauche des outils ONTAP , accédez à *Paramètres* > *Gérer l'accès au réseau* > *Modifier*.
+
Pour ajouter plusieurs adresses IP, séparez la liste par des virgules, des plages, la notation CIDR (Classless Inter-Domain Routing) ou une combinaison des trois.

. Sélectionnez *Enregistrer*.

