---
permalink: configure/create-vvols-datastore.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez créer un datastore vVols avec de nouveaux volumes ou avec des volumes existants. Vous pouvez également créer un datastore vVols en combinant des volumes existants et de nouveaux volumes. 
---
= Créer un datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Selon la destination choisie pour l'action, le datastore est créé et monté sur tous les hôtes de la destination et l'action est activée uniquement si l'utilisateur actuel a le privilège d'exécuter.

L'assistant d'action CREATE datastore prend en charge la création de datastores NFS, VMFS et vVols. L'interface utilisateur est intuitive. Utilisez ces étapes comme instructions.



== Créer un datastore vVols

Vous pouvez créer un datastore vVols avec de nouveaux volumes ou avec des volumes existants. Vous ne pouvez pas créer de datastore vVols avec la combinaison de volumes existants et de nouveaux volumes.


NOTE: Cette option permet de vérifier que les agrégats racine ne sont pas mappés sur un SVM.

.Étapes
. Connectez-vous au client vSphere à l'aide de `\https://vcenterip/ui`
. Cliquez avec le bouton droit de la souris sur un système hôte, un cluster hôte ou un centre de données, puis sélectionnez *NetApp ONTAP Tools* > *Create datastore*
. Dans le volet *Type*, sélectionnez vVols dans *Type de datastore*.
+

NOTE: Vous obtenez l'option vVols uniquement si le fournisseur VASA est enregistré avec le vCenter sélectionné.

. Dans le volet *Nom et Protocole*, indiquez *nom du datastore* et *Protocole*.
. Dans le volet *Storage*, sélectionnez *Platform* et *Storage VM*. Dans la section *Options avancées*, en fonction de votre choix, sélectionnez une règle d'export personnalisée (pour le protocole NFS) ou un nom de groupe initiateur personnalisé (pour le protocole iSCSI).
+
** Les options de plateforme et asymétriques vous aident à filtrer les options déroulantes des SVM. On doit sélectionner la SVM pour créer ou utiliser le ou les volume(s) pour créer les datastores.
** *Le bouton bascule asymétrique* n'est visible que si iSCSI a été sélectionné à l'étape précédente et si les performances ou la capacité sont sélectionnées dans la liste déroulante plate-forme.
** Le protocole asymétrique est vrai pour la plateforme AFF et faux pour la plateforme ASA.


. Dans le volet *attributs de stockage*, vous pouvez créer de nouveaux volumes ou utiliser les volumes existants. Lors de la création d'un volume, vous pouvez activer la QoS sur le datastore.
. Vérifiez votre sélection dans le volet *Résumé* et cliquez sur *Terminer*.
Un datastore est créé et monté sur tous les hôtes.




== Créer un datastore NFS

Le datastore VMware Network File System (NFS) est un type de stockage qui utilise le protocole NFS pour connecter les hôtes ESXi à un périphérique de stockage partagé sur un réseau. Les datastores NFS sont généralement utilisés dans les environnements VMware vSphere et offrent plusieurs avantages, tels que la simplicité et la flexibilité.

.Étapes
. Connectez-vous au client vSphere à l'aide de `\https://vcenterip/ui`
. Cliquez avec le bouton droit de la souris sur un système hôte, un cluster hôte ou un centre de données, puis sélectionnez *NetApp ONTAP Tools* > *Create datastore*
. Dans le volet *Type*, sélectionnez NFS dans *Type de datastore*.
. Dans le volet *Nom et protocole*, entrez le nom, la taille et les informations de protocole du datastore. Dans les options avancées, sélectionnez *datastore cluster* et authentification Kerberos.
+

NOTE: L'authentification Kerberos est disponible uniquement lorsque le protocole NFS 4.1 est sélectionné.

. Dans le volet *Storage*, sélectionnez *Platform* et *Storage VM*. Vous pouvez sélectionner *Custom Export Policy* dans la section *Advanced option*.
+
** *Le bouton bascule asymétrique* n'est visible que si la performance ou la capacité est sélectionnée dans la liste déroulante plate-forme.
** *Toute option* dans le menu déroulant de la plate-forme vous permet de voir tous les SVM faisant partie de vCenter indépendamment de la plate-forme ou de l'indicateur asymétrique.


. Dans le volet *attributs de stockage*, sélectionnez l'agrégat pour la création du volume. Dans les options avancées, choisissez *Réserve d'espace* et *Activer QoS* selon les besoins.
. Vérifiez les sélections dans le volet *Résumé* et cliquez sur *Terminer*.


Un datastore est créé et monté sur tous les hôtes.



== Créer un datastore VMFS

VMFS (Virtual machine File System) est un système de fichiers en cluster spécialement conçu pour le stockage de fichiers de machines virtuelles dans des environnements VMware vSphere. Elle permet à plusieurs hôtes ESXi d'accéder simultanément aux mêmes fichiers de machine virtuelle, ce qui permet d'utiliser des fonctionnalités telles que vMotion et haute disponibilité.

*Avant de commencer*

Vérifier les éléments suivants avant de continuer :

* Vérifiez que tous les hôtes cibles sont en bon état et que l'hôte prend en charge le protocole.
* Créer un nouveau volume (taille min. 2 Go)
* Définissez les options de volume avec QoS
* Créer une LUN de type VMware
* Get initiators for all target hosts
* Créez/réutilisez un groupe initiateur en fonction d'initiateurs correspondants
* Mapper la LUN sur le groupe initiateur
* Ajoutez des cibles iSCSI aux hôtes ESXi
* Relancez l'analyse des adaptateurs de bus hôte (HBA) sur tous les hôtes
* Montage du volume en tant que datastore VMFS6 (pour plus de 6.5 hôtes)
* Relancez l'analyse du stockage VMFS sur les hôtes ESXi
* Déplacez le datastore vers le cluster datastore
* Rééquilibrer les chemins iSCSI


.Étapes
. Connectez-vous au client vSphere à l'aide de `\https://vcenterip/ui`
. Cliquez avec le bouton droit de la souris sur un système hôte, un cluster hôte ou un datastore, puis sélectionnez *NetApp ONTAP Tools* > *Create datastore*
. Dans le volet *Type*, sélectionnez VMFS dans *Type de datastore*.
. Dans le volet *Nom et Protocole*, entrez le nom, la taille et les informations de protocole du datastore. Dans la section *Options avancées* du volet, sélectionnez le cluster de datastore auquel vous souhaitez ajouter ce datastore.
. Sélectionnez plate-forme et VM de stockage dans le volet stockage. Sélectionnez le bouton à bascule asymétrique. Indiquez le *Nom du groupe initiateur* personnalisé dans la section *Options avancées* du volet (facultatif). Vous pouvez choisir un groupe initiateur existant pour le datastore ou créer un nouveau groupe initiateur avec un nom personnalisé.
+
Si vous choisissez l'option *any* dans le menu déroulant de la plateforme, vous pouvez voir tous les SVM faisant partie de vCenter indépendamment de la plate-forme ou de l'indicateur asymétrique.

. Dans le volet Storage Attributes, sélectionnez *aggregate* dans la liste déroulante. Sélectionnez *Réserve d'espace*, *utiliser le volume existant* et *Activer QoS* selon les besoins dans la section *Options avancées* et fournissez les détails nécessaires.
. Consultez les détails du datastore dans le volet *Summary* et cliquez sur *Finish*.
Un datastore est créé et monté sur tous les hôtes.

