---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords: create datastore, ONTAP tools NFS VMFS vVols, host cluster datastore provisioning, nconnect datastore settings 
summary: 'Créez des datastores NFS, VMFS ou vVols dans ONTAP tools au niveau de l"hôte ou du cluster d"hôtes.' 
---
= Créer un datastore dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez une banque de données au niveau du cluster hôte, les outils ONTAP la montent sur tous les hôtes de destination et activent l'action uniquement si vous disposez des privilèges requis.

*Interopérabilité entre les banques de données natives avec les banques de données gérées par vCenter Server et les outils ONTAP*

À partir des ONTAP tools for VMware vSphere 10.4, les outils ONTAP créent des igroups imbriqués pour les banques de données, avec des igroups parents spécifiques aux banques de données et des igroups enfants mappés aux hôtes.  Vous pouvez créer des groupes i plats à partir d' ONTAP System Manager et les utiliser pour créer des banques de données VMFS sans utiliser les outils ONTAP . Se référer à https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Gérer les initiateurs et les groupes SAN"] pour plus d'informations.

Une fois que vous avez intégré le stockage et exécuté la découverte de la banque de données, les outils ONTAP modifient les groupes i plats dans les banques de données VMFS en groupes i imbriqués.  Vous ne pouvez pas utiliser d'anciens groupes i plats pour créer de nouveaux magasins de données.  Utilisez l’interface des outils ONTAP ou l’API REST pour réutiliser les igroups imbriqués.

[role="tabbed-block"]
====
.Créer un datastore vVols
--
À partir de ONTAP tools for VMware vSphere 10.3, vous pouvez créer un datastore vVols sur les systèmes ASA r2 avec une efficacité d'espace fine. Le fournisseur VASA crée un conteneur et les points de terminaison de protocole souhaités lors de la création du datastore vVol. Le fournisseur VASA n'attribue aucun volume de support à ce conteneur.

.Avant de commencer
* Assurez-vous que les agrégats racines ne sont pas mappés sur la SVM.
* Assurez-vous que le fournisseur VASA est enregistré avec le vCenter sélectionné.
* Pour les systèmes de stockage ASA r2, le mappage SVM-agrégat n'est pas requis.


.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez vVols comme *type de magasin de données*.
. Entrez les informations *nom du datastore* et *Protocole*.
+

NOTE: Le système ASA r2 prend en charge les protocoles iSCSI et FC pour les vVols.

. Sélectionnez la VM de stockage où vous souhaitez créer le datastore.
. Sous *Options avancées* :
+
** Si vous sélectionnez la *règles d'export* personnalisée, exécutez la découverte dans vCenter pour tous les objets avant de continuer. Il est déconseillé d'utiliser cette option.
** Vous pouvez sélectionner un nom de *groupe d'initiateurs personnalisé* pour les protocoles iSCSI et FC.
+

NOTE: Pour un ASA r2 SVM, les unités de stockage (LUN/espaces de noms) ne sont pas créées car la datastore n'est qu'un conteneur logique.



. Dans le volet *attributs de stockage*, vous pouvez créer de nouveaux volumes ou utiliser les volumes existants. Toutefois, vous ne pouvez pas combiner ces deux types de volumes pour créer un datastore vVols.
+
Lors de la création d'un volume, vous pouvez activer la QoS sur la banque de données. Par défaut, un volume est créé pour chaque demande de création de LUN. Ignorez cette étape pour les banques de données vVols sur les systèmes de stockage ASA r2.

. Vérifiez votre sélection dans le volet *Résumé* et sélectionnez *Terminer*.


--
.Créer un datastore NFS
--
Un datastore NFS connecte les hôtes ESXi à un stockage partagé via le protocole NFS. Il est simple et flexible et est utilisé dans les environnements VMware vSphere.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez NFS dans le champ *type de datastore*.
. Saisissez le nom, la taille et les informations de protocole de la banque de données dans le volet *Nom et protocole*.
+
.. Sélectionnez *Cluster de banque de données* et *Authentification Kerberos* dans les *Options avancées*.
+

NOTE: L'authentification Kerberos n'est disponible que lorsque le protocole NFS 4.1 est sélectionné.

.. Spécifiez le *nombre de connexions (nconnect)* pour le datastore. La valeur par défaut est 4, configurable de 1 à 8. Si la valeur que vous sélectionnez est supérieure au paramètre nconnect actuel au niveau de l'hôte, ONTAP tools met à jour le paramètre nconnect au niveau de l'hôte pour qu'il corresponde.


. Dans le volet *Stockage*, sélectionnez *Plateforme* et *Storage VM*.
. Si vous sélectionnez *Custom export policy* dans les *Options avancées*, exécutez la découverte dans vCenter pour tous les objets avant de continuer.
+

NOTE: Vous ne pouvez pas créer une banque de données NFS à l'aide de la stratégie de volume racine ou par défaut de la SVM.

+
** Dans les *Options avancées*, le bouton *Asymétrique* n'est visible que si *Performances* ou *Capacité* est sélectionné dans le menu déroulant de la plateforme. Cependant, l'option *Asymétrique* ne s'applique pas à la création de datastore NFS.
** Lorsque vous sélectionnez l'option *Tout* dans le menu déroulant de la plateforme, toutes les SVM dans le vCenter sont visibles. Les paramètres de plateforme et d'asymétrie n'ont aucune incidence sur la visibilité.


. Dans le volet *Attributs de stockage*, sélectionnez l'agrégat pour la création du volume. Dans les *Options avancées*, choisissez *Réserve d'espace* et *Activer la QoS* selon vos besoins.
. Dans le volet *Résumé*, vérifiez les sélections et sélectionnez *Terminer*.


Les outils ONTAP créent le magasin de données NFS et le montent sur tous les hôtes.

--
.Créer un datastore VMFS
--
VMFS est un système de fichiers en cluster pour stocker les fichiers de machines virtuelles.  Plusieurs hôtes ESXi peuvent accéder simultanément aux mêmes fichiers VM pour les fonctionnalités vMotion et haute disponibilité.

.Avant de commencer
* Activez les services et les LIF pour chaque protocole côté stockage ONTAP.
* Pour les systèmes de stockage ASA r2, le mappage SVM-agrégat n'est pas requis.
* Configurez l'hôte ESXi si vous utilisez le protocole NVMe/TCP :
+
.. Examinez le https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guide de compatibilité VMware"]
+

NOTE: VMware vSphere 7.0 U3 et versions ultérieures prennent en charge le protocole NVMe/TCP. Toutefois, VMware vSphere 8.0 et versions ultérieures sont recommandés.

.. Vérifiez si le fournisseur de la carte d'interface réseau (NIC) prend en charge les NIC ESXi avec le protocole NVMe/TCP.
.. Configurez la carte réseau ESXi pour NVMe/TCP conformément aux spécifications du fournisseur de la carte réseau.
.. Si vous utilisez VMware vSphere 7, suivez les instructions qui s'affichent sur le site VMware https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Configurez la liaison VMkernel pour l'adaptateur NVMe over TCP"] pour configurer la liaison du port NVMe/TCP. Si vous utilisez VMware vSphere 8, suivez https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Configuration de NVMe over TCP sur ESXi"]la procédure pour configurer la liaison du port NVMe/TCP.
.. Pour VMware vSphere 7, suivez les instructions à la page https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Activez NVMe over RDMA ou les adaptateurs logiciels NVMe over TCP"] pour configurer les adaptateurs logiciels NVMe/TCP. Pour la version VMware vSphere 8, reportez-vous à la section https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Ajout de NVMe over RDMA Software ou de NVMe over TCP Adapters"] pour configurer les adaptateurs logiciels NVMe/TCP.
.. Exécutez l’action link:../configure/discover-storage-systems-and-hosts.html["Découverte des systèmes et des hôtes de stockage"] sur l’hôte ESXi. Pour plus d’informations, consultez  https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Comment configurer NVMe/TCP avec vSphere 8.0 Update 1 et ONTAP 9.13.1 pour les datastores VMFS"].


* Si vous utilisez le protocole NVMe/FC, procédez comme suit pour configurer l'hôte ESXi :
+
.. Si ce n'est pas déjà fait, activez NVMe over Fabrics (NVMe-oF) sur votre ou vos hôtes ESXi.
.. Segmentation SCSI complète.
.. Assurez-vous que les hôtes ESXi et le système ONTAP sont connectés au niveau d'une couche physique et logique.




Pour configurer un SVM ONTAP pour le protocole FC, reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Configuration d'un SVM pour FC"]la .

Pour plus d'informations sur l'utilisation du protocole NVMe/FC avec VMware vSphere 8.0, reportez-vous à https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuration d'hôte NVMe-of pour ESXi 8.x avec ONTAP"]la .

Pour plus d'informations sur l'utilisation de NVMe/FC avec VMware vSphere 7.0, reportez-vous à  https://docs.netapp.com/us-en/ontap-sanhost/nvme-esxi-7.html["Guide de configuration d'hôte NVMe/FC de ONTAP"].

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez le type de banque de données VMFS.
. Saisissez le nom, la taille et les informations de protocole de la banque de données dans le volet *Nom et protocole*. Pour ajouter la nouvelle banque de données à un cluster VMFS existant, sélectionnez le cluster de banques de données dans *Options avancées*.
. Sélectionnez la machine virtuelle de stockage dans le volet *Stockage*. Indiquez le *Nom du groupe d'initiateurs personnalisé* dans la section *Options avancées* si nécessaire. Vous pouvez choisir un igroup existant pour la datastore ou en créer un nouveau avec un nom personnalisé.
+
Lorsque le protocole NVMe/FC ou NVMe/TCP est sélectionné, un nouveau sous-système d'espace de noms est créé et utilisé pour le mappage des espaces de noms. ONTAP tools crée le sous-système d'espace de noms en utilisant un nom généré automatiquement qui inclut le nom de la datastore. Vous pouvez renommer le sous-système d'espace de noms dans le champ *custom namespace subsystem name* des *Advanced options* du volet *Storage*.

. Dans le volet *Attributs de stockage* :
+
.. Sélectionnez *aggregate* dans les options de la liste déroulante.
+

NOTE: Pour les systèmes de stockage ASA r2, l'option *Aggregate* n'est pas affichée car le stockage est désagrégé. Lorsque vous choisissez un système de stockage ASA r2 de type SVM, la page *Attributs de stockage* affiche des options pour activer la QoS.

.. Les outils ONTAP créent une unité de stockage (LUN/Namespace) avec une réserve d'espace mince en fonction du protocole sélectionné.
+

NOTE: À partir de ONTAP 9.16.1, les systèmes de stockage ASA r2 prennent en charge jusqu'à 12 nœuds par cluster.

.. Sélectionnez le niveau de service *Performance* pour un système de stockage ASA r2 avec une SVM à 12 nœuds dans un cluster hétérogène. Cette option n'est pas disponible si la SVM sélectionnée est un cluster homogène ou utilise un utilisateur SVM.
+
'Any' est la valeur par défaut du niveau de service de performance (PSL). Ce paramètre crée l'unité de stockage à l'aide de l'algorithme de placement équilibré ONTAP. Toutefois, vous pouvez sélectionner l'option performance ou Extreme selon vos besoins.

.. Sélectionnez *utiliser le volume existant*, *Activer les options QoS* selon les besoins et fournissez les détails.
+

NOTE: Dans le type de stockage ASA r2, la création ou la sélection de volumes ne s'applique pas à la création d'unités de stockage (LUN/Namespace). Par conséquent, ces options ne sont pas affichées.

+

NOTE: Vous ne pouvez pas utiliser le volume existant pour créer une banque de données VMFS avec le protocole NVMe/FC ou NVMe/TCP.  Créez un nouveau volume pour la banque de données VMFS.



. Dans la fenêtre *Protection*, sélectionnez *Protéger cette banque de données à l'aide de la réplication SnapMirror* pour activer la protection. Vous pouvez ajouter la banque de données à un groupe de protection existant ou en créer un nouveau. Pour créer un nouveau groupe de protection :
+
.. Saisissez un *nom de groupe de protection*.
.. Configurez la relation SnapMirror. Si vous sélectionnez la stratégie Automated Failover Duplex (AFD), configurez les paramètres de configuration du cluster d'hôtes avant de continuer. Pour plus de détails, consultez link:../protect/config-proximity.html["Configurer le cluster pour la protection du datastore avec les outils ONTAP"].
+

NOTE: Si le volume sélectionné fait déjà partie d'une autre configuration de protection, la page de protection suivante est désactivée et un message d'information s'affiche. Si la banque de données n'est pas éligible à la protection, l'option de protection est désactivée et le motif d'inéligibilité est affiché. Vous pouvez néanmoins créer la banque de données sans protection.



. Vérifiez les détails du datastore dans le volet *Summary* et sélectionnez *Finish*.
+

NOTE: Si une banque de données est protégée, les ONTAP tools la montent sur tous les hôtes du cluster.



.Résultat
Les outils ONTAP créent le magasin de données VMFS et le montent sur tous les hôtes.

--
====