---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: 'Lorsque vous créez une banque de données au niveau du cluster hôte, les outils ONTAP la montent sur tous les hôtes de destination et activent l"action uniquement si vous disposez des privilèges requis.' 
---
= Créer un datastore dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez une banque de données au niveau du cluster hôte, les outils ONTAP la montent sur tous les hôtes de destination et activent l'action uniquement si vous disposez des privilèges requis.

*Interopérabilité entre les banques de données natives avec les banques de données gérées par vCenter Server et les outils ONTAP*

À partir des ONTAP tools for VMware vSphere 10.4, les outils ONTAP créent des igroups imbriqués pour les banques de données, avec des igroups parents spécifiques aux banques de données et des igroups enfants mappés aux hôtes.  Vous pouvez créer des groupes i plats à partir d' ONTAP System Manager et les utiliser pour créer des banques de données VMFS sans utiliser les outils ONTAP . Se référer à https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Gérer les initiateurs et les groupes SAN"] pour plus d'informations.

Une fois que vous avez intégré le stockage et exécuté la découverte de la banque de données, les outils ONTAP modifient les groupes i plats dans les banques de données VMFS en groupes i imbriqués.  Vous ne pouvez pas utiliser d'anciens groupes i plats pour créer de nouveaux magasins de données.  Utilisez l’interface des outils ONTAP ou l’API REST pour réutiliser les igroups imbriqués.

[role="tabbed-block"]
====
.Créer un datastore vVols
--
À partir des ONTAP tools for VMware vSphere 10.3, vous pouvez créer une banque de données vVols sur des systèmes ASA r2 avec une efficacité spatiale telle que thin.vVol.  Le fournisseur VASA crée un conteneur et les points de terminaison de protocole souhaités lors de la création de la banque de données vVol.  Le fournisseur VASA n'attribue aucun volume de sauvegarde à ce conteneur.

.Avant de commencer
* Assurez-vous que les agrégats racines ne sont pas mappés à SVM.
* Assurez-vous que le fournisseur VASA est enregistré avec le vCenter sélectionné.
* Dans le système de stockage ASA r2, le SVM doit être mappé à l'agrégat pour l'utilisateur SVM.


.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez vVols *type de datastore*.
. Entrez les informations *nom du datastore* et *Protocole*.
+

NOTE: Le système ASA r2 prend en charge les protocoles iSCSI et FC pour les vVols.

. Sélectionnez la VM de stockage où vous souhaitez créer le datastore.
. Sous Options avancées :
+
** Si vous sélectionnez la *politique d’exportation personnalisée*, assurez-vous d’exécuter la découverte dans vCenter pour tous les objets.  Il est recommandé de ne pas utiliser cette option.
** Vous pouvez sélectionner *Nom du groupe initiateur* personnalisé pour les protocoles iSCSI et FC.
+

NOTE: Dans le type de système de stockage ASA r2 SVM, les unités de stockage (LUN/espace de noms) ne sont pas créées car la banque de données n'est qu'un conteneur logique.



. Dans le volet *attributs de stockage*, vous pouvez créer de nouveaux volumes ou utiliser les volumes existants. Toutefois, vous ne pouvez pas combiner ces deux types de volumes pour créer un datastore vVols.
+
Lors de la création d'un nouveau volume, vous pouvez activer la QoS sur la banque de données.  Par défaut, un volume est créé pour chaque demande de création de LUN.  Ignorez cette étape pour les banques de données vVols sur les systèmes de stockage ASA r2.

. Vérifiez votre sélection dans le volet *Résumé* et sélectionnez *Terminer*.


--
.Créer un datastore NFS
--
Une banque de données NFS connecte les hôtes ESXi au stockage partagé à l’aide du protocole NFS.  Ils sont simples et flexibles et sont utilisés dans les environnements VMware vSphere.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez NFS dans le champ *type de datastore*.
. Entrez le nom, la taille et les informations de protocole du datastore dans le volet *Nom et protocole*. Sélectionnez *datastore cluster* et *Kerberos Authentication* dans les options avancées.
+

NOTE: L'authentification Kerberos n'est disponible que lorsque le protocole NFS 4.1 est sélectionné.

. Sélectionnez *Platform* et *Storage VM* dans le volet *Storage*.
. Si vous sélectionnez *Politique d’exportation personnalisée* sous les options avancées, exécutez la découverte dans vCenter pour tous les objets.  Il est recommandé de ne pas utiliser cette option.
+

NOTE: Vous ne pouvez pas créer une banque de données NFS à l'aide de la stratégie de volume racine ou par défaut de la SVM.

+
** Dans les options avancées, le bouton bascule *asymétrique* n'est visible que si la performance ou la capacité est sélectionnée dans la liste déroulante plate-forme.
** Lorsque vous choisissez l’option *Tout* dans la liste déroulante de la plate-forme, vous pouvez voir tous les SVM dans vCenter.  La plate-forme et le drapeau asymétrique n'affectent pas la visibilité.


. Sélectionnez l'agrégat pour la création du volume dans le volet *Storage Attributes*. Dans les options avancées, choisissez *Réserve d'espace* et *Activer QoS* selon les besoins.
. Vérifiez les sélections dans le volet *Résumé* et sélectionnez *Terminer*.


Les outils ONTAP créent le magasin de données NFS et le montent sur tous les hôtes.

--
.Créer un datastore VMFS
--
VMFS est un système de fichiers en cluster pour stocker les fichiers de machines virtuelles.  Plusieurs hôtes ESXi peuvent accéder simultanément aux mêmes fichiers VM pour les fonctionnalités vMotion et haute disponibilité.

Sur un cluster protégé :

* Vous ne pouvez créer que des banques de données VMFS.  L'ajout d'une banque de données VMFS à un cluster protégé le protège automatiquement.
* Vous ne pouvez pas créer de datastore sur un data Center avec un ou plusieurs clusters hôtes protégés.
* Vous ne pouvez pas créer de banque de données sur un hôte ESXi si le cluster d'hôte parent est protégé par une « stratégie de duplex de basculement automatisé » (configuration uniforme ou non uniforme).
* Vous pouvez créer un datastore VMFS uniquement sur un hôte ESXi protégé par une relation asynchrone. Vous ne pouvez pas créer et monter un datastore sur un hôte ESXi faisant partie d'un cluster hôte protégé par la règle « Automated Failover Duplex ».


.Avant de commencer
* Activez les services et les LIF pour chaque protocole côté stockage ONTAP.
* Mapper SVM à l'agrégat pour l'utilisateur SVM dans le système de stockage ASA r2
* Configurez l'hôte ESXi si vous utilisez le protocole NVMe/TCP :
+
.. Examinez le https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guide de compatibilité VMware"]
+

NOTE: VMware vSphere 7.0 U3 et versions ultérieures prennent en charge le protocole NVMe/TCP. Toutefois, VMware vSphere 8.0 et versions ultérieures sont recommandés.

.. Vérifiez si le fournisseur de la carte d’interface réseau (NIC) prend en charge la carte réseau ESXi avec le protocole NVMe/TCP.
.. Configurez la carte réseau ESXi pour NVMe/TCP conformément aux spécifications du fournisseur de la carte réseau.
.. Si vous utilisez VMware vSphere 7, suivez les instructions qui s'affichent sur le site VMware https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Configurez la liaison VMkernel pour l'adaptateur NVMe over TCP"] pour configurer la liaison du port NVMe/TCP. Si vous utilisez VMware vSphere 8, suivez https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Configuration de NVMe over TCP sur ESXi"]la procédure pour configurer la liaison du port NVMe/TCP.
.. Pour VMware vSphere 7, suivez les instructions à la page https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Activez NVMe over RDMA ou les adaptateurs logiciels NVMe over TCP"] pour configurer les adaptateurs logiciels NVMe/TCP. Pour la version VMware vSphere 8, reportez-vous à la section https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Ajout de NVMe over RDMA Software ou de NVMe over TCP Adapters"] pour configurer les adaptateurs logiciels NVMe/TCP.
.. Exécutez link:../configure/discover-storage-systems-and-hosts.html["Découverte des systèmes et des hôtes de stockage"] l'action sur l'hôte ESXi. Pour plus d'informations, reportez-vous https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Comment configurer NVMe/TCP avec vSphere 8.0 Update 1 et ONTAP 9.13.1 pour les datastores VMFS"]à .


* Si vous utilisez le protocole NVME/FC, procédez comme suit pour configurer l'hôte ESXi :
+
.. Si ce n'est pas déjà fait, activez NVMe over Fabrics (NVMe-of) sur vos hôtes ESXi.
.. Segmentation SCSI complète.
.. Assurez-vous que les hôtes ESXi et le système ONTAP sont connectés au niveau d'une couche physique et logique.




Pour configurer un SVM ONTAP pour le protocole FC, reportez-vous à https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Configuration d'un SVM pour FC"]la .

Pour plus d'informations sur l'utilisation du protocole NVMe/FC avec VMware vSphere 8.0, reportez-vous à https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuration d'hôte NVMe-of pour ESXi 8.x avec ONTAP"]la .

Pour plus d'informations sur l'utilisation de NVMe/FC avec VMware vSphere 7.0, reportez-vous aux sections https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Guide de configuration d'hôte NVMe/FC de ONTAP"] et http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"].

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Créer une banque de données *.
. Sélectionnez le type de datastore VMFS.
. Saisissez le nom, la taille et les informations de protocole du magasin de données dans le volet *Nom et protocole*.  Pour ajouter le nouveau magasin de données à un cluster VMFS existant, sélectionnez le cluster de magasin de données dans les Options avancées.
. Sélectionnez Storage VM dans le volet *Storage*. Indiquez le *Nom du groupe d'initiateurs personnalisé* dans la section *Options avancées*, si nécessaire. Vous pouvez choisir un groupe initiateur existant pour le datastore ou créer un nouveau groupe initiateur avec un nom personnalisé.
+
Lorsque le protocole NVMe/FC ou NVMe/TCP est sélectionné, un nouveau sous-système d'espace de noms est créé et utilisé pour le mappage d'espace de noms.  Les outils ONTAP créent le sous-système d’espace de noms à l’aide du nom généré automatiquement qui inclut le nom de la banque de données.  Vous pouvez renommer le sous-système d'espace de noms dans le champ *nom du sous-système d'espace de noms personnalisé* dans les options avancées du volet *Stockage*.

. Dans le volet *Storage Attributes* :
+
.. Sélectionnez *aggregate* dans les options de la liste déroulante.
+

NOTE: Pour les systèmes de stockage ASA r2, l'option *Aggregate* n'est pas affichée car le stockage est désagrégé. Lorsque vous choisissez un système de stockage ASA r2 de type SVM, la page des attributs de stockage affiche les options d'activation de la qualité de service.

.. Les outils ONTAP créent une unité de stockage (LUN/Namespace) avec une réserve d'espace mince en fonction du protocole sélectionné.
+

NOTE: À partir de ONTAP 9.16.1, les systèmes de stockage ASA r2 prennent en charge jusqu'à 12 nœuds par cluster.

.. Sélectionner le *niveau de service Performance* pour les systèmes de stockage ASA r2 avec un SVM à 12 nœuds qui est un cluster hétérogène. Cette option n'est pas disponible si le SVM sélectionné est un cluster homogène ou utilise un utilisateur SVM.
+
'Any' est la valeur par défaut du niveau de service de performance (PSL). Ce paramètre crée l'unité de stockage à l'aide de l'algorithme de placement équilibré ONTAP. Toutefois, vous pouvez sélectionner l'option performance ou Extreme selon vos besoins.

.. Sélectionnez *utiliser le volume existant*, *Activer les options QoS* selon les besoins et fournissez les détails.
+

NOTE: Dans le type de stockage ASA r2, la création ou la sélection de volume ne s'applique pas à la création d'unité de stockage (LUN/espace de noms).  Par conséquent, ces options ne sont pas affichées.

+

NOTE: Vous ne pouvez pas utiliser le volume existant pour créer une banque de données VMFS avec le protocole NVMe/FC ou NVMe/TCP.  Créez un nouveau volume pour la banque de données VMFS.



. Vérifiez les détails du datastore dans le volet *Summary* et sélectionnez *Finish*.



NOTE: Si vous créez le datastore sur un cluster protégé, un message en lecture seule s'affiche : « le datastore est en cours de montage sur un cluster protégé ».

.Résultat
Les outils ONTAP créent le magasin de données VMFS et le montent sur tous les hôtes.

--
====