---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Lors de la première exécution des outils ONTAP pour VMware vSphere dans un client vSphere, les outils ONTAP pour VMware vSphere permettent de détecter les hôtes ESXi, leurs LUN et leurs exportations NFS, ainsi que les systèmes de stockage NetApp qui possèdent ces LUN et ces exportations. 
---
= Découvrez les systèmes de stockage et les hôtes dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors du premier lancement ONTAP tools for VMware vSphere dans le client vSphere, celui-ci détecte automatiquement les hôtes ESXi, leurs LUN et exportations NFS associés, ainsi que les systèmes de stockage NetApp qui possèdent ces ressources.

.Avant de commencer
* Assurez-vous que tous les hôtes ESXi sont allumés et connectés.
* Assurez-vous que toutes les machines virtuelles de stockage (SVM) à découvrir sont en cours d'exécution et que chaque nœud du cluster dispose d'au moins une interface logique de données (LIF) configurée pour le protocole de stockage utilisé (NFS ou iSCSI).


.Description de la tâche
Vous pouvez découvrir de nouveaux systèmes de stockage ou mettre à jour ceux existants pour obtenir les dernières informations sur leur capacité et leur configuration.  Vous pouvez également modifier les ONTAP tools for VMware vSphere afin d'accéder au système de stockage.

Lors de la découverte des systèmes de stockage, les outils ONTAP pour VMware vSphere collectent des informations à partir des hôtes ESXi gérés par l'instance vCenter Server.

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Cliquez avec le bouton droit sur le centre de données requis et sélectionnez * Outils NetApp ONTAP * > * Mettre à jour les données de l'hôte * .
+
Dans la boîte de dialogue *confirmer*, confirmez votre choix.

. Sélectionnez les contrôleurs de stockage détectés qui ont l'état `Authentication Failure` et sélectionnez *actions* > *Modifier*.
. Renseignez les informations requises dans la boîte de dialogue *Modifier le système de stockage*.
. Répétez les étapes 4 et 5 pour tous les contrôleurs de stockage avec `Authentication Failure` état.


Une fois le processus de détection terminé, effectuez les actions suivantes :

* Utilisez les outils ONTAP pour VMware vSphere pour configurer les paramètres de l'hôte VMware ESXi pour les hôtes qui affichent l'icône d'alerte dans la colonne des paramètres de l'adaptateur, dans la colonne des paramètres MPIO ou dans la colonne des paramètres NFS.
* Indiquez les informations d'identification du système de stockage.

