---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez définir des délais d"expiration et d"autres valeurs sur les hôtes ESXi à l"aide des outils ONTAP pour VMware vSphere afin de garantir des performances optimales et un basculement réussi. Les outils ONTAP pour les ensembles VMware vSphere sont basés sur des tests NetApp internes.' 
---
= Définissez les valeurs de l'hôte ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À l'aide des outils ONTAP pour VMware vSphere, vous pouvez définir des délais d'expiration et d'autres valeurs sur les hôtes VMware ESXi afin de garantir des performances optimales et un basculement réussi. Les outils ONTAP pour les ensembles VMware vSphere sont basés sur des tests NetApp internes.

Vous pouvez définir les valeurs suivantes sur un hôte ESXi :



== Paramètres de l'adaptateur HBA/CNA

Définit les paramètres de délai d'expiration de HBA recommandés pour les systèmes de stockage NetApp.

|===
| Paramètres | Définir cette valeur sur... 


| Disk.QFullSampleSize | 32 pour toutes les configurations. La définition de cette valeur permet d'éviter les erreurs d'E/S. 


| Disk.QFullThreshold | 8 pour toutes les configurations. La définition de cette valeur permet d'éviter les erreurs d'E/S. 


| Délais d'expiration de la carte HBA FC Emulex | Valeur par défaut. 


| Délais de connexion HBA FC QLogic | Valeur par défaut. 
|===


== Paramètres MPIO

Les paramètres MPIO définissent les chemins de prédilection pour les systèmes de stockage NetApp. Ils déterminent quels chemins disponibles sont optimisés (par opposition aux chemins non optimisés qui traversent le câble d'interconnexion) et définissent le chemin préféré sur l'un de ces chemins.

Dans les environnements hautes performances, ou lorsque vous testez les performances avec un seul datastore LUN, pensez à modifier le paramètre d'équilibrage de charge de la règle de sélection de chemin (PSP) de Round Robin (VMW_PSP_RR) du paramètre d'IOPS par défaut de 1000 à une valeur de 1.



== Paramètres NFS

|===


| Paramètre | Définir cette valeur sur... 


| Net.TcpipeHeapSize | 32 


| Net.TcpipeHeapMax | 1024 MO 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou plus 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===