---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez installer le plug-in NetApp NFS pour VMware vStorage APIs for Array Integration \(VAAI\) à l"aide des outils ONTAP pour VMware vSphere.' 
---
= Installer le plug-in NFS VAAI à l'aide des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in NFS vStorage API for Array Integration (NFS VAAI) connecte VMware vSphere aux baies de stockage NFS.  Utilisez les ONTAP tools for VMware vSphere pour installer le plug-in VAAI. Cela permet à la baie de stockage NFS de gérer certaines opérations de stockage à la place des hôtes ESXi.

.Avant de commencer
* Téléchargez le https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plug-in NetApp NFS pour VMware VAAI"] package d'installation.
* Assurez-vous que vous disposez de l'hôte VMware ESXi et du dernier correctif ou des versions ultérieures de vSphere 7.0U3 et de ONTAP 9.14.1 ou versions ultérieures.
* Monter un datastore NFS.


.Étapes
. Connectez-vous au client vSphere.
. Sélectionnez *raccourcis* > *Outils NetApp ONTAP* dans la section modules externes.
. Sélectionnez *Paramètres* > *Outils NFS VAAI*.
. Si vous avez déjà téléchargé le plug-in VAAI sur vCenter Server, sélectionnez *Modifier* dans *Version existante*.  Si vous ne l'avez pas encore fait, sélectionnez *Télécharger*.
. Parcourez et sélectionnez le `.vib` fichier et sélectionnez *Télécharger* pour télécharger le fichier vers les outils ONTAP.
. Sélectionnez *installer sur l'hôte ESXI*, sélectionnez l'hôte ESXi sur lequel vous souhaitez installer le plug-in NFS VAAI, puis sélectionnez *installer*.
+
Le client Web vSphere affiche uniquement les hôtes ESXi pouvant installer le plug-in. Vous pouvez suivre la progression de l'installation dans la section « Tâches récentes ».

. Redémarrez l'hôte ESXi manuellement après l'installation.
+
Après avoir redémarré l’hôte ESXi, les ONTAP tools for VMware vSphere détectent et activent automatiquement le plug-in NFS VAAI.



.Et la suite ?
Après avoir installé le plug-in NFS VAAI et redémarré votre hôte ESXi, configurez les stratégies d’exportation NFS pour le déchargement de copie VAAI.  Assurez-vous que les règles de la politique d’exportation répondent à ces exigences :

* Le volume ONTAP concerné autorise les appels NFSv4.
* L'utilisateur root reste root et NFSv4 est autorisé dans tous les volumes parents de jonction.
* L'option de prise en charge VAAI est définie sur le serveur NFS concerné.


Pour plus d'informations, reportez-vous à https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configurez les règles d'exportation NFS appropriées pour le déchargement des copies VAAI"] Article de la base de connaissances.

.Informations associées
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Prise en charge de VMware vStorage over NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Activer ou désactiver NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Prise en charge de ONTAP pour NFSv4.2"]
