---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Les outils ONTAP pour VMware vSphere permettent de gérer la protection des clusters hôtes. 
---
= Protégez à l'aide de la protection de cluster hôte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere gèrent la protection des clusters hôtes. Tous les datastores appartenant au SVM sélectionné et montés sur un ou plusieurs hôtes du cluster sont protégés sous un cluster hôte.

.Avant de commencer
Assurez-vous de répondre à ces exigences avant de protéger un cluster hôte :

* Le cluster hôte contient des banques de données provenant d'une seule SVM uniquement.
* Les banques de données sur le cluster hôte ne sont pas montées sur des hôtes extérieurs au cluster.
* Les banques de données montées sur le cluster hôte sont des banques de données VMFS avec protocole iSCSI ou FC.  Vous ne pouvez pas utiliser les banques de données vVols, NFS ou VMFS avec les protocoles NVMe/FC et NVMe/TCP.
* Les banques de données basées sur des volumes FlexVol/LUN montés sur un hôte ne font partie d'aucun groupe de cohérence.
* Les banques de données basées sur des volumes FlexVol/LUN montés sur un hôte ne font partie d’aucune relation SnapMirror .
* Le cluster hôte contient au moins une banque de données.


.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un cluster hôte et sélectionnez * Outils NetApp ONTAP * > * Protéger le cluster *.
. Dans la fenêtre de protection du cluster, le système renseigne automatiquement le type de banque de données et les détails de la machine virtuelle (VM) de stockage source.  Sélectionnez le lien des magasins de données pour afficher les magasins de données protégés.
. Sélectionnez *Ajouter une relation*.
. Dans la fenêtre *Ajouter une relation SnapMirror*, sélectionnez *VM de stockage cible* et le type *Stratégie*.
+
Le type de règle peut être asynchrone ou automatique FailOverDuplex.

+
Lorsque vous ajoutez la relation SnapMirror en tant que stratégie de type AutomatedFailOverDuplex, vous devez ajouter la machine virtuelle de stockage cible en tant que back-end de stockage au serveur vCenter sur lequel les outils ONTAP pour VMware vSphere sont déployés.

+
Dans le type de stratégie AutomatedFailOverDuplex, il existe des configurations d’hôte uniformes et non uniformes.  Lorsque vous sélectionnez le bouton bascule *configuration uniforme de l'hôte*, la configuration du groupe d'initiateurs de l'hôte est implicitement répliquée sur le site cible. Pour plus d'informations, reportez-vous à link:../concepts/ontap-tools-concepts-terms.html["Concepts et termes clés"] .

. Si vous choisissez d'avoir une configuration hôte non uniforme, sélectionnez l'accès hôte (source/cible) pour chaque hôte à l'intérieur de ce cluster.
. Sélectionnez *Ajouter*.
. Vous pouvez modifier la protection du cluster hôte à l'aide de l'opération *Modifier la protection du cluster hôte*.  Vous pouvez modifier ou supprimer les relations à l’aide des options du menu à points de suspension.
. Sélectionnez le bouton *protéger*.
+
Le système crée une tâche vCenter avec les détails de l'ID de tâche et affiche sa progression dans le panneau des tâches récentes.  Il s'agit d'une tâche asynchrone ; l'interface utilisateur affiche uniquement l'état de soumission de la demande et n'attend pas la fin de la tâche.

. Pour afficher les clusters d'hôtes protégés, accédez à * Outils NetApp ONTAP * > *Protection* > *Relations entre les clusters d'hôtes*.  Sélectionnez un groupe de cohérence pour afficher sa capacité, les banques de données associées et les groupes de cohérence enfants.


[NOTE]
====
Si vous devez supprimer la protection dans l’heure suivant sa création, exécutez d’abord la découverte de stockage.

====
.Informations associées
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["Cluster de stockage VMware vSphere Metro (vMSC)"^]
