---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans les ONTAP tools for VMware vSphere 10.5. 
---
= Nouveautés des ONTAP tools for VMware vSphere 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités disponibles dans les ONTAP tools for VMware vSphere 10.5.

* *Qualification de la plateforme*


Les ONTAP tools for VMware vSphere 10.5 ajoutent la prise en charge des systèmes ASA r2, offrant une compatibilité avec les dernières configurations matérielles et logicielles.  Cette version inclut également l'intégration avec ONTAP 9.16.1 et 9.17.1, élargissant ainsi les environnements pris en charge.

* *Qualification et certifications VMware*


Les ONTAP tools for VMware vSphere 10.5 sont conformes aux normes de certification d’interopérabilité VMware actuelles, prenant en charge à la fois l’hôte ESXi et vCenter Server.

* * Prise en charge de MetroCluster *


Cette version introduit la prise en charge des configurations MetroCluster , améliorant ainsi les capacités de haute disponibilité et de reprise après sinistre.

* *Gestion de la sécurité et des certificats*


Cette version introduit une gestion simplifiée des certificats auto-signés, améliorant à la fois l'expérience utilisateur et le respect des normes de sécurité.  Il fournit des flux de travail de validation de certificat améliorés pour sécuriser les outils ONTAP et ONTAP tools for VMware vSphere .

* *Améliorations de la réplication*


Cette version prend en charge la réplication VMFS avec un groupe de cohérence hiérarchique incluant SRA et SnapMirror Active Sync dans les systèmes ASA r2.  Il prend en charge les sauvegardes RPO zéro pour améliorer la protection et la récupération des données.

* *Mise à niveau et migration*


Le processus de mise à niveau et de migration des versions précédentes des ONTAP tools for VMware vSphere vers les ONTAP tools for VMware vSphere 10.5 est conçu pour être transparent et efficace, minimisant les temps d'arrêt et garantissant une transition en douceur.



== Plateformes ONTAP et versions de vCenter Server prises en charge

Pour les derniers détails sur la compatibilité des versions, reportez-vous à https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] .
