---
permalink: manage/add-ntpserver.html 
sidebar: sidebar 
keywords: ONTAP tools NTP server, add NTP server, appliance time sync, ONTAP tools clock synchronization 
summary: 'Ajoutez les informations du serveur NTP pour synchroniser l"heure de l"appliance dans ONTAP tools.' 
---
= Ajouter des serveurs NTP aux outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saisissez les informations du serveur NTP pour synchroniser les horloges de l'appliance ONTAP tools.


NOTE: À partir de ONTAP tools for VMware vSphere 10.6, le démon de synchronisation horaire est chronyd au lieu de ntpd. Lors d’une mise à niveau vers 10.6, les paramètres du serveur NTP existants sont automatiquement migrés. Aucune reconfiguration manuelle n’est requise.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez l'option *Paramètres* > *serveur NTP* > *Modifier*.
. Saisissez les noms de domaine complets (FQDN) ou les adresses IPv4 séparés par des virgules.
+
Actualisez l'écran pour voir les valeurs mises à jour.


