---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords: add vSphere host, ONTAP tools host discovery, register ESXi host, VMware host management 
summary: Ajoutez des hôtes VMware vSphere aux ONTAP tools for VMware vSphere. 
---
= Ajouter des hôtes VMware vSphere aux outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ajoutez de nouveaux hôtes VMware vSphere à ONTAP tools for VMware vSphere afin que vous puissiez gérer et protéger les datastores des hôtes.

.Étapes
. Ajoutez un hôte à votre cluster VMware vSphere en suivant les https://techdocs.broadcom.com/["Broadcom Documentation technique"].
. Après avoir ajouté l'hôte, accédez au menu principal des ONTAP tools et sélectionnez *Discover* dans le panneau d'aperçu, ou attendez que la découverte planifiée de l'hôte soit terminée.


.Résultat
Le nouvel hôte est désormais détecté et géré par ONTAP tools for VMware vSphere. Vous pouvez maintenant gérer les datastores sur l'hôte.

.Sections connexes
* link:../manage/mount-a-vvols-datastore.html["Montez un datastore vvols"]sur de nouveaux hôtes.
* link:../manage/mount-datastores-on-host.html["Montez les datastores NFS et VMFS"]sur de nouveaux hôtes.

