---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords: attach data disk VM, detach VM disk, ONTAP tools virtual machine disk, VMware VM storage expansion 
summary: Attachez ou détachez des disques de données de machine virtuelle pour gérer la capacité de stockage. 
---
= Attacher ou détacher un disque de données d'une machine virtuelle dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Attachez ou détachez des disques de données des machines virtuelles dans vSphere pour gérer la capacité de stockage.



[[attach-a-data-disk-to-a-virtual-machine]]
== Reliez un disque de données à une machine virtuelle

Connectez un disque de données à une machine virtuelle pour augmenter son espace de stockage.

.Étapes
. Connectez-vous au client vSphere.
. Faites un clic droit sur une machine virtuelle dans l'inventaire et sélectionnez *Modifier les paramètres*.
. Dans l'onglet *matériel virtuel*, sélectionnez *disque dur existant*.
. Sélectionnez la machine virtuelle qui contient le disque.
. Sélectionnez le disque que vous souhaitez attacher et sélectionnez *OK*.


.Résultat
Le disque dur apparaît dans la liste périphériques matériels virtuels.



[[detach-a-data-disk-from-the-virtual-machine]]
== Détacher un disque de données de la machine virtuelle

Détachez un disque de données d'une machine virtuelle lorsque vous n'en avez plus besoin. Le disque n'est pas supprimé et reste sur le système de stockage ONTAP.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur une machine virtuelle dans l’inventaire et sélectionnez *Modifier les paramètres*.
. Déplacez votre pointeur sur le disque et sélectionnez *Supprimer*.
+

NOTE: Le disque est supprimé de la machine virtuelle. Si d'autres machines virtuelles partagent le disque, les fichiers du disque ne sont pas supprimés.



.Informations associées
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Ajouter un nouveau disque dur à une machine virtuelle"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Ajouter un disque dur existant à une machine virtuelle"]
