---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Une seule instance des outils ONTAP pour VMware vSphere peut gérer plusieurs instances vCenter Server. Les outils ONTAP pour VMware vSphere sont déployés avec un certificat auto-signé pour VASA Provider. Avec cela, une seule instance vCenter Server peut être gérée pour les datastores vVols. 
---
= Gérer les certificats des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un certificat auto-signé est généré par défaut pour les outils ONTAP et le fournisseur VASA lors du déploiement. Vous pouvez utiliser l'interface du gestionnaire d'outils ONTAP pour renouveler ce certificat ou le remplacer par un certificat d'autorité de certification personnalisé. Dans les déploiements multi-vCenter, l'utilisation de certificats d'autorité de certification personnalisés est requise.

.Avant de commencer
Vous devriez avoir les éléments suivants avant de commencer :

* Le nom de domaine correspond à l'adresse IP virtuelle.
* Résolution réussie du nom de domaine par nslookup, confirmant qu'il correspond à l'adresse IP correcte.
* Certificats créés avec le nom de domaine et l'adresse IP des outils ONTAP .



NOTE: Une adresse IP des outils ONTAP doit correspondre à un nom de domaine complet (FQDN). Les certificats doivent contenir le même nom de domaine complet mappé à l'adresse IP des outils ONTAP dans les autres noms d'objet ou d'objet.


NOTE: Vous ne pouvez pas passer d'un certificat signé par une autorité de certification à un certificat auto-signé.

[role="tabbed-block"]
====
.Certificat de mise à niveau des outils ONTAP
--
L'onglet Outils ONTAP affiche des détails tels que le type de certificat (auto-signé/CA signé) et le nom de domaine. Pendant le déploiement, le certificat auto-signé est généré par défaut. Vous pouvez renouveler le certificat ou le mettre à niveau vers une autorité de certification.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *certificats* > *ONTAP Tools* > *Renew* pour renouveler les certificats.
+
Vous pouvez renouveler le certificat s'il a expiré ou s'il approche de sa date d'expiration. L'option renouveler est disponible lorsque le type de certificat est signé par une autorité de certification. Dans la fenêtre contextuelle, indiquez le certificat du serveur, la clé privée, l'autorité de certification racine et le certificat intermédiaire.

+

NOTE: Le système sera hors ligne jusqu'à ce que le certificat soit renouvelé et vous serez déconnecté de l'interface du Gestionnaire d'outils ONTAP.

. Pour mettre à niveau le certificat auto-signé vers un certificat CA personnalisé, sélectionnez *certificats* > *ONTAP Tools* > *mettre à niveau vers CA* option.
+
.. Dans la fenêtre contextuelle, téléchargez le certificat du serveur, la clé privée du certificat du serveur, le certificat de l'autorité de certification racine et les fichiers de certificat intermédiaires.
.. Saisissez le nom de domaine complet (FQDN) de l'adresse IP de l'équilibreur de charge pour lequel vous avez généré ce certificat et mettez-le à jour.
+

NOTE: Le système sera hors ligne jusqu'à la fin de la mise à niveau et vous serez déconnecté de l'interface du Gestionnaire d'outils ONTAP.





--
.Mettre à niveau le certificat VASA Provider
--
Les outils ONTAP pour VMware vSphere sont déployés avec un certificat auto-signé pour VASA Provider. Avec cela, une seule instance vCenter Server peut être gérée pour les datastores vVols. Lorsque vous gérez plusieurs instances de vCenter Server et que vous souhaitez activer la fonctionnalité vVols sur celles-ci, vous devez remplacer le certificat auto-signé par un certificat d'autorité de certification personnalisé.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *certificats* > *VASA Provider* ou *ONTAP Tools* > *Renew* pour renouveler les certificats.
. Sélectionnez *certificats* > *VASA Provider* ou *ONTAP Tools* > *mettre à niveau vers CA* pour mettre à niveau le certificat auto-signé vers un certificat CA personnalisé.
+
.. Dans la fenêtre contextuelle, téléchargez le certificat du serveur, la clé privée du certificat du serveur, le certificat de l'autorité de certification racine et les fichiers de certificat intermédiaires.
.. Saisissez le nom de domaine complet (FQDN) de l'adresse IP de l'équilibreur de charge pour lequel vous avez généré ce certificat et mettez-le à jour.
+

NOTE: Le système sera hors ligne jusqu'à la fin de la mise à niveau et vous serez déconnecté de l'interface du Gestionnaire d'outils ONTAP.





--
====