---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Une seule instance des outils ONTAP pour VMware vSphere peut gérer plusieurs instances vCenter Server. Les outils ONTAP pour VMware vSphere sont déployés avec un certificat auto-signé pour VASA Provider. Avec cela, une seule instance vCenter Server peut être gérée pour les datastores vVols. 
---
= Gérer les certificats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une seule instance des outils ONTAP pour VMware vSphere peut gérer plusieurs instances vCenter Server.

Assurez-vous que le nom de domaine sur lequel le certificat est émis est mappé à l'adresse IP virtuelle dans un déploiement multi-vCenter où les certificats d'autorité de certification personnalisés sont obligatoires. _Nslookup_ vérifiez le nom de domaine pour vérifier si le domaine est résolu à l'adresse IP prévue. Les certificats doivent être créés avec le nom de domaine et l'adresse IP de l'adresse IP de l'équilibreur de charge.


NOTE: Une adresse IP d'équilibreur de charge différente mappée à différents domaines n'est pas prise en charge lorsque vous mettez à niveau l'autosignature vers une autorité de certification personnalisée.

[role="tabbed-block"]
====
.Certificat d'outils ONTAP
--
L'onglet Outils ONTAP affiche des détails tels que le type de certificat (auto-signé/CA signé) et le nom de domaine. Pendant le déploiement, le certificat auto-signé est généré par défaut. Vous pouvez renouveler le certificat ou le mettre à niveau vers une autorité de certification.

*Étapes*

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://loadBalancerIP:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *certificats* > *ONTAP Tools* > *Renew* option pour renouveler les certificats.
+

NOTE: Vous pouvez renouveler le certificat s'il a expiré ou s'il approche de sa date d'expiration. Le système sera hors ligne jusqu'à ce que le certificat soit renouvelé et que vous soyez déconnecté de l'interface utilisateur.

+
*Renew* est la seule option disponible lorsque le type de certificat est CA signé. Dans le cas d'un certificat signé par une autorité de certification, une boîte de dialogue s'affiche dans laquelle vous pouvez fournir le certificat du serveur, la clé privée, l'autorité de certification racine et les détails du certificat intermédiaire.

. Pour mettre à niveau le certificat auto-signé vers un certificat CA personnalisé, sélectionnez *certificats* > *ONTAP Tools* > *mettre à niveau vers CA* option.
+
.. Dans la fenêtre contextuelle *mettre à niveau le certificat vers une autorité de certification personnalisée*, téléchargez le certificat du serveur, la clé privée du certificat du serveur, le certificat de l'autorité de certification racine et les fichiers de certificat intermédiaires. L'info-bulle fournit une description des certificats.
.. Entrez le nom de domaine pour lequel vous avez généré ce certificat.
.. Cliquez sur *Upgrade*.
+

NOTE: Le système sera hors ligne jusqu'à ce que la mise à niveau soit terminée et que vous soyez déconnecté de l'interface utilisateur. Le passage d'une autorité de certification signée à un certificat auto-signé n'est pas autorisé.





--
.Certificat de fournisseur VASA
--
Les outils ONTAP pour VMware vSphere sont déployés avec un certificat auto-signé pour VASA Provider. Avec cela, une seule instance vCenter Server peut être gérée pour les datastores vVols. Lorsque vous gérez plusieurs instances de serveur vCenter et que vous souhaitez activer la fonctionnalité vVols sur plusieurs instances de serveur vCenter, vous devez remplacer le certificat auto-signé par un certificat d'autorité de certification personnalisé à l'aide de l'interface du gestionnaire des outils ONTAP.

*Étapes*

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://loadBalancerIP:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *certificats* > *VASA Provider* ou *ONTAP Tools* > *Renew* option pour renouveler les certificats.
. Pour mettre à niveau le certificat auto-signé vers un certificat CA personnalisé, sélectionnez *certificats* > *VASA Provider* ou *ONTAP Tools* > *mettre à niveau vers CA* option.
+
.. Dans la fenêtre contextuelle *mettre à niveau le certificat vers une autorité de certification personnalisée*, téléchargez le certificat du serveur, la clé privée du certificat du serveur, le certificat de l'autorité de certification racine et les fichiers de certificat intermédiaires. L'info-bulle fournit une description des certificats.
.. Entrez le nom de domaine pour lequel vous avez généré ce certificat.
.. Cliquez sur *Upgrade*.
+

NOTE: Le système sera hors ligne jusqu'à ce que la mise à niveau soit terminée et que vous soyez déconnecté de l'interface utilisateur. Le passage d'une autorité de certification signée à un certificat auto-signé n'est pas autorisé.





--
====