---
permalink: manage/change-valid-flag.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez modifier l’indicateur de validation du certificat à l’aide de la console de maintenance. 
---
= Modifier l'indicateur de validation du certificat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, l'indicateur de validation du certificat est activé (défini sur vrai).  Vous pouvez définir l'indicateur de validation du certificat backend de stockage ONTAP sur false si vous devez contourner les vérifications de certificat SAN.  Ce paramètre ne s’applique pas aux certificats vCenter Server.

.Avant de commencer
Vous devez disposer des informations d'identification de l'utilisateur de maintenance.

.Étapes
. À partir du serveur vCenter, ouvrez une console pour accéder aux outils ONTAP.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrer `1` pour sélectionner le menu *Configuration de l'application*.
. Entrer `3` pour modifier l'indicateur de validation du certificat.
+
La console de maintenance affiche l’état de l’indicateur de validation du certificat et vous invite à le modifier.

. Entrez « y » pour basculer le drapeau ou « n » pour annuler.


Lorsque vous activez l'indicateur de validation du certificat (défini sur vrai), les outils ONTAP vérifient que tous les systèmes de stockage utilisent des certificats avec un nom alternatif de sujet (SAN).  Si un système dorsal utilise un certificat sans SAN, la validation du certificat ne peut pas être activée.  Avant d'activer cette option, vérifiez que tous les systèmes de stockage utilisent des certificats basés sur SAN.  Si vous désactivez l'indicateur de validation du certificat (défini sur false), les outils ONTAP contournent la validation du certificat pour tous les systèmes de stockage configurés.
