---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords: remote diagnostic access, ONTAP tools SSH diag user, enable SSH diagnostics, appliance troubleshooting access 
summary: 'Activez l"accès SSH pour l"utilisateur diag dans ONTAP tools for VMware vSphere.' 
---
= Configurer l'accès de diagnostic à distance pour ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les outils ONTAP pour VMware vSphere afin d'activer l'accès SSH pour l'utilisateur diag.

.Avant de commencer
Activez l'extension VASA Provider pour votre instance vCenter Server.

.Description de la tâche
L'utilisation de SSH pour accéder au compte utilisateur diag présente les limites suivantes :

* vous n'êtes autorisé qu'à un seul compte de connexion par activation de SSH.
* L'accès SSH au compte utilisateur diag est désactivé lorsque l'une des conditions suivantes se produit :
+
** Le délai expire.
+
La session de connexion expire à minuit le lendemain.

** Vous vous connectez à nouveau en tant qu'utilisateur diag à l'aide de SSH.




.Étapes
. Connectez-vous au serveur vCenter.
. Localisez la machine virtuelle ONTAP tools et lancez la console Web.
. Connectez-vous en utilisant les `maint` identifiants.
. Entrez `4` pour sélectionner *support et diagnostic*.
. Entrer `2` pour sélectionner *Activer l'accès au diagnostic à distance*.
. Entrez `y` Dans la boîte de dialogue Confirmation pour activer l'accès au diagnostic à distance.
. Saisissez un mot de passe pour l'accès au diagnostic à distance.

