---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: remove FlexVol after uninstall, ONTAP tools cleanup, delete unused FlexVol volumes, post-uninstall storage cleanup 
summary: 'Supprimez les volumes FlexVol inutilisés après la suppression du déploiement des outils ONTAP afin d"éviter les impacts sur les performances.' 
---
= Supprimez les volumes FlexVol après la désinstallation des ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous déployez les ONTAP tools for VMware vSphere sur un cluster ONTAP dédié, le déploiement crée de nombreux volumes FlexVol inutilisés. Après avoir supprimé les ONTAP tools, supprimez les volumes FlexVol inutilisés afin d’éviter tout impact sur les performances.

.Étapes
. Déterminez le type de déploiement des ONTAP tools for VMware vSphere à partir de la machine virtuelle du nœud de gestion des ONTAP tools. Exécutez la commande suivante pour vérifier le type de déploiement : _cat /opt/netapp/meta/ansible_vars.yaml | grep -i protocol_
+
Si le déploiement utilise iSCSI, supprimez également les igroups.

. Obtenez la liste des volumes FlexVol . _kubectl décrit les volumes persistants | grep internalName | awk -F'=' '{print $2}'_
. Supprimez les machines virtuelles du serveur vCenter. Reportez-vous à la https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Supprimez et réenregistrez les machines virtuelles et les modèles de machines virtuelles"].
. Supprimer les volumes FlexVol . Se référer à https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Supprime un volume FlexVol"] . Saisissez le nom exact du FlexVol volume dans la commande CLI pour supprimer un volume.
. Pour les déploiements iSCSI, supprimez les igroups SAN du système de stockage ONTAP. Voir https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Affichez et gérez les initiateurs SAN et igroups"].

