---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 'L"action Supprimer le datastore supprime le datastore. Dans le cas d"un datastore NFS ou VMFS, une boîte de dialogue s"affiche avec la liste des machines virtuelles qui utilisent le datastore.' 
---
= Supprimer les datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette section décrit comment supprimer des banques de données NFS, VMFS ou vVols à l’aide des outils ONTAP dans vCenter Server.

Lorsque vous supprimez une banque de données, les actions suivantes sont effectuées en fonction du type de banque de données :

* Le conteneur vVol est démonté.
* Si l'igroup n'est pas utilisé, iqn est supprimé de l'igroup.
* Le conteneur vVol est supprimé.
* Les volumes flexibles sont laissés sur la baie de stockage.


Vous ne pouvez supprimer le magasin de données que si aucun vVols n'est présent sur le magasin de données sélectionné.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un système hôte, un cluster hôte ou un centre de données et sélectionnez * Outils NetApp ONTAP * > * Supprimer la banque de données *.
+

NOTE: Vous ne pouvez pas supprimer une banque de données utilisée par des machines virtuelles.  Déplacez les machines virtuelles vers un autre magasin de données avant de les supprimer.  Vous ne pouvez pas supprimer le volume s’il fait partie d’un cluster hôte protégé.

+
.. Dans le cas d'une banque de données NFS ou VMFS, une boîte de dialogue apparaît avec la liste des machines virtuelles utilisant la banque de données.
.. Si aucune machine virtuelle n’est associée à une banque de données VMFS, une boîte de dialogue de confirmation s’affiche.  Si la protection du cluster hôte est activée et qu'une relation AFD existe, vous pouvez nettoyer les éléments de stockage secondaires.
.. Pour les banques de données VMFS protégées sur les systèmes ASA r2, assurez-vous que la protection est supprimée avant la suppression.  À partir d’ ONTAP 9.17.1 et des ONTAP tools for VMware vSphere 10.5, vous pouvez supprimer une banque de données protégée.  S'il s'agit de la seule banque de données du groupe de protection, la protection du cluster hôte est automatiquement supprimée.
.. Pour les magasins de données vVols , vous ne pouvez supprimer le magasin de données que s'il n'y a aucun vVols présent.  La boîte de dialogue *Supprimer la banque de données* inclut une option permettant de supprimer des volumes du cluster ONTAP .
.. Pour les banques de données vVols sur les systèmes ASA r2, vous ne pouvez pas supprimer les volumes de sauvegarde d' ONTAP à l'aide de l'option *Supprimer la banque de données*.


. Pour supprimer les volumes de sauvegarde sur le stockage ONTAP, sélectionnez *Supprimer les volumes sur le cluster ONTAP*.
+

NOTE: Pour les banques de données VMFS sur un stockage ONTAP unifié qui font partie d'un cluster hôte protégé, vous ne pouvez pas supprimer le volume du cluster ONTAP .


