---
permalink: manage/disable-autosupport.html 
sidebar: sidebar 
keywords:  
summary: Lors de la première configuration de votre système de stockage, AutoSupport est activé par défaut. Il envoie des messages au support technique 24 heures après son activation. 
---
= Désactivez AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la première configuration de votre système de stockage, AutoSupport est activé par défaut. Il envoie des messages au support technique 24 heures après son activation. Lorsque vous désactivez AutoSupport, vous ne recevrez plus de support et de surveillance proactifs.


NOTE: Il est recommandé de conserver AutoSupport activé. Elle accélère la détection et la résolution des problèmes. Le système collecte les informations AutoSupport et les stocke localement, même lorsqu'elles sont désactivées. Cependant, il n'envoie pas le rapport à aucun réseau.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez l'option *Paramètres* > *télémétrie* > *Modifier*.
. Désélectionnez l'option *AutoSupport* et enregistrez les modifications.

