---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier le mot de passe administrateur à l"aide du Gestionnaire d"outils ONTAP.' 
---
= Modification des outils ONTAP pour la configuration de VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ONTAP Tools Manager pour faire évoluer les ONTAP tools for VMware vSphere , soit en augmentant le nombre de nœuds, soit en activant la haute disponibilité (HA).  Par défaut, les ONTAP tools for VMware vSphere sont déployés en tant que configuration à nœud unique, non HA.

.Avant de commencer
* Assurez-vous que votre modèle OVA possède la même version OVA que le nœud 1. Le nœud 1 est le nœud par défaut sur lequel les outils ONTAP pour VMware vSphere OVA sont initialement déployés.
* Assurez-vous que l'ajout à chaud du processeur et la connexion à chaud de la mémoire sont activés.
* Dans vCenter Server, définissez le niveau d'automatisation du service de reprise après sinistre (DRS) sur partiellement automatisé. Après le déploiement de la haute disponibilité, rétablissez le niveau d'automatisation complet.
* Les noms d’hôtes des nœuds dans la configuration HA doivent être en minuscules.


.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *Modifier les paramètres de l'appareil* dans la section Présentation.
. Dans la section *Configuration*, augmentez la taille du nœud et activez la configuration HA.  Utilisez les identifiants du serveur vCenter pour effectuer les modifications.
+
Dans la configuration HA, vous pouvez modifier les détails de la bibliothèque de contenu.  Veuillez indiquer le mot de passe pour chaque modification.

+

NOTE: Dans les ONTAP tools for VMware vSphere, vous êtes uniquement autorisé à augmenter la taille du nœud ; vous ne pouvez pas la réduire.  Dans une configuration non HA, seule une configuration de taille moyenne est prise en charge.  Dans une configuration HA, les configurations moyennes et grandes sont prises en charge.

. Utilisez le bouton bascule HA pour activer la configuration HA. Sur la page *HA settings*, assurez-vous que :
+
** La bibliothèque de contenu appartient au même serveur vCenter sur lequel s'exécutent les machines virtuelles du nœud des outils ONTAP. Les informations d'identification du serveur vCenter sont utilisées pour valider et télécharger le modèle OVA pour les modifications de l'appliance.
** La machine virtuelle hébergeant les outils ONTAP n'est pas directement déployée sur un hôte VMware ESXi. La machine virtuelle doit être déployée sur un cluster ou un pool de ressources.
+

NOTE: Une fois la configuration HA activée, vous ne pouvez pas revenir à une configuration à nœud unique non HA.



. Dans la section *HA settings* de la fenêtre *Edit Appliance Settings*, vous pouvez entrer les détails des nœuds 2 et 3. Les outils ONTAP pour VMware vSphere prennent en charge trois nœuds lors de la configuration haute disponibilité.
+

NOTE: Les outils ONTAP pré-remplissent la plupart des options d'entrée avec les détails du réseau Node 1 afin de simplifier le flux de travail.  Vous pouvez modifier les données saisies avant d'accéder à la dernière page de l'assistant. Vous pouvez saisir les détails de l'adresse IPv6 pour les deux autres nœuds uniquement lorsque l'adresse IPv6 est activée sur le nœud de gestion des outils ONTAP .

+
Assurez-vous qu'un hôte ESXi ne contient qu'une seule machine virtuelle d'outils ONTAP. Les entrées sont validées chaque fois que vous passez à la fenêtre suivante.

. Passez en revue les détails dans la section *Résumé* et *Enregistrer* les modifications.


.Et la suite ?
La page *Aperçu* affiche l'état du déploiement. Vous pouvez également suivre l'état de la tâche de modification des paramètres de l'appareil depuis la vue des tâches en utilisant l'ID de la tâche.

Si le déploiement HA échoue et que le statut du nouveau nœud est « Nouveau », supprimez la nouvelle machine virtuelle dans vCenter avant de tenter à nouveau d'activer HA.

L'onglet *alertes* du panneau de gauche répertorie les alertes des outils ONTAP pour VMware vSphere.
