---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Vous pouvez modifier les relations SnapMirror du cluster hôte protégé. Vous pouvez ajouter, modifier et supprimer les relations. Toutefois, vous ne pouvez pas modifier le nom du groupe de cohérence. 
---
= Modifier un cluster d'hôtes protégé dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres de protection d’un cluster hôte dans un seul workflow.  Les modifications suivantes sont prises en charge :

* Ajoutez de nouveaux datastores ou hôtes au cluster protégé.
* Ajoutez de nouvelles relations SnapMirror aux paramètres de protection.
* Supprimez les relations SnapMirror existantes des paramètres de protection.
* Modifier une relation SnapMirror existante.



NOTE: Vous devez effectuer la découverte de stockage après avoir créé, modifié ou supprimé la protection d'un cluster hôte afin de refléter les modifications.  Si vous n'effectuez pas la découverte de stockage, les modifications sont reflétées après le déclenchement de la découverte de stockage périodique.



== Surveillez la protection des clusters hôtes

Surveillez l’état de protection, les relations SnapMirror , les banques de données et l’état SnapMirror pour chaque cluster d’hôtes protégé.

.Étapes
. Connectez-vous au client vSphere.
. Accédez à * Outils NetApp ONTAP * > *Protection* > *Relations entre clusters d'hôtes*.
+
La colonne de protection affiche une icône qui indique l'état de protection.

. Passez la souris sur l'icône pour afficher plus de détails.




== Ajoutez de nouveaux datastores ou hôtes

Ajoutez des hôtes ou créez des banques de données sur le cluster protégé à l’aide de l’interface utilisateur vCenter.

.Étapes
. Connectez-vous au client vSphere.
. Pour modifier les propriétés d'un cluster protégé, vous pouvez l'un ou l'autre
+
.. Accédez à * Outils NetApp ONTAP * > * Protection * > * Relations entre clusters d'hôtes *, sélectionnez le menu à points de suspension à côté du cluster et sélectionnez * Modifier * ou
.. Cliquez avec le bouton droit sur un cluster hôte et sélectionnez * Outils NetApp ONTAP * > * Protéger le cluster *.


. Si vous créez une banque de données dans l’interface utilisateur de vCenter, elle apparaît comme non protégée.  Vous pouvez afficher tous les magasins de données du cluster et leur état de protection dans une boîte de dialogue.  Sélectionnez le bouton *Protéger* pour activer la protection.
+

NOTE: Après avoir créé une banque de données dans l'interface utilisateur de vCenter Server, sélectionnez *Découvrir* sur la page de présentation pour afficher la banque de données comme candidate à la protection dans le cluster hôte.  L'état de protection est mis à jour sur protégé après la prochaine découverte de protection périodique.

. Si vous ajoutez un nouvel hôte ESXi, l’état de protection est affiché comme partiellement protégé.  Sélectionnez le menu points de suspension sous les paramètres SnapMirror et sélectionnez *Modifier* pour définir la proximité de l’hôte ESXi nouvellement ajouté.
+

NOTE: Pour les relations asynchrones, la modification n'est pas prise en charge dans les outils ONTAP car le SVM cible d'un site tertiaire ne peut pas être ajouté à la même instance.  Pour modifier la configuration de la relation, utilisez le Gestionnaire système ou l’interface de ligne de commande sur la SVM cible.

. Après avoir effectué les modifications, sélectionnez *Enregistrer*.
. Vous pouvez voir les modifications dans la fenêtre *Protect Cluster*.


Les outils ONTAP créent une tâche vCenter et vous pouvez suivre sa progression dans le panneau *Tâche récente*.



== Ajouter une nouvelle relation SnapMirror

.Étapes
. Connectez-vous au client vSphere.
. Pour modifier les propriétés d'un cluster protégé, vous pouvez l'un ou l'autre
+
.. Accédez à * Outils NetApp ONTAP * > * Protection * > * Relations entre clusters d'hôtes *, sélectionnez le menu à points de suspension en regard du cluster et sélectionnez * Modifier * ou
.. Cliquez avec le bouton droit sur un cluster hôte et sélectionnez * Outils NetApp ONTAP * > * Protéger le cluster *.


. Sélectionnez *Ajouter une relation*.
. Ajoutez une nouvelle relation en tant que type de stratégie *Asynchronous* ou *AutomatedFailOverDuplex*.
. Sélectionnez *protéger*.
+
Vous pouvez voir les modifications dans la fenêtre *Protect Cluster*.



Les outils ONTAP créent une tâche vCenter et vous pouvez suivre sa progression dans le panneau *Tâche récente*.



== Supprimez une relation SnapMirror existante

Pour supprimer une relation asynchrone SnapMirror , assurez-vous que le SVM ou le cluster du site secondaire est ajouté en tant que backend de stockage dans les ONTAP tools for VMware vSphere.  Vous ne pouvez pas supprimer toutes les relations SnapMirror à la fois.  La suppression d’une relation supprime également la relation correspondante du cluster ONTAP .  Lorsque vous supprimez une relation SnapMirror Duplex de basculement automatisé, le système démappe les banques de données de destination et supprime le groupe de cohérence, les LUN, les volumes et les igroups du cluster ONTAP de destination.

Lorsque vous supprimez la relation, le système réanalyse le site secondaire pour supprimer le LUN non mappé en tant que chemin actif des hôtes.

.Étapes
. Connectez-vous au client vSphere.
. Pour modifier les propriétés d'un cluster protégé, vous pouvez l'un ou l'autre
+
.. Accédez à * Outils NetApp ONTAP * > * Protection * > * Relations entre clusters d'hôtes *, sélectionnez le menu à points de suspension en regard du cluster et sélectionnez * Modifier * ou
.. Cliquez avec le bouton droit sur un cluster hôte et sélectionnez * Outils NetApp ONTAP * > * Protéger le cluster *.


. Sélectionnez le menu points de suspension sous les paramètres SnapMirror et sélectionnez *Supprimer*.
+
** Si vous supprimez une relation basée sur un type de stratégie asynchrone d'un cluster d'hôtes protégé, vous devez supprimer manuellement les éléments de stockage du cluster de stockage tertiaire.  Les éléments de stockage incluent des groupes de cohérence, des volumes (pour les systèmes ONTAP ), des unités de stockage (LUN/espaces de noms) et des instantanés.
** Si vous supprimez une relation basée sur une stratégie de basculement automatique duplex (AFD) d'un cluster d'hôtes protégé, vous pouvez choisir de supprimer les éléments de stockage associés sur le stockage secondaire directement à partir de l'interface.
** Si vous supprimez une relation basée sur une stratégie de duplex de basculement automatisé (AFD) et que le groupe de cohérence est désormais hiérarchique pour les sauvegardes au niveau de l'application, un avertissement s'affiche concernant l'impact de la sauvegarde.  Confirmez pour continuer.  Après confirmation, supprimez les éléments de stockage associés sur le stockage secondaire.  Si vous ne les supprimez pas, ils restent sur le site secondaire.




Les outils ONTAP créent une tâche vCenter et vous pouvez suivre sa progression dans le panneau *Tâche récente*.



== Modifier une relation SnapMirror existante

Pour modifier une relation asynchrone SnapMirror , assurez-vous que le SVM ou le cluster du site secondaire est ajouté en tant que backend de stockage dans les ONTAP tools for VMware vSphere.  Pour les relations SnapMirror Duplex de basculement automatisé, vous pouvez mettre à jour la proximité de l'hôte pour les configurations uniformes ou l'accès à l'hôte pour les configurations non uniformes.  Le changement entre les types de stratégie Duplex de basculement asynchrone et automatisé n'est pas pris en charge.  Vous pouvez configurer les paramètres de proximité ou d’accès pour les hôtes nouvellement découverts dans le cluster.


NOTE: Vous ne pouvez pas modifier une relation asynchrone SnapMirror existante.

.Étapes
. Connectez-vous au client vSphere.
. Pour modifier les propriétés d'un cluster protégé, vous pouvez l'un ou l'autre
+
.. Accédez à * Outils NetApp ONTAP * > * Protection * > * Relations entre clusters d'hôtes *, sélectionnez le menu à points de suspension en regard du cluster et sélectionnez * Modifier * ou
.. Cliquez avec le bouton droit sur un cluster hôte et sélectionnez * Outils NetApp ONTAP * > * Protéger le cluster *.


. Si le type de stratégie AutomatedFailOverDuplex est sélectionné, ajoutez les détails de proximité ou d'accès à l'hôte.
. Sélectionnez le bouton *protéger*.


Les outils ONTAP créent une tâche vCenter.  Suivez sa progression dans le panneau *Tâche récente*.
