---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords: modify ESXi host settings, ONTAP tools host configuration, VMware host tuning, ESXi settings dashboard 
summary: 'Modifiez les paramètres de l"hôte ESXi depuis le tableau de bord des ONTAP tools.' 
---
= Modifiez les paramètres de l'hôte VMware ESXi à l'aide des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez le tableau de bord des ONTAP tools dans VMware vSphere pour identifier les problèmes de configuration, examiner les paramètres recommandés par NetApp pour les hôtes ESXi sélectionnés et les appliquer.

.Avant de commencer
Le portlet des systèmes hôtes ESXi affiche les problèmes liés aux paramètres de l'hôte ESXi.  Sélectionnez un problème pour afficher le nom d'hôte ou l'adresse IP.

.Étapes
. Connectez-vous au client vSphere.
. Sur la page Raccourcis, sélectionnez *NetApp ONTAP tools* dans la section Modules d’extension.
. Accédez au portlet *Conformité de l’hôte ESXi* sur le tableau de bord Vue d’ensemble du plug-in ONTAP tools for VMware vSphere.
. Sélectionnez le lien *Appliquer les paramètres recommandés*.
. Dans la fenêtre *Appliquer les paramètres d'hôte recommandés*, sélectionnez les hôtes auxquels vous souhaitez appliquer les paramètres d'hôte recommandés NetApp, puis sélectionnez *Suivant*.
+

NOTE: Vous pouvez développer l'hôte ESXi pour voir les valeurs actuelles.

. Sur la page Paramètres, sélectionnez les valeurs recommandées selon vos besoins.
. Dans le volet récapitulatif, vérifiez les valeurs et sélectionnez *Terminer*. Vous pouvez suivre la progression dans le panneau Tâches récentes.


.Informations associées
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Configurer les paramètres de l'hôte ESXi"]
