---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords: scale ONTAP tools appliance, enable high availability, ONTAP tools HA configuration, appliance scaling settings 
summary: 'Mettez à l"échelle l"appliance ONTAP tools et configurez la haute disponibilité (HA) à l"aide de ONTAP tools Manager.' 
---
= Augmentez l'échelle des ONTAP tools et activez la haute disponibilité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ONTAP tools Manager pour faire évoluer votre appliance et configurer la haute disponibilité (HA). Par défaut, ONTAP tools for VMware vSphere est déployé en configuration mono-nœud sans haute disponibilité.

.Avant de commencer
* Assurez-vous que votre modèle OVA correspond à la version du nœud 1 (le nœud de déploiement initial).
* Activez l'ajout à chaud de processeurs et de mémoire sur l'hyperviseur. Ces fonctionnalités sont nécessaires pour augmenter la capacité de l'appliance et activer la haute disponibilité. Pour ONTAP tools 10.6 et versions ultérieures, ces fonctionnalités sont activées par défaut. Pour les versions antérieures, activez ces fonctionnalités avant d'augmenter la capacité ou d'activer la haute disponibilité.
* Dans vCenter Server, définissez le niveau d'automatisation du service de reprise après sinistre (DRS) sur partiellement automatisé. Revenez au niveau entièrement automatisé une fois le déploiement de la haute disponibilité terminé.
+

NOTE: Vous pouvez uniquement augmenter la taille des nœuds, pas la diminuer. Les déploiements extra-petits (XS) limitent certains services.



.Étapes
. Lancez le gestionnaire ONTAP tools : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous avec vos identifiants d'administrateur des outils ONTAP.
. Sélectionnez *Modifier les paramètres de l'appareil* dans la section Vue d'ensemble.
. Dans la section *Configuration*, sélectionnez la taille de votre nouveau nœud et activez l'interrupteur HA pour activer la haute disponibilité.
. Sur la page des *paramètres HA*, vérifiez les points suivants :
+
** La bibliothèque de contenu se trouve sur le même vCenter Server où s'exécuteront les machines virtuelles des ONTAP tools.
** Les machines virtuelles ONTAP tools sont déployées sur un cluster ou un pool de ressources, et non directement sur un hôte ESXi.
+

IMPORTANT: Une fois la haute disponibilité activée, vous ne pouvez pas revenir à une configuration à nœud unique sans haute disponibilité.



. Dans la section *paramètres HA*, saisissez les détails du réseau pour les nœuds 2 et 3. Les outils ONTAP prennent en charge trois nœuds en mode HA.
+
ONTAP tools pré-remplit la plupart des champs avec les paramètres réseau du nœud 1. Vous pouvez modifier ces valeurs avant de terminer l’assistant. Les entrées d’adresse IPv6 ne sont disponibles que si IPv6 est activé sur le nœud de gestion. Assurez-vous que chaque hôte ESXi héberge une seule machine virtuelle ONTAP tools.

. Vérifiez le résumé et cliquez sur *Enregistrer*.


.Résultat
L'appliance commence sa mise à l'échelle et l'activation de la haute disponibilité. Surveillez la progression sur la page *Aperçu* ou suivez la tâche depuis la vue *Tâches* à l'aide de l'ID de la tâche.

Si le déploiement HA échoue avec le statut « Nouveau », supprimez la VM défaillante dans vCenter et réessayez.

Consultez l'onglet *Alertes* pour vérifier la présence de tout avertissement ou problème survenu pendant le processus.
