---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez utiliser le tableau de bord des outils ONTAP pour VMware vSphere afin de modifier les paramètres de votre hôte ESXi. 
---
= Modifiez les paramètres de l'hôte VMware ESXi à l'aide des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez le tableau de bord des outils ONTAP dans VMware vSphere pour identifier les problèmes de configuration, sélectionner les hôtes ESXi, consulter les paramètres recommandés par NetApp et les appliquer.

.Avant de commencer
Le portlet des systèmes hôtes ESXi affiche les problèmes liés aux paramètres de l'hôte ESXi.  Sélectionnez un problème pour afficher le nom d'hôte ou l'adresse IP.

.Étapes
. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Accédez au portlet *ESXi Host Compliance* dans la Présentation (tableau de bord) du plug-in ONTAP Tools for VMware vSphere.
. Sélectionnez le lien *appliquer les paramètres recommandés*.
. Dans la fenêtre *Appliquer les paramètres d'hôte recommandés*, sélectionnez les hôtes pour lesquels vous souhaitez utiliser les paramètres d'hôte recommandés par NetApp , puis sélectionnez *Suivant*.
+

NOTE: Vous pouvez développer l'hôte ESXi pour voir les valeurs actuelles.

. Dans la page des paramètres, sélectionnez les valeurs recommandées.
. Dans le volet récapitulatif, vérifiez les valeurs et sélectionnez *Terminer*. Vous pouvez suivre la progression dans le panneau des tâches récentes.


.Informations associées
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Configurer les paramètres de l'hôte ESXi"]
