---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords: enable ONTAP tools services, enable VASA provider, enable SRA service, vVols service configuration 
summary: 'Activez les services optionnels des ONTAP tools, notamment le fournisseur VASA, vVols, l"importation de configuration et la reprise après sinistre (SRA).' 
---
= Activer les services ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez ONTAP tools Manager pour activer des services optionnels tels que VASA Provider, vVols, l'importation de configuration et la reprise après sinistre (SRA).

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Dans la section *Aperçu*, sélectionnez *Modifier les paramètres de l’appareil*.
. Dans la section *Services*, activez les services optionnels dont vous avez besoin, tels que VASA Provider, vVols, l'importation de configuration et la reprise après sinistre (SRA).
+
Lorsque vous activez ces services pour la première fois, créez des identifiants VASA Provider et SRA.

+
** Utilisez ces identifiants pour enregistrer et activer les services VASA Provider et SRA sur le serveur vCenter.
** Le nom d'utilisateur peut contenir uniquement des lettres, des chiffres et des traits de soulignement.
** La longueur du mot de passe doit être comprise entre 8 et 256 caractères.





NOTE: Avant de désactiver un service optionnel, assurez-vous que les instances de serveur vCenter gérées par ONTAP tools n'utilisent pas ce service.

L’option *Autoriser l’importation de la configuration vVols* n’apparaît que lorsque le service VASA Provider est activé. Cette option permet la migration des données vVols depuis ONTAP tools 9.x vers ONTAP tools 10.6.
