---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'Lorsque vous cliquez avec le bouton droit de la souris sur l"objet datastore dans la vue d"objet vCenter, les actions prises en charge par les outils ONTAP pour VMware vSphere s"affichent sous la section du plug-in.' 
---
= Développez les datastores vVols dans les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous cliquez avec le bouton droit sur l'objet datastore dans la vue d'objet vCenter, la section des plug-ins affiche les actions prises en charge pour les ONTAP tools for VMware vSphere. Des actions spécifiques sont activées en fonction du type de banque de données et des privilèges utilisateur actuels.


NOTE: L'opération étendre le datastore vVols ne s'applique pas aux datastores vVols système ASA r2.

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit de la souris sur le datastore et sélectionnez *NetApp ONTAP Tools* > *Add Storage to datastore*.
. Dans la fenêtre *Créer ou sélectionner des volumes*, vous pouvez soit créer de nouveaux volumes, soit choisir parmi les volumes existants. Suivez les instructions à l'écran pour effectuer votre sélection.
. Dans la fenêtre *Résumé*, examinez les sélections et sélectionnez *développer*. Vous pouvez suivre la progression dans le panneau tâches récentes.

