---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: expand vVols datastore, increase vVol datastore capacity, ONTAP tools vVol storage expansion, VMware virtual volumes scaling 
summary: Étendez le stockage du datastore vVols à partir de la vue objet vCenter en utilisant les actions des outils ONTAP. 
---
= Étendre une banque de données vVols dans les ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous cliquez avec le bouton droit sur l'objet datastore dans la vue d'objets vCenter, la section du plug-in affiche les actions prises en charge pour ONTAP tools for VMware vSphere. Les actions disponibles dépendent du type de datastore et des privilèges de l'utilisateur actuel.


NOTE: Cette procédure ne s'applique pas aux banques de données vVols basées sur le système ASA r2.

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit de la souris sur le datastore et sélectionnez *NetApp ONTAP Tools* > *Add Storage to datastore*.
. Dans la fenêtre *Créer ou sélectionner des volumes*, vous pouvez soit créer de nouveaux volumes, soit choisir parmi les volumes existants. Suivez les instructions à l'écran pour effectuer votre sélection.
. Dans la fenêtre *Résumé*, examinez les sélections et sélectionnez *développer*. Vous pouvez suivre la progression dans le panneau tâches récentes.

