---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: Gérez les instances vCenter dans ONTAP tools pour contrôler les hôtes, les machines virtuelles et les systèmes de stockage. 
---
= Gérer les instances vCenter Server dans les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les instances vCenter Server sont des plateformes de gestion centralisée qui vous permettent de contrôler les hôtes, les machines virtuelles et les systèmes back-end de stockage.



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== Dissocier les systèmes de stockage d'une instance de serveur vCenter

La page de liste vCenter Server affiche le nombre de systèmes back-end de stockage associés. Chaque instance de vCenter Server peut être associée ou dissociée à un système back-end de stockage.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *vCenters* dans la barre latérale.
. Sélectionnez les points de suspension verticaux pour le vCenter Server que vous souhaitez associer ou dissocier aux backends de stockage.
. Sélectionnez *dissocier le backend de stockage*.




[[modify-a-vcenter-server-instance]]
== Modifier une instance de vCenter Server

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *vCenters* dans la barre latérale.
. Sélectionnez les points de suspension verticaux pour le serveur vCenter que vous souhaitez modifier et sélectionnez *Modifier*.
. Dans la fenêtre *Modifier vCenter*, saisissez le nom d’utilisateur, le mot de passe et les détails du port.
. Téléchargez le certificat et sélectionnez *Modifier*.




[[remove-a-vcenter-server-instance]]
== Supprimer une instance de vCenter Server

Vous pouvez supprimer une instance de serveur vCenter même si des banques de données et des systèmes de stockage y sont encore associés. La boîte de dialogue *Supprimer vCenter* vous guide à travers les actions nécessaires en fonction de l'état actuel du serveur vCenter.


NOTE: La suppression forcée efface uniquement les métadonnées des outils ONTAP. Elle ne supprime pas les objets de stockage ONTAP (volumes ou LUN), les banques de données vSphere ni les machines virtuelles.

.Avant de commencer
La suppression forcée est bloquée si le serveur vCenter possède des banques de données vVols ou des banques de données protégées. Avant de continuer :

* Supprimez ou migrez tous les datastores vVols.
* Déprotégez tous les magasins de données protégés.
* Assurez-vous qu'aucune tâche de découverte n'est en cours. L'opération de suppression forcée ne pourra pas avoir lieu si des tâches de découverte sont en cours.



NOTE: Les espaces de stockage globaux partagés avec d'autres instances de serveur vCenter sont conservés. Seule l'association avec le serveur vCenter supprimé est supprimée.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *vCenters* dans la barre latérale.
. Sélectionnez les points de suspension verticaux pour le vCenter Server requis et sélectionnez *Supprimer*.
. Dans la boîte de dialogue *Supprimer vCenter*, vérifiez l’état du serveur vCenter et effectuez toutes les actions requises.
+
Le comportement du dialogue dépend de l'état du serveur vCenter :

+
[cols="2,2,3"]
|===
| Condition | Comportement du dialogue | Action requise 


| Aucun vVols ni magasin de données protégé, mais les backends de stockage sont associés | La boîte de dialogue affiche le nombre de systèmes de stockage backends et de banques de données associés. | Sélectionnez *Supprimer tous les artefacts de stockage de ce vCenter Server* et *Je comprends que les banques de données associées ne seront plus gérées par ONTAP tools*. 


| Aucun magasin de données vVols, magasin de données protégé ou backend de stockage | La boîte de dialogue confirme la suppression. | Aucune action supplémentaire requise. 
|===
. Sélectionnez *Force delete*.
. Confirmez l'action.


.Résultat
Les outils ONTAP effectuent automatiquement les actions suivantes :

* Le plug-in n'est pas enregistré.
* Les privilèges de plug-in et les rôles de plug-in sont supprimés.


L’instance du serveur vCenter n’est plus gérée par les outils ONTAP.

Si le serveur vCenter est inaccessible pendant la suppression :

* Les outils ONTAP suppriment l'enregistrement du serveur vCenter.
* La désinscription du plugin n'a pas lieu.
* Un avertissement s'affiche.
* Vous devez désenregistrer manuellement le plugin auprès de VMware vCenter Server.




[[renew-vcenter-server-certificate]]
== Renouveler le certificat du serveur vCenter

Les outils ONTAP vous avertissent lorsque le certificat vCenter approche de son expiration ou a expiré. Après avoir renouvelé le certificat vCenter, téléchargez le nouveau certificat sur les outils ONTAP en suivant les étapes suivantes :

. Connectez-vous à l'interface de diagnostic à distance des outils ONTAP .
. Obtenez le certificat vCenter renouvelé depuis l'interface de diagnostic :
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. Assurez-vous que le certificat est au format ASCII Base 64 et qu'il comprend les lignes de début et de fin, par exemple :
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copiez le résultat et enregistrez-le dans un fichier texte avec un `.pem` extension sur votre bureau.
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez l'instance de vCenter Server appropriée dans la barre latérale
. Sélectionnez les points de suspension verticaux pour le serveur vCenter que vous souhaitez modifier et sélectionnez *Modifier*.
. Dans la fenêtre *Modifier vCenter*, saisissez le nom d’utilisateur, le mot de passe et les détails du port.
. Téléchargez le certificat et sélectionnez *Modifier*.


.Informations associées
link:../manage/configure-remote-diagnostic-access.html["Configurer l'accès aux diagnostics à distance"]
