---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage 
summary: Migrez les machines virtuelles des banques de données NFS et VMFS vers des banques de données vVols pour une gestion basée sur des règles. 
---
= Migrer des machines virtuelles vers des datastores vVols dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez migrer des machines virtuelles depuis des datastores NFS ou VMFS vers des datastores Virtual Volumes (vVols) pour utiliser la gestion des machines virtuelles basée sur des règles et d'autres fonctionnalités vVols.

.Avant de commencer
Vérifiez que VASA Provider n'est pas exécuté sur les machines virtuelles que vous prévoyez de migrer. Si vous migrez une machine virtuelle exécutant VASA Provider vers un datastore vVols, vous ne pourrez effectuer aucune opération de gestion, y compris la mise sous tension des machines virtuelles qui se trouvent sur des datastores vVols.

.Description de la tâche
Lorsque vous migrez d'un datastore NFS ou VMFS vers un datastore vVols, le serveur vCenter utilise les API vStorage pour l'intégration de baies (VAAI) pour les données déplacées depuis les datastores VMFS, mais pas depuis les fichiers VMDK NFS. Les déchargements VAAI réduisent généralement la charge de l'hôte.

.Étapes
. Cliquez avec le bouton droit de la souris sur la machine virtuelle à migrer et sélectionnez *migrer*.
. Sélectionnez *changer stockage uniquement*, puis *Suivant*.
. Sélectionnez un format de disque virtuel, une stratégie de stockage de machine virtuelle et une banque de données vVol qui correspondent aux fonctionnalités de la banque de données que vous migrez.
. Vérifiez les paramètres et sélectionnez *Terminer*.

