---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Vous devez prendre en compte certaines considérations lors de la migration des machines virtuelles existantes dans votre data Center. 
---
= Considérations relatives à la migration et au clonage de machines virtuelles pour ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la migration de machines virtuelles existantes dans votre data Center, vous devez prendre en compte certaines considérations.



== Migrer des machines virtuelles protégées

Vous pouvez migrer les machines virtuelles protégées vers :

* Même datastore vVvols dans un autre hôte ESXi
* Il existe un autre datastore compatible vVvols dans le même hôte ESXi
* Il existe un autre datastore compatible vVvols dans un hôte VMware ESXi différent


Si vous migrez la machine virtuelle vers un autre FlexVol volume, le système met à jour le fichier de métadonnées de ce volume avec les informations de la machine virtuelle. Si une machine virtuelle est migrée vers un autre hôte ESXi mais avec le même stockage, le fichier de métadonnées du FlexVol volume sous-jacent ne sera pas modifié.



== Machines virtuelles protégées par des clones

Vous pouvez cloner des machines virtuelles protégées à plusieurs méthodes :

* Même conteneur du même volume FlexVol à l'aide du groupe de réplication
+
Le fichier de métadonnées du volume FlexVol est mis à jour avec les détails de la machine virtuelle clonée.

* Même conteneur d'un autre volume FlexVol utilisant le groupe de réplication
+
Volume FlexVol où la machine virtuelle clonée est placée, le fichier de métadonnées est mis à jour avec les détails de la machine virtuelle clonée.

* Il existe un autre conteneur ou datastore vvols
+
Volume FlexVol sur lequel la machine virtuelle clonée est placée, le fichier de métadonnées est mis à jour les informations relatives à la machine virtuelle.



VMware ne prend actuellement pas en charge les machines virtuelles clonées sur un modèle de machine virtuelle.

Le clonage d'une machine virtuelle protégée est pris en charge.

Voir https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Création d'une machine virtuelle pour le clonage"] pour plus de détails.



== Snapshots de machine virtuelle

Actuellement, seuls les snapshots de machine virtuelle sans mémoire sont pris en charge. Si la machine virtuelle possède une copie Snapshot de la mémoire, la machine virtuelle n'est pas prise en compte pour sa protection.

Vous ne pouvez pas non plus protéger les machines virtuelles non protégées qui disposent d’un instantané de mémoire.  Pour cette version, vous devez supprimer l'instantané de mémoire avant d'activer la protection de la machine virtuelle.

Pour une machine virtuelle Windows avec le type de stockage ASA r2, un instantané de la machine virtuelle est en lecture seule.  Lorsque vous mettez la VM sous tension, le fournisseur VASA crée un LUN à partir de l'instantané en lecture seule et active les IOPS.  Lorsque vous mettez la machine virtuelle hors tension, le fournisseur VASA supprime le LUN et désactive les IOPS.
