---
permalink: manage/mount-a-vvols-datastore.html 
sidebar: sidebar 
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount 
summary: Montez un datastore vVols sur des hôtes supplémentaires pour fournir un accès au stockage dans votre environnement virtuel. 
---
= Monter un datastore vVols dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez monter un datastore VMware Virtual Volumes (vVols) sur un ou plusieurs hôtes supplémentaires afin de fournir un accès au stockage à ces hôtes. Vous pouvez démonter un datastore vVols uniquement via les API au niveau de l’hôte. Le démontage d’un datastore au niveau du cluster n’est pas pris en charge.


NOTE: Après avoir ajouté l'hôte, attendez la fin de la découverte planifiée de l'hôte avant qu'il n'apparaisse dans ONTAP tools. Vous pouvez également lancer la découverte manuellement depuis l'écran de présentation des NetApp ONTAP tools. Pour savoir comment ajouter un hôte ESXi à votre cluster vSphere, consultez  https://techdocs.broadcom.com/["Broadcom Documentation technique"].

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit de la souris sur le datastore et sélectionnez *NetApp ONTAP Tools* > *Mount datastore*.
. Dans la boîte de dialogue *Mount datastores on hosts*, sélectionnez les hôtes sur lesquels vous souhaitez monter le datastore, puis sélectionnez *Mount*.


Le panneau des tâches récentes affiche la progression.

.Sujet connexe
link:../manage/add-vsphere-host.html["Ajouter de nouveaux hôtes VMware vSphere"]
