---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: Montez les banques de données sur des hôtes supplémentaires après avoir ajouté des hôtes à votre environnement VMware. 
---
= Monter les datastores NFS et VMFS dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le montage d'une banque de données permet d'accéder au stockage depuis des hôtes supplémentaires après que vous les avez ajoutés à votre environnement VMware.


NOTE: Après avoir ajouté l'hôte, attendez la fin de la découverte planifiée de l'hôte avant qu'il n'apparaisse dans ONTAP tools. Vous pouvez également lancer la découverte manuellement depuis l'écran de présentation des NetApp ONTAP tools. Pour savoir comment ajouter un hôte ESXi à votre cluster vSphere, consultez  https://techdocs.broadcom.com/["Broadcom Documentation technique"].

.Description de la tâche
* Certaines actions du clic droit sont désactivées ou indisponibles selon la version du client vSphere et le type de datastore sélectionné.
+
** Si vous utilisez vSphere client 8.0 ou une version ultérieure, certaines options du clic droit sont masquées.
** De vSphere 7.0U3 à vSphere 8.0, même si les options apparaissent, l'action est désactivée.


* vSphere désactive l'option de montage de la banque de données lorsque le cluster hôte est protégé par des configurations uniformes.


.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation de gauche, sélectionnez les centres de données contenant les hôtes.
. Pour monter des banques de données NFS/VMFS sur un hôte ou un cluster d'hôtes, cliquez avec le bouton droit et sélectionnez * Outils NetApp ONTAP * > *Monter les banques de données *.
. Sélectionnez les datastores à monter et sélectionnez *Mount*.


.Et la suite ?
Vous pouvez suivre la progression dans le panneau des tâches récentes.

.Sujet connexe
link:../manage/add-vsphere-host.html["Ajouter de nouveaux hôtes VMware vSphere"]
