---
permalink: manage/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 'L"action Supprimer le datastore supprime le datastore. Dans le cas d"un datastore NFS ou VMFS, une boîte de dialogue s"affiche avec la liste des machines virtuelles qui utilisent le datastore.' 
---
= Protéger le cluster hôte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revdate: ONTAP tools for VMware vSphere manages protection of a host cluster.


Tous les datastores appartenant au SVM sélectionné (et montés sur un ou plusieurs hôtes du cluster) sont protégés (pour les SMAs) sous un cluster hôte.

.Prérequis
Assurez-vous que les conditions suivantes sont remplies avant de protéger le cluster hôte : . Le cluster hôte ne dispose que de datastores d'un SVM. La version du SVM (SB) doit être supérieure à 9.15.1 . Les datastores montés sur le cluster hôte ne doivent pas être montés sur des hôtes extérieurs au cluster. . Tous les datastores montés sur le cluster hôte doivent être des datastores VMFS. . Tout volume FlexVol/LUN formant des datastores montés sur le cluster hôte ne doit pas faire partie d'un groupe de cohérence existant. . Les FlexVol ou LUN ne doivent pas faire partie d'une relation SnapMirror

.Étapes
. Connectez-vous au client vSphere à l'aide de `\https://vcenterip/ui`
. Cliquez avec le bouton droit de la souris sur un cluster hôte, puis sélectionnez *NetApp ONTAP Tools* > *Protect Cluster*.
. Dans la fenêtre protéger le cluster, entrez les paramètres de protection des datastores à protéger. Le cluster hôte ne peut avoir de datastores qu'à partir d'un SVM (Cluster).
. Sélectionnez l'une des options ONTAP cluster and Storage VM cibles.
. Cochez la case *Activer l'instantané local* pour associer une stratégie d'instantané local aux volumes de sauvegarde des datastores.
. Cochez *Activer SnapMirror* et *Ajouter une relation* pour protéger les datastores avec la stratégie AutomatedFailoverDuplex sélectionnée, le cluster cible et la machine virtuelle de stockage cible.
. Pour une configuration uniforme, sélectionnez le bouton bascule *Uniform Host Configuration* sur TRUE.
. Fournit *proximité hôte* ou *accès* pour chaque hôte, en fonction de la sélection du bouton de basculement de configuration hôte uniforme.
. Sélectionnez *Ajouter*.
. Consultez la page de résumé et sélectionnez protéger.


Une tâche est créée dans vCenter. Utilisez l'ID de travail généré pour contrôler la tâche.
