---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down 
summary: 'Supprimez un datastore vVols uniquement lorsqu"il ne reste plus aucun vVols sur le datastore sélectionné.' 
---
= Réduire la taille d'un vVols datastore dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Supprimez des volumes d'une banque de données vVols dans ONTAP tools pour réduire la capacité lorsque vous n'avez plus besoin du stockage supplémentaire.

Utilisez l'action « Supprimer le stockage de la banque de données » sur toute banque de données vVols gérée par les outils ONTAP dans vCenter Server.

Vous ne pouvez pas supprimer de stockage d'un volume s'il contient des vVols ; l'option de suppression est désactivée pour ces volumes. Lors de la suppression de volumes de la banque de données, vous avez également la possibilité de supprimer les volumes sélectionnés du stockage ONTAP.


NOTE: L'opération de réduction de la banque de données vVols n'est pas prise en charge pour les banques de données vVols basées sur les systèmes ASA r2.

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit sur la banque de données vVol et sélectionnez *NetApp ONTAP tools* > *Supprimer le stockage de la banque de données*.
. Sélectionnez les volumes qui ne possèdent pas de vVols et sélectionnez *Supprimer*.
+

NOTE: L'option permettant de sélectionner le volume sur lequel vVols résident est désactivée.

. Dans la fenêtre contextuelle *Supprimer le stockage*, cochez la case à cocher *Supprimer les volumes du cluster ONTAP* pour supprimer les volumes de la banque de données et du stockage ONTAP, puis sélectionnez *Supprimer*.

