---
permalink: manage/reports.html 
sidebar: sidebar 
keywords:  
summary: Le plug-in ONTAP Tools for VMware vSphere fournit des rapports pour les machines virtuelles et les datastores. 
---
= Rapports sur les outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in ONTAP Tools for VMware vSphere fournit des rapports pour les machines virtuelles et les datastores. Lorsque vous sélectionnez l'icône du plug-in NetApp ONTAP Tools for VMware vSphere dans la section des raccourcis du client vCenter, l'interface utilisateur accède à la page Présentation. Sélectionnez l'onglet Rapports pour afficher la machine virtuelle et le rapport datastores.

Le rapport Machines virtuelles affiche la liste des machines virtuelles découvertes (doivent avoir au moins un disque provenant de banques de données basées sur le stockage ONTAP ) avec des mesures de performances. Lorsque vous développez l'enregistrement de la machine virtuelle, l'interface affiche toutes les informations relatives au disque et à la banque de données.

Le rapport sur les banques de données répertorie les banques de données découvertes ou reconnues par les ONTAP tools for VMware vSphere qui utilisent un stockage ONTAP , avec des indicateurs de performance.

Vous pouvez utiliser l'option gérer les colonnes pour masquer ou afficher différentes colonnes.
