---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords: reset ONTAP tools Manager password, manager admin credential recovery, token-based password reset, appliance administrator reset 
summary: 'Réinitialisez les informations d"identification de l"administrateur d"ONTAP tools Manager à l"aide d"un jeton de console de maintenance.' 
---
= Réinitialiser le mot de passe du gestionnaire ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous oubliez le mot de passe du gestionnaire d'outils ONTAP , vous pouvez rétablir l'accès administrateur à l'aide d'un jeton de réinitialisation généré à partir de la console de maintenance des ONTAP tools for VMware vSphere .

.Étapes
. Ouvrez un navigateur Web et accédez à  `https://<ONTAPtoolsIP>:8443/virtualization/ui/` pour ouvrir ONTAP tools Manager.
. Sur la page de connexion, sélectionnez *Réinitialiser le mot de passe*.
. Générez un jeton de réinitialisation de mot de passe à l'aide des ONTAP tools for VMware vSphere :
+
.. Connectez-vous au serveur vCenter.
.. Localisez la machine virtuelle ONTAP tools et lancez la console Web.
.. Connectez-vous en utilisant les `maint` identifiants.
.. Entrer `2` pour sélectionner *Configuration système*.
.. Saisissez  `3` pour sélectionner *Générer un jeton pour réinitialiser le mot de passe de l’interface utilisateur du gestionnaire*, et notez le jeton.


. Dans la boîte de dialogue de réinitialisation du mot de passe, saisissez le jeton de réinitialisation, le nom d'utilisateur et le nouveau mot de passe.
. Sélectionnez *Réinitialiser* pour mettre à jour les informations d'identification.
. Connectez-vous à ONTAP Tools Manager avec le nouveau mot de passe.

