---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: 'Si vous avez oublié le mot de passe du gestionnaire d"outils ONTAP, vous pouvez réinitialiser les informations d"identification de l"administrateur à l"aide du jeton généré par les outils ONTAP pour la console de maintenance VMware vSphere.' 
---
= Réinitialisez le mot de passe du gestionnaire d'outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous oubliez le mot de passe du gestionnaire d'outils ONTAP , vous pouvez rétablir l'accès administrateur à l'aide d'un jeton de réinitialisation généré à partir de la console de maintenance des ONTAP tools for VMware vSphere .

.Étapes
. Ouvrez un navigateur web et accédez à `https://<ONTAPtoolsIP>:8443/virtualization/ui/` pour accéder au gestionnaire d'outils ONTAP .
. Sur la page de connexion, sélectionnez *Réinitialiser le mot de passe*.
. Générez un jeton de réinitialisation de mot de passe à l'aide des ONTAP tools for VMware vSphere :
+
.. Connectez-vous au serveur vCenter et ouvrez la console de maintenance.
.. Entrer `2` pour sélectionner *Configuration système*.
.. Entrer `3` pour sélectionner *Modifier le mot de passe de l'utilisateur 'maintenance'*.


. Dans la boîte de dialogue de réinitialisation du mot de passe, saisissez le jeton de réinitialisation, le nom d'utilisateur et le nouveau mot de passe.
. Sélectionnez *Réinitialiser* pour mettre à jour les informations d'identification.
. Connectez-vous à ONTAP Tools Manager avec le nouveau mot de passe.

