---
permalink: manage/reset-vasa-sra-credentials.html 
sidebar: sidebar 
keywords:  
summary: 'Entrez les détails du serveur NTP pour synchroniser les horloges de l"appliance ONTAP Tools.' 
---
= Réinitialiser les informations d'identification du fournisseur VASA et du SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous oubliez vos informations d'identification VASA Provider ou SRA, vous pouvez les réinitialiser avec un nouveau mot de passe à l'aide de l'interface du gestionnaire d'outils ONTAP .  Le nouveau mot de passe doit comporter entre 8 et 256 caractères.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez l'option *Paramètres* > *Informations d'identification du fournisseur VASA / SRA* > *Réinitialiser le mot de passe*.
. Entrez le nouveau mot de passe et confirmez-le.
. Sélectionnez *Enregistrer* pour appliquer les modifications.

