---
permalink: manage/resize-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Le redimensionnement d"un datastore vous permet d"augmenter le stockage des fichiers de votre machine virtuelle. Vous pouvez modifier la taille d"un datastore en fonction de l"évolution des exigences de votre infrastructure.' 
---
= Redimensionner les datastores NFS et VMFS dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le redimensionnement d'un datastore vous permet d'augmenter le stockage des fichiers de votre machine virtuelle. Vous pouvez modifier la taille d'un datastore en fonction de l'évolution des exigences de votre infrastructure.

.Description de la tâche
Vous pouvez augmenter la taille des banques de données NFS et VMFS.  Un FlexVol volume dans ces datastores ne peut pas diminuer en dessous de sa taille actuelle, mais peut croître jusqu'à 120 %.

.Étapes
. Sur la page d'accueil de vSphere client, sélectionnez *hosts and clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient le datastore.
. Cliquez avec le bouton droit de la souris sur le datastore NFS ou VMFS et sélectionnez *NetApp ONTAP Tools* > *Redimensionner le datastore*.
. Dans la boîte de dialogue Redimensionner, saisissez une nouvelle taille pour le magasin de données et sélectionnez *OK*.

