---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Les systèmes back-end de stockage sont des systèmes que les hôtes ESXi utilisent pour le stockage des données. 
---
= Gestion des systèmes back-end
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes back-end de stockage sont des systèmes que les hôtes ESXi utilisent pour le stockage des données.



== Découverte du stockage

Vous pouvez exécuter la découverte d'un backend de stockage à la demande sans attendre qu'une découverte planifiée mette à jour immédiatement les détails de stockage.  Pour les configurations MetroCluster , exécutez la découverte des outils ONTAP manuellement après un basculement.

Suivez les étapes ci-dessous pour découvrir les systèmes back-end.

.Étapes
. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu des ellipses verticales et sélectionnez *découvrir le stockage*


Vous pouvez suivre la progression dans le panneau tâches récentes.



== Modification des systèmes back-end de stockage

Vous pouvez modifier les informations d’identification du backend de stockage ou le nom du port.  Vous pouvez également modifier le backend de stockage pour les clusters ONTAP globaux à l'aide du gestionnaire d'outils ONTAP .  Si le certificat expire dans 30 jours ou moins, les outils ONTAP affichent un avertissement.  Modifiez le backend de stockage et téléchargez le nouveau certificat depuis l'administrateur ONTAP .

Lorsque vous modifiez le backend de stockage, les ONTAP tools for VMware vSphere effectuent une découverte du backend de stockage pour mettre à jour les détails de stockage.

Suivez les étapes de cette section pour modifier un système back-end de stockage.

. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu des ellipses verticales et sélectionnez *Modifier* pour modifier les informations d'identification ou le nom du port. Vous pouvez suivre la progression dans le panneau tâches récentes.


Modifiez les clusters ONTAP globaux avec le gestionnaire d’outils ONTAP comme suit.

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez les systèmes back-end de stockage dans la barre latérale.
. Sélectionnez le back-end de stockage à modifier.
. Sélectionnez le menu ellipses verticales et sélectionnez *Modifier*.
. Vous pouvez modifier les informations d'identification ou le port. Entrez *Nom d'utilisateur* et *Mot de passe* pour modifier le backend de stockage.




== Suppression des systèmes back-end

Vous devez supprimer tous les magasins de données attachés au backend de stockage avant de le supprimer.  Suivez les étapes ci-dessous pour supprimer un backend de stockage.

. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu des ellipses verticales et sélectionnez *Supprimer*.  Assurez-vous que le backend de stockage ne contient aucun magasin de données.  Vous pouvez suivre la progression dans le panneau des tâches récentes.


Vous pouvez effectuer l'opération de suppression pour les clusters ONTAP globaux à l'aide du gestionnaire d'outils ONTAP.

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *systèmes back-end de stockage* dans la barre latérale.
. Sélectionnez le système back-end de stockage à supprimer
. Sélectionnez le menu ellipses verticales et sélectionnez *Supprimer*.




== Vue détaillée du système back-end de stockage

La page backend de stockage répertorie tous les backends de stockage.  Vous pouvez effectuer des opérations de découverte, de modification et de suppression de stockage sur les backends de stockage que vous avez ajoutés, mais pas sur le SVM enfant individuel sous le cluster.

Sélectionnez le cluster parent ou l’enfant pour afficher le résumé du composant.  Pour le cluster parent, utilisez la liste déroulante des actions pour découvrir le stockage, modifier ou supprimer le backend de stockage.

La page de résumé fournit les détails suivants :

* État du système back-end de stockage
* Informations sur la capacité
* Informations de base sur la machine virtuelle
* Détails du certificat tels que le statut du certificat et la date d'expiration.
* Informations réseau telles que l'adresse IP et le port du réseau.  Pour le SVM enfant, les informations sont les mêmes que celles du backend de stockage parent.
* Privileges autorisés et restreints pour le backend de stockage.  Pour le SVM enfant, les informations sont les mêmes que celles du backend de stockage parent.  Les outils ONTAP affichent les privilèges uniquement sur les backends de stockage basés sur des clusters.  Si vous ajoutez SVM comme backend de stockage, les informations sur les privilèges ne sont pas affichées.
* La vue détaillée du cluster système ASA r2 n'inclut pas l'onglet des niveaux locaux lorsque la propriété désagrégée est définie sur « vrai » pour le SVM ou le cluster.
* Pour les systèmes SVM ASA r2, le portlet capacité n'est pas affiché. Le portail de capacité n'est requis que lorsque la propriété désagrégée est définie comme « true » pour le SVM ou le cluster.
* Pour les systèmes ASA r2 SVM, la section informations de base présente le type de plateforme.


L'onglet interface fournit des informations détaillées sur l'interface.

L'onglet niveaux locaux fournit des informations détaillées sur la liste des agrégats.
