---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords: manage storage backends, ONTAP backend systems, storage backend operations, VMware datastore backend configuration 
summary: Gérez les systèmes de stockage utilisés par les hôtes ESXi pour le stockage des données. 
---
= Gérer les backends de stockage dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les backends de stockage sont les ressources de stockage ONTAP que les hôtes ESXi utilisent pour le stockage des données. Vous pouvez les découvrir, les modifier et les supprimer dans ONTAP tools for VMware vSphere.



[[discover-storage]]
== Découverte du stockage

Vous pouvez exécuter la découverte du système de stockage à la demande, sans attendre la prochaine découverte planifiée pour la mise à jour des informations de stockage. Pour les configurations MetroCluster, exécutez manuellement la découverte des outils ONTAP après un basculement.

Suivez ces étapes pour découvrir les systèmes de stockage backends.

.Étapes
. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu à trois points verticaux et sélectionnez *Découvrir le stockage*


Vous pouvez suivre la progression dans le panneau tâches récentes.



[[modify-storage-backends]]
== Modification des systèmes back-end de stockage

Vous pouvez modifier les informations d'identification du backend de stockage ou le nom du port. Vous pouvez également modifier le backend de stockage pour les clusters ONTAP globaux à l'aide de ONTAP tools Manager. Si le certificat expire dans 30 jours ou moins, ONTAP tools affiche un avertissement. Modifiez le backend de stockage et téléversez le nouveau certificat depuis l'administrateur ONTAP.

Lorsque vous modifiez le backend de stockage, les ONTAP tools for VMware vSphere effectuent une découverte du backend de stockage pour mettre à jour les détails de stockage.

Suivez les étapes de cette section pour modifier un système back-end de stockage.

. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu à trois points verticaux, puis *Modifier* pour modifier les identifiants ou le nom du port. Vous pouvez suivre la progression dans le panneau des tâches récentes.


Modifiez les clusters ONTAP globaux avec le gestionnaire d’outils ONTAP comme suit.

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *systèmes back-end de stockage* dans la barre latérale.
. Sélectionnez le back-end de stockage à modifier.
. Sélectionnez le menu à trois points verticaux et sélectionnez *Modifier*.
. Vous pouvez modifier les identifiants ou le port. Saisissez le *nom d'utilisateur* et le *mot de passe* pour mettre à jour les identifiants du stockage backend.




[[remove-storage-backends]]
== Suppression des systèmes back-end

Vous devez supprimer tous les magasins de données attachés au backend de stockage avant de le supprimer.  Suivez les étapes ci-dessous pour supprimer un backend de stockage.

. Connectez-vous au client vSphere.
. Dans la page raccourcis, sélectionnez *NetApp ONTAP Tools* dans la section modules externes.
. Dans le volet gauche des outils ONTAP , accédez à *Backends de stockage* et sélectionnez un backend de stockage.
. Sélectionnez le menu à trois points verticaux, puis *Supprimer*. Vérifiez que le backend de stockage ne contient aucun datastore. Vous pouvez suivre la progression dans le panneau des tâches récentes.


Vous pouvez supprimer les clusters ONTAP globaux à l'aide du Gestionnaire d'outils ONTAP.

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *systèmes back-end de stockage* dans la barre latérale.
. Sélectionnez le système back-end de stockage à supprimer
. Sélectionnez le menu à trois points verticaux et sélectionnez *Supprimer*.




[[drill-down-view-of-storage-backend]]
== Vue détaillée du système back-end de stockage

La page relative aux systèmes de stockage répertorie tous les systèmes de stockage. Vous pouvez découvrir, modifier et supprimer les systèmes de stockage que vous avez ajoutés, mais vous ne pouvez pas effectuer ces opérations sur les SVM enfants individuelles du cluster.

Sélectionnez le cluster parent ou l’enfant pour afficher le résumé du composant.  Pour le cluster parent, utilisez la liste déroulante des actions pour découvrir le stockage, modifier ou supprimer le backend de stockage.

La page de résumé fournit les détails suivants :

* État du système back-end de stockage
* Informations sur la capacité
* Informations de base sur la machine virtuelle
* Détails du certificat tels que le statut du certificat et la date d'expiration.
* Informations réseau telles que l'adresse IP et le port du réseau.  Pour le SVM enfant, les informations sont les mêmes que celles du backend de stockage parent.
* Privileges autorisés et restreints pour le stockage backend. Pour la SVM enfant, les informations sont identiques à celles du stockage backend parent. ONTAP tools affiche les privileges uniquement sur les stockages backend basés sur cluster. Si vous ajoutez une SVM comme stockage backend, les informations de privilege ne sont pas affichées.
* La vue détaillée du cluster système ASA r2 n'inclut pas l'onglet des niveaux locaux lorsque la propriété désagrégée est définie sur « true » pour le SVM ou le cluster.
* Pour les systèmes ASA r2 SVM, le portlet de capacité n'est pas affiché. Le portlet de capacité est requis uniquement lorsque la propriété « disaggregated » est définie sur « true » pour la SVM ou le cluster.
* Pour les systèmes ASA r2 SVM, la section informations de base présente le type de plateforme.


L'onglet interface fournit des informations détaillées sur l'interface.

L'onglet niveaux locaux fournit des informations détaillées sur la liste des agrégats.
