---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: 'L"action de démontage du datastore démonte un datastore NFS ou VMFS des hôtes ESXi. L"action démonter le datastore est activée pour les datastores NFS et VMFS découverts ou gérés par les outils ONTAP pour VMware vSphere.' 
---
= Démontez les datastores NFS et VMFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'action « Démonter le datastore » supprime un datastore NFS ou VMFS des hôtes ESXi.  Il est disponible pour les banques de données découvertes ou gérées par les ONTAP tools for VMware vSphere.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un objet de banque de données NFS ou VMFS et sélectionnez *Démonter la banque de données*.
+
Le client vSphere ouvre une boîte de dialogue et liste les hôtes ESXi qui montent la banque de données. Lorsque l'opération est effectuée sur une banque de données protégée, un message d'avertissement s'affiche à l'écran.

. Sélectionnez un ou plusieurs hôtes ESXi pour démonter le datastore.
+
Vous ne pouvez pas démonter le datastore de tous les hôtes. L'interface utilisateur suggère d'utiliser l'opération de suppression de datastore.

. Sélectionnez le bouton *Unmount*.
+
Si le datastore fait partie d'un cluster hôte protégé, un message d'avertissement s'affiche.




NOTE: Si la banque de données protégée est démontée, le paramètre de protection existant peut entraîner une protection partielle. Consultez link:../manage/edit-hostcluster-protection.html["Modifier le cluster hôte protégé"] pour permettre une protection complète.

.Et la suite ?
Vous pouvez suivre la progression dans le panneau tâches récentes.
