---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords: unmount NFS VMFS datastore, remove datastore from host, ONTAP tools datastore unmount, ESXi host storage detach 
summary: 'Démontez les datastores NFS ou VMFS des hôtes ESXi à l"aide des ONTAP tools.' 
---
= Démontez les datastores NFS et VMFS dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez cette tâche pour démonter une banque de données NFS ou VMFS depuis des hôtes ESXi. Le démontage des banques de données au niveau du cluster n'est pas pris en charge via l'interface utilisateur ni les API.

À partir de la version 10.6 des ONTAP tools, le démontage est bloqué pour les datastores VMFS protégés.

.Étapes
. Connectez-vous au client vSphere.
. Cliquez avec le bouton droit sur un objet de datastore NFS ou VMFS et sélectionnez *Démonter le datastore*.
+
Le vSphere Client ouvre une boîte de dialogue et affiche la liste des hôtes ESXi qui montent la banque de données. Si la banque de données est protégée, ONTAP tools bloque la requête et affiche un message indiquant que la banque de données est sous protection et ne peut pas être démontée.

. Sélectionnez un ou plusieurs hôtes ESXi pour démonter le datastore.
+
Il est impossible de démonter le datastore de tous les hôtes. L'interface utilisateur suggère d'utiliser plutôt l'opération de suppression du datastore.

. Sélectionnez le bouton *Unmount*.
+
L'option *Démonter le datastore* est disponible uniquement lorsque l'hôte est déplacé hors du cluster d'hôtes protégé.




NOTE: Si un datastore est protégé, vous devez supprimer la protection avant de pouvoir le démonter.

.Et la suite ?
Vous pouvez suivre la progression dans le panneau tâches récentes.
