---
permalink: manage/update-proxyurl.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir des options disponibles dans l"interface utilisateur graphique \(GUI\) des outils ONTAP pour VMware vSphere. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.' 
---
= Mettre à jour l'URL du proxy AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mettez à jour l'URL du proxy AutoSupport pour garantir le bon fonctionnement de la fonctionnalité AutoSupport dans les cas où un serveur proxy est utilisé pour le contrôle d'accès au réseau ou les mesures de sécurité. Il permet de router les données AutoSupport via le proxy approprié, ce qui garantit une transmission et une conformité sécurisées.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *Paramètres* dans la barre latérale.
. Sélectionnez l'option *Paramètres* > *télémétrie* > *Modifier*.
. Entrez une *URL proxy* valide et enregistrez les modifications.
+
Si vous désactivez AutoSupport, l'URL du proxy est également désactivée.


