---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez mettre à jour les informations d"identification du serveur vCenter à l"aide de la console de maintenance.' 
---
= Mettre à jour les informations d'identification du serveur vCenter dans ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour les informations d'identification de l'instance vCenter Server à l'aide de la console de maintenance.

.Avant de commencer
Vous devez disposer des informations d'identification de l'utilisateur de maintenance.

.Description de la tâche
Si vous avez modifié les informations d'identification de vCenter Server après le déploiement, mettez-les à jour en suivant cette procédure.

.Étapes
. Depuis vCenter Server, ouvrez une console vers VASA Provider.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `2` pour sélectionner le menu de configuration du système.
. Entrer `8` modifier les informations d'identification vCenter.

